$STORAGE:2

      PROGRAM BLDELEM
C
C    THIS PROGRAM READS DATAEASE STN ELEMENT RECORDS
C       AND WRITES THE INFORMATION TO TO A DIRECT FILE FOR USE BY
C       THE CLICOM QC ROUTINES.
C       THE INPUT DATA IS READ AS AN UNFORMATTED BINARY FILE,
C       READING ALL INPUT INTO THE CHARACTER ARRAY INREC.  THE 
C       VARIABLES WITHIN THE RECORD ARE EQUIVALENCED TO THE 
C       APPROPRIATE POSITION WITHIN INREC.
C
C  LOCAL VARIABLES
      CHARACTER*78 MSGLN1,MSGLN2,MSGLN3
      CHARACTER*32 INFILE,OUTFIL
      CHARACTER*16 SRTKEY,DDISK
      CHARACTER*22 FILNAME
      CHARACTER*8 STNID,MSGTXT,INBDATE,INEDATE      
      CHARACTER*3 INELEM, INRELELEM
      CHARACTER*2 RDISK
      CHARACTER*1 INREC(57)
      CHARACTER*1 INOBS,INDIG,INSCHED,INSPCOBS,INRELSHIP,NULL
      INTEGER*2 HEADER(3),IOBS,ELEM,DIGITIZED,SCHEDULE
     +         ,RELELEM,SPCOBS,RELSHIP
      INTEGER*4 BDATE,EDATE,NUMREC,I1,NCOUNT
C
C    EQUIVALENCE THE INPUT VARIABLES TO THE INPUT RECORD STRING
C
      EQUIVALENCE (HEADER,INREC(1)),  (STNID,INREC(6)),
     +            (INOBS,INREC(14)),  (INELEM,INREC(15)),
     +            (INBDATE,INREC(18)),(INEDATE,INREC(26)),
     +            (INDIG,INREC(51)),  (INSCHED,INREC(52)),
     +            (INSPCOBS,INREC(53)), (INRELELEM,INREC(54)),
     +            (INRELSHIP,INREC(57))
C
      NULL = CHAR(0)
C
      CALL GETMSG(206,MSGLN1)
      CALL GETMSG(208,MSGLN2)
      CALL GETMSG(209,MSGLN3)
      CALL GETMSG(999,MSGLN3)
      WRITE(*,*) MSGLN1
      WRITE(*,*) MSGLN2
      WRITE(*,*) ' ' 
C
C   FIND THE NAME OF THE DATAEASE STN ELEMENT FILE
C
      CALL FNDFIL('STN ELEMENT             ',FILNAME,NUMREC)
      IF (FILNAME.EQ.'          ') THEN
         STOP
      END IF
      LEND = 16
      CALL GETDSC(RDISK,DDISK,LEND)
      INFILE(1:LEND) = DDISK
      ILEN = LEND + 13
      INFILE(LEND+1:LEND+1) = '\'
      INFILE(LEND+2:ILEN) = FILNAME(3:14)
C
C   SORT THE STN ELEMENT FILE
C
      CALL COLOAD
      SRTKEY = '2,A,6,12,A,26,8'
      OUTFIL = '  \DATA\TMP1.TMP'
      OUTFIL(1:2) = RDISK
      OPEN (63,FILE=OUTFIL,STATUS='UNKNOWN',FORM='BINARY',IOSTAT=IOCHK)
      IF (IOCHK.NE.0) THEN
         CALL OPENMSG(OUTFIL,'BLDELEM-1   ',IOCHK)
         STOP ' '
      ELSE
         CLOSE(63)
      END IF
      IF (NUMREC.GT.0) THEN
         CALL SORT (INFILE,ILEN,OUTFIL,16,57,SRTKEY)
      END IF
C
      WRITE(*,*) MSGLN3 
C
   10 CONTINUE
      OPEN(27,FILE=OUTFIL,STATUS='OLD',FORM='BINARY',IOSTAT=IOCHK)
      IF(IOCHK.NE.0)THEN
         CALL OPENMSG(OUTFIL,'BLDELEM     ',IOCHK)
         GO TO 10
      END IF   
C
      OPEN(32,FILE='P:\DATA\STNELEM.INF',STATUS='OLD',
     +        ACCESS='DIRECT',RECL=30,IOSTAT=IOCHK)
      IF (IOCHK.EQ.0) THEN
C          .. DELETE FILE IF IT EXISTS
         CLOSE(32,STATUS='DELETE')
      ELSE IF (IOCHK.NE.6416) THEN
C          .. EXIT PROGRAM IF ERROR IS ANYTHING EXCEPT 'FILE NOT FOUND'
         CALL OPENMSG('P:\DATA\STNELEM.INF','BLDELEM     ',IOCHK)
         STOP ' '
      END IF
C       .. START WITH AN EMPTY FILE      
      OPEN(32,FILE='P:\DATA\STNELEM.INF',STATUS='NEW',
     +        ACCESS='DIRECT',RECL=30)
C
      NCOUNT = 0
      DO 100 I1 = 2,999999
   15    CONTINUE
         READ(27,END=200) INREC
         IF(HEADER(1).EQ.13 .OR. HEADER(1).EQ.15) GO TO 15
         DO 20 I2 = 1,8
            IF (STNID(I2:I2).EQ.NULL) THEN
               STNID(I2:I2) = ' '
            END IF
   20    CONTINUE
          
         IOBS = 0
         CALL MOVBYT(1,INOBS,1,IOBS,1)
         READ(INELEM,'(I3)',ERR=30) ELEM 
         GO TO 40
         
   30    CONTINUE
         WRITE(MSGTXT,'(4X,I4)') NCOUNT
         MSGTXT(1:3) = INELEM
         MSGTXT(4:4) = ','
         CALL WRTMSG(4,108,12,1,1,MSGTXT,8) 
         ELEM = -9999
   40    CONTINUE 
         READ(INBDATE,'(I8)',ERR=50) BDATE
         GO TO 60
   50    BDATE = -9999
   60    CONTINUE 
         IF (ELEM.EQ.0)THEN
            ELEM = -9999
         END IF
         READ(INEDATE,'(I8)',ERR=70) EDATE
         GO TO 80
   70    EDATE = -9999
   80    CONTINUE
         DIGITIZED = 0
         CALL MOVBYT(1,INDIG,1,DIGITIZED,1)
         SCHEDULE = 0
         CALL MOVBYT(1,INSCHED,1,SCHEDULE,1)
         SPCOBS = 0
         CALL MOVBYT(1,INSPCOBS,1,SPCOBS,1)
         READ(INRELELEM,'(I3)',ERR=90)RELELEM
         GO TO 95
   90    RELELEM = -9999
   95    IF (RELELEM.EQ.0)THEN
            RELELEM = -9999
         END IF
         RELSHIP = 0
         CALL MOVBYT(1,INRELSHIP,1,RELSHIP,1)
         IF (RELSHIP.LT.1.OR.RELSHIP.GT.10)THEN
            RELELEM = -9999
         END IF
C
         NCOUNT = NCOUNT + 1

         WRITE(32,REC=I1) STNID,IOBS,ELEM,BDATE,EDATE,DIGITIZED,
     +                    SCHEDULE,SPCOBS,RELELEM,RELSHIP
  100 CONTINUE
  200 CONTINUE
      WRITE(32,REC=1) NCOUNT
      CLOSE(27,STATUS='DELETE')
      CLOSE(32)
      WRITE(*,250) NCOUNT
  250 FORMAT(/,I5,' Station Element Records Written',//)
      STOP ' '
      END
