$STORAGE:2

      PROGRAM DEFMENU
C
C   ROUTINE TO DEFINE AND MODIFY MENUS IN THE FORTRAN MENU FILE, 
C   INCLUDING THE ABILITY TO COPY MENUS TO OR FROM OTHER MENU FILES.   
C
C   LOCAL VARIABLES 
C
      PARAMETER(MAXCHOICE=16,MAXFLD=24) 
      INTEGER*2 WIDTH,NUMCHOICE,FGCOLOR,BGCOLOR,HDRFGC,HDRBGC
     +         ,TLENGTH,CLENGTH
      INTEGER*2 WDTH,FGCOL,BGCOL,TLNTH,CLNTH,HBGC,HFGC
      CHARACTER*64 FILNAME,HLDREC
      CHARACTER*60 TITLE,FIELD(MAXFLD)
      CHARACTER*60 TTLE
      CHARACTER*32 CHOICE(MAXCHOICE)
      CHARACTER*32 CHCE(MAXCHOICE)
      CHARACTER*42 MENFIL
      CHARACTER*12 MENUNAME,INNAME,BLANK
      CHARACTER*12 INNME
      CHARACTER*8  FORMNAME
      CHARACTER*1 REPLY,RTNCODE,BORDER,DELMARK
      CHARACTER*1 BRDR
      CHARACTER*1 DELMK
      CHARACTER*2 RTNFLAG
      LOGICAL NEWMENU,WRTMENU
      DATA FIELD,BLANK /24*'          ','        '/
C
      FILNAME = 'P:\HELP\DEFMENU.HLP'
      MENFIL  = ' '
C
C   DETERMINE THE OPTION TO BE PERFORMED 
C
  20  CONTINUE
      CALL CLS
      IOPT=0
      NEWMENU = .TRUE.
      FORMNAME = 'DEFMENUS'
      MENUNAME = BLANK
      CALL LOCATE(3,15,IERR)
      CALL GETMNU('DEFINE MENUS',FILNAME,IOPT)
      IF (IOPT.EQ.0) THEN
         CLOSE(14)
         STOP ' '
      END IF 
C
C   OPEN THE MENU FILE FOR NON-SHARED WRITE ACCESS
C
   50 CONTINUE
      OPEN (14,FILE='P:\FORM\USERMENU.DEF',STATUS='OLD',ACCESS='DIRECT'
     +    ,RECL=602,IOSTAT=IOCHK)
      IF(IOCHK.NE.0) THEN
         CALL OPENMSG('P:\FORM\USERMENU.DEF  ','DEFMENU     ',IOCHK)
         GO TO 50
      END IF   
C
C  ASK FOR NEW MENU NAME OR SELECT FROM LIST OF EXISTING MENUS
C
      IF (IOPT.EQ.4.OR.IOPT.EQ.5)THEN
         GO TO 120
      END IF
C      
      IF (IOPT.GT.1) THEN
         RTNFLAG = '  '
         CALL LOCATE(0,0,IERR)
         CALL VALWIN(14,HLDREC,64,4,ICNTRL)
         MENUNAME = HLDREC(1:12)
C         IF (ICNTRL.EQ.1) THEN
C **DEBUG         
C            IOPT = 6
C            IOPT = 3
C         END IF
      ELSE
         CALL LOCATE(16,30,IERR)
         CALL WRTSTR('Menu Name: ',11,14,0)
         CALL GETSTR(0,MENUNAME,12,15,1,RTNFLAG)
      END IF
C
      IF (MENUNAME.EQ.BLANK.OR.RTNFLAG.EQ.'4F') THEN
         GO TO 20
      END IF
C
C   DETERMINE IF THE MENU ALREADY EXISTS AND SET RECORD TO IREC
C
      DO 100 IREC = 1,999
         READ(14,REC=IREC,ERR=120) DELMARK,INNAME,TITLE,BORDER
     +       ,(CHOICE(J),J=1,MAXCHOICE),WIDTH,NUMCHOICE
     +       ,HDRFGC,HDRBGC,FGCOLOR,BGCOLOR,TLENGTH,CLENGTH
         IF (INNAME.EQ.MENUNAME .AND. DELMARK.EQ.BLANK) THEN 
            NEWMENU = .FALSE.
            GO TO 120
         END IF
  100 CONTINUE
C  
  120 CONTINUE
C
C    OPTION 1 - NEW MENU TO BE DEFINED - INITIALIZE FORM VARIABLES
C
      IF (IOPT.EQ.1) THEN
         IF (NEWMENU) THEN
            WIDTH = 0
            TITLE = BLANK
            FGCOLOR = 14
            BGCOLOR = 0
            HDRFGC = 15
            HDRBGC = 1
            DO 150 I1 = 1,MAXCHOICE
               CHOICE(I1) = BLANK
  150       CONTINUE
C
C        THE MENU ALREADY EXISTS - ERROR
C
         ELSE
            CALL LOCATE(20,10,IERR)
            CALL WRTMSG(5,233,12,1,1,' ',0)
            GO TO 20
         END IF
C
C    OPTION 3 -  DELETE THIS MENU IF IT IS NOT PROTECTED
C
      ELSE IF (IOPT.EQ.3) THEN
         CALL LOCATE(20,45,IERR)
         IF (MENUNAME.EQ.'DEFINE FORMS'.OR.MENUNAME.EQ.
     +        'DEFINE MENUS'.OR.MENUNAME.EQ.'MAIN MENU') THEN
            CALL WRTMSG(5,234,12,1,1,' ',0)
         ELSE   
            CALL WRTMSG(5,414,14,1,0,' ',0)
            LGTH = LNG(MENUNAME)
            CALL WRTMSG(4,416,14,0,0,MENUNAME,LGTH)
            LGTH = MIN0((LGTH+20),79)
            CALL LOCATE(21,LGTH,IERR)
            CALL OKREPLY(REPLY,RTNCODE)
            CALL CLRMSG(5)
            CALL CLRMSG(4)
            IF (REPLY.EQ.'Y')THEN
               DELMARK = '*'
               WRITE(14,REC=IREC) DELMARK,INNAME,TITLE,BORDER
     +             ,(CHOICE(J),J=1,MAXCHOICE),WIDTH,NUMCHOICE
     +             ,HDRFGC,HDRBGC,FGCOLOR,BGCOLOR,TLENGTH,CLENGTH
               CALL WRTMSG(5,413,14,1,1,' ',0)
               CALL CLRMSG(5)
               CALL CLRMSG(4)
            ENDIF
         END IF
         GO TO 20
C
C    OPTION 4 -  COPY A MENU TO CLICOM FROM ANOTHER FILE
C
      ELSE IF (IOPT.EQ.4)THEN
  155    CALL LOCATE(16,30,IERR)
         CALL WRTMSG(5,420,14,0,0,' ',0)
         CALL LOCATE(21,5,IERR)
         CALL GETSTR(0,MENFIL,42,15,1,RTNFLAG)
         CALL CLRMSG(5)
         CALL CLRMSG(4)
         IF (RTNFLAG .EQ. '4F' .OR. MENFIL .EQ. ' ') THEN
            GO TO 20
         ENDIF
         OPEN (66,FILE=MENFIL,STATUS='OLD',ACCESS='DIRECT'
     +       ,RECL=602,IOSTAT=IOCHK)
         IF(IOCHK.NE.0) THEN
            CALL OPENMSG(MENFIL,'DEFMENU     ',IOCHK)
            GO TO 155
         END IF
C
C  ASK FOR NEW MENU NAME OR SELECT FROM LIST OF EXISTING MENUS
C
         RTNFLAG = '  '
         CALL LOCATE(0,0,IERR)
         CALL VALWIN(66,HLDREC,64,4,ICNTRL)
         MENUNAME = HLDREC(1:12)
C
      IF (MENUNAME.EQ.BLANK.OR.RTNFLAG.EQ.'4F') THEN
         GO TO 20
      END IF
C
C       .. READ THE MENU DEFINITION FROM THE SOURCE FILE
C
      DO 157 IREC = 1,999
         READ(66,REC=IREC,ERR=157) DELMARK,INNAME,TITLE,BORDER
     +       ,(CHOICE(J),J=1,MAXCHOICE),WIDTH,NUMCHOICE
     +       ,HDRFGC,HDRBGC,FGCOLOR,BGCOLOR,TLENGTH,CLENGTH
         IF (INNAME.EQ.MENUNAME .AND. DELMARK.EQ.BLANK) THEN 
            GO TO 158
         END IF
  157 CONTINUE
C       .. MENU NAME NOT FOUND IN SOURCE FILE 
      CALL WRTMSG(5,232,12,1,1,' ',0)
      CLOSE (66)
      GO TO 20
  158 CONTINUE
      CLOSE (66)
C
C       .. DETERMINE IF THE MENU ALREADY EXISTS IN USERMENU.DEF
C
      WRTMENU = .TRUE.
      NEWMENU = .TRUE.
      DO 160 IREC = 1,999
         READ(14,REC=IREC,ERR=162) DELMK,INNME,TTLE,BRDR
     +       ,(CHCE(J),J=1,MAXCHOICE),WDTH,NMCHCE
     +       ,HFGC,HBGC,FGCOL,BGCOL,TLNTH,CLNTH
         IF (DELMK.NE.'*' .AND. INNME.EQ.MENUNAME) THEN 
C             .. MENU NAME EXISTS
            NEWMENU=.FALSE.
            MNUREC = IREC
            GO TO 162 
         END IF
  160 CONTINUE
         WRTMENU=.FALSE.
         NEWMENU=.FALSE.
  162 CONTINUE
      IF (WRTMENU .AND. .NOT.NEWMENU) THEN
C
C          .. MENU NAME EXISTS -- ASK USER TO OVERWRITE OLD MENU
         CALL WRTMSG(5,421,14,1,0,' ',0)
         CALL LOCATE(21,5,IERR)
         CALL OKREPLY(REPLY,RTNCODE)
         CALL CLRMSG(5)
         CALL CLRMSG(4)
         IF (REPLY.EQ.'Y')THEN
C             .. OVERWRITE OLD MENU -- ASK USER TO RECONSIDER OVERWRITE
            CALL WRTMSG(5,414,14,0,0,' ',0)
            CALL WRTMSG(4,415,14,0,0,' ',0)
            CALL LOCATE(21,20,IERR)
            CALL OKREPLY(REPLY,RTNCODE)
            CALL CLRMSG(5)
            CALL CLRMSG(4)
            IF (REPLY.EQ.'Y')THEN
C                .. OVERWRITE OLD MENU 
               WRTMENU = .TRUE.
               NEWMENU = .FALSE.
            ELSE   
C                .. DO NOT OVERWRITE OLD MENU  -- GET ANOTHER OPTION
               WRTMENU = .FALSE.
               NEWMENU = .FALSE.
            ENDIF
         ELSE   
C             .. DO NOT OVERWRITE OLD MENU -- ASK USER TO SAVE UNDER NEW NAME
            CALL CHGNAM(MENUNAME,418,IOPT,RTNFLAG)
            IF (RTNFLAG.EQ.'4F') THEN
C                .. F4/ESC -- GET ANOTHER OPTION
               WRTMENU = .FALSE.
               NEWMENU = .FALSE.
            ELSE IF (IOPT.EQ.1) THEN
C                .. SAVE MENU UNDER NEW NAME                  
               WRTMENU = .TRUE.
               NEWMENU = .TRUE.
            ELSE
C                .. DO NOT SAVE MENU -- GET ANOTHER OPTION
               WRTMENU = .FALSE.
               NEWMENU = .FALSE.
            END IF
         END IF
      END IF
C
      IF (WRTMENU) THEN
         IF (NEWMENU) THEN
C             .. WRITE NEW MENU -- FIND NEXT EMPTY RECORD         
            NMSG = 422
            DO 164 I = 1,999
               IREC = I
               READ(14,REC=I,ERR=166) DELMARK
               IF (DELMARK.EQ.'*') THEN
                  GO TO 166
               END IF  
  164       CONTINUE
  166       CONTINUE
            MNUREC = IREC
         ELSE
C             .. REPLACE CURRENT MENU WITH NEW MENU         
            NMSG = 417
         ENDIF
         DELMARK = ' '
         WRITE(14,REC=MNUREC) DELMARK,MENUNAME,TITLE,BORDER
     +       ,(CHOICE(J),J=1,MAXCHOICE),WIDTH,NUMCHOICE
     +       ,HDRFGC,HDRBGC,FGCOLOR,BGCOLOR,TLENGTH,CLENGTH
         CALL WRTMSG(5,NMSG,14,0,1,' ',0)
      ENDIF      
      GO TO 20
C
C    OPTION 5 -  COPY A CLICOM MENU TO ANOTHER FILE
C
      ELSE IF (IOPT.EQ.5)THEN
  175    CALL LOCATE(16,30,IERR)
         CALL WRTMSG(5,423,14,0,0,' ',0)
         CALL LOCATE(21,5,IERR)
         CALL GETSTR(0,MENFIL,42,15,1,RTNFLAG)
         CALL CLRMSG(5)
         CALL CLRMSG(4)
         IF (RTNFLAG .EQ. '4F' .OR. MENFIL .EQ. ' ') THEN
            GO TO 20
         ENDIF
         OPEN (66,FILE=MENFIL,STATUS='OLD',ACCESS='DIRECT'
     +       ,RECL=602,IOSTAT=IOCHK)
         IF(IOCHK.NE.0) THEN
            CALL WRTMSG(5,424,12,0,0,' ',0)
            CALL LOCATE(21,5,IERR)
            CALL OKREPLY(REPLY,RTNCODE)
            CALL CLRMSG(5)
            CALL CLRMSG(4)
            IF (REPLY.EQ.'Y')THEN
               GO TO 176
            ELSE
               GO TO 20
            END IF
  176       OPEN (66,FILE=MENFIL,STATUS='NEW',ACCESS='DIRECT'
     +          ,RECL=602,IOSTAT=IOCHK)
            IF(IOCHK.NE.0) THEN
               CALL OPENMSG(MENFIL,'DEFMENU     ',IOCHK)
               GO TO 175
            END IF
         END IF
C
C  ASK FOR NEW MENU NAME OR SELECT FROM LIST OF EXISTING MENUS
C
         RTNFLAG = '  '
         CALL LOCATE(0,0,IERR)
         CALL VALWIN(14,HLDREC,64,4,ICNTRL)
         MENUNAME = HLDREC(1:12)
C
      IF (MENUNAME.EQ.BLANK.OR.RTNFLAG.EQ.'4F') THEN
         GO TO 20
      END IF
C
C   READ THE MENU DEFINITION FROM THE SOURCE FILE
C
      NEWMENU = .FALSE.
      DO 177 IREC = 1,999
         READ(14,REC=IREC,ERR=177) DELMARK,INNAME,TITLE,BORDER
     +       ,(CHOICE(J),J=1,MAXCHOICE),WIDTH,NUMCHOICE
     +       ,HDRFGC,HDRBGC,FGCOLOR,BGCOLOR,TLENGTH,CLENGTH
         IF (INNAME.EQ.MENUNAME .AND. DELMARK.EQ.BLANK) THEN 
            NEWMENU = .TRUE.
            GO TO 178
         END IF
  177 CONTINUE
      CALL WRTMSG(5,232,12,1,1,' ',0)
      CLOSE (66)
      GO TO 20
  178 CONTINUE
C
C   DETERMINE IF THE MENU ALREADY EXISTS IN DESTINATION MENU FILE.
C
      DO 180 IREC = 1,999
         READ(66,REC=IREC,ERR=182) DELMK,INNME,TTLE,BRDR
     +       ,(CHCE(J),J=1,MAXCHOICE),WDTH,NMCHCE
     +       ,HFGC,HBGC,FGCOL,BGCOL,TLNTH,CLNTH
         IF (DELMK.EQ.'*')THEN
            GO TO 180
         END IF
         IF (INNME.EQ.MENUNAME) THEN 
            CALL WRTMSG(5,421,14,1,0,' ',0)
            CALL LOCATE (21,5,IERR)
            CALL OKREPLY(REPLY,RTNCODE)
            CALL CLRMSG(5)
            CALL CLRMSG(4)
            IF (REPLY.EQ.'Y')THEN
               DELMARK = ' '
               WRITE(66,REC=IREC) DELMARK,INNAME,TITLE,BORDER
     +            ,(CHOICE(J),J=1,MAXCHOICE),WIDTH,NUMCHOICE
     +            ,HDRFGC,HDRBGC,FGCOLOR,BGCOLOR,TLENGTH,CLENGTH
            END IF
            CLOSE (66)
            GO TO 20
         END IF
  180 CONTINUE
  182 CONTINUE
C
         DO 184 I = 1,999
            IREC = I
            READ(66,REC=I,ERR=186) DELMARK
            IF (DELMARK.EQ.'*') THEN
               GO TO 186
            END IF  
  184    CONTINUE
C
  186    CONTINUE
      DELMARK = ' '
      WRITE(66,REC=IREC) DELMARK,INNAME,TITLE,BORDER
     +   ,(CHOICE(J),J=1,MAXCHOICE),WIDTH,NUMCHOICE
     +   ,HDRFGC,HDRBGC,FGCOLOR,BGCOLOR,TLENGTH,CLENGTH
C
         CALL WRTMSG(5,422,14,0,1,' ',0)
         CLOSE (66)
         GO TO 20
C
C     OPTION 6 - DISPLAY THE MENU AS IT WILL APPEAR TO THE USER
C 
      ELSE IF (IOPT.EQ.6) THEN
         CALL DSPMNU(WIDTH,BORDER,TITLE,HDRFGC,HDRBGC
     +        ,FGCOLOR,BGCOLOR,CHOICE,NUMCHOICE,TLENGTH,CLENGTH)
         GO TO 20
C
C **DEBUG
      ELSE IF (IOPT.EQ.7) THEN
         GO TO 20
      END IF
C
C    DEFINE NEW OR MODIFY OLD MENU - SET THE MENU FORM DEFINITION VARIABLES 
C
      FIELD(1) = MENUNAME
      WRITE(FIELD(2),'(I2)') WIDTH
      FIELD(3) = BORDER
      FIELD(4) = TITLE
      WRITE(FIELD(5),'(I2)') HDRFGC
      WRITE(FIELD(6),'(I1)') HDRBGC
      WRITE(FIELD(7),'(I2)') FGCOLOR
      WRITE(FIELD(8),'(I1)') BGCOLOR
      DO 190 I1 = 1,MAXCHOICE
         FIELD(I1+8) = CHOICE(I1)
  190 CONTINUE
C
C   DISPLAY AND RETRIEVE THE MENU DEFINITION FORM
C   
  200 CONTINUE
      CALL CLS
      CALL LOCATE(0,0,IERR)
      RTNFLAG = '  '
      CALL GETFRM(FORMNAME,FILNAME,FIELD,60,RTNFLAG)
      IF (RTNFLAG.EQ.'4F') THEN
         CALL LOCATE(23,32,IERR)
         CALL WRTMSG(2,236,14,1,0,' ',0)
         CALL OKREPLY(REPLY,RTNCODE)
         IF (REPLY.EQ.'Y'.AND.RTNCODE.EQ.'0') THEN
            GO TO 20
         ELSE
            GO TO 200
         END IF
      END IF
C
C   SET THE MENU DEFINITION TO THE VALUES RETURNED, DETERMINE 
C       COMPUTED VARIABLES,  AND WRITE THE MENU DEFINTION TO DISK
C
      MENUNAME = FIELD(1)
      READ(FIELD(2),'(BN,I2)') WIDTH
      BORDER = FIELD(3)
      TITLE  = FIELD(4)
      READ(FIELD(5),'(BN,I2)') HDRFGC
      READ(FIELD(6),'(I1)') HDRBGC
      READ(FIELD(7),'(BN,I2)') FGCOLOR
      READ(FIELD(8),'(I1)') BGCOLOR
      NUMCHOICE = 0
      DO 250 I1 = 1,MAXCHOICE
         CHOICE(I1) = '   '
  250 CONTINUE         
      DO 300 I1 = 1,MAXCHOICE
         IF (FIELD(I1+8).NE.BLANK) THEN
             NUMCHOICE = NUMCHOICE + 1
             CHOICE(NUMCHOICE) = FIELD(I1+8)
         END IF
  300 CONTINUE
      DO 320 I1 = 60,1,-1
         IF (TITLE(I1:I1).NE.' ') THEN
            TLENGTH = I1
            GO TO 330
         END IF
  320 CONTINUE
  330 CONTINUE
      CLENGTH = 0
      DO 350 I1 = 1,MAXCHOICE
         DO 340 I2 = 1,32
            IF (CHOICE(I1)(I2:I2).NE.' ') THEN
               IF (I2.GT.CLENGTH) THEN
                   CLENGTH = I2
               END IF
            END IF
  340    CONTINUE
  350 CONTINUE
      IF (TLENGTH.GT.WIDTH.OR.CLENGTH+5.GT.WIDTH) THEN
         CALL WRTMSG(2,237,12,1,1,' ',0)
         GO TO 200
      END IF 
C
C   MENU DEFINITION HAS BEEN ACCEPTED - WRITE IT TO THE MENU FILE
C
      IF (IOPT.EQ.2) THEN
         CALL CHGNAM(MENUNAME,238,IOPT,RTNFLAG)
         IF (RTNFLAG.EQ.'4F') THEN
            GO TO 200
         END IF
      END IF
      IF (IOPT.EQ.1) THEN
         DO 400 I = 1,999
            IREC = I
            READ(14,REC=I,ERR=420) DELMARK
            IF (DELMARK.EQ.'*') THEN
               GO TO 420
            END IF  
  400    CONTINUE
  420    CONTINUE
      END IF
      DELMARK = ' '
      WRITE(14,REC=IREC) DELMARK,MENUNAME,TITLE,BORDER
     +   ,(CHOICE(J),J=1,MAXCHOICE),WIDTH,NUMCHOICE
     +   ,HDRFGC,HDRBGC,FGCOLOR,BGCOLOR,TLENGTH,CLENGTH
      GO TO 20
      END

$PAGE

      SUBROUTINE DSPMNU(WIDTH,BORDER,TITLE,HDRFGC,HDRBGC
     +           ,FGCOLOR,BGCOLOR,CHOICE,NUMCHOICE,TLENGTH,CLENGTH)
C
C   ROUTINE TO DISPLAY A MENU AS IT WILL APPEAR WHEN GETMNU IS CALLED
C
      PARAMETER(MAXCHOICE=16)
C
C   LOCAL VARIABLES 
C 
      INTEGER*2 STRTROW,STRTCOL,ENDROW,ENDCOL,IROW,ICOL
     +         ,WIDTH,NUMCHOICE,FGCOLOR,BGCOLOR,HDRFGC,HDRBGC
     +         ,TLENGTH,CLENGTH,PMTLEN
      CHARACTER*60 TITLE
      CHARACTER*32 CHOICE(MAXCHOICE)
      CHARACTER*12 PROMPT
      CHARACTER*1 INCHAR(2),BORDER
      CHARACTER*2 ICHAR,CREPLY
      CHARACTER*4 WRTTXT
      DATA PROMPT /' (  ды)'/, PMTLEN /10/
C
C   WRITE THE FUNCTION KEY LINE
C
      CALL CLS
      CALL WRTFNC(0)
C
C   DETERMINE THE SIZE OF THE FORM AND CENTER IT
C
      IF (BORDER.EQ.'Y') THEN
         MENUSIZE = NUMCHOICE + 5
      ELSE
         MENUSIZE = NUMCHOICE + 3
      END IF
      IROW = (23 - MENUSIZE)/2
      ICOL = (80 - WIDTH)/2
      STRTROW = IROW 
      STRTCOL = ICOL
      ENDROW = STRTROW + MENUSIZE - 1
C
C   WRITE THE MENU
C
C     DRAW THE MENU BORDER 
C
      CALL DRWBOX(STRTCOL,STRTROW-1,STRTCOL+WIDTH-1,ENDROW,2,11,0)
C
C     DRAW THE MENU TITLE
C
      IF (TLENGTH.GT.0) THEN
         ICOL1 = (WIDTH/2) - (TLENGTH/2) + STRTCOL
         CALL LOCATE (STRTROW,ICOL1,IERR)
         CALL WRTSTR(TITLE,TLENGTH,HDRFGC,HDRBGC) 
      END IF
C
C     DRAW THE MENU CHOICES
C
      IROW = STRTROW + 2
      ICOL2 = (WIDTH/2) - ((CLENGTH+4)/2) + STRTCOL
      CALL LOCATE (IROW,ICOL2,IERR)
      CALL WRTSTR(' 0  Exit',8,FGCOLOR,BGCOLOR)
      DO 100 ICHOICE = 1,NUMCHOICE 
         IROW = STRTROW + ICHOICE + 2
         CALL LOCATE(IROW,ICOL2,IERR)
         WRITE (ICHAR,'(I2)') ICHOICE
         CALL WRTSTR(ICHAR,2,FGCOLOR,BGCOLOR)
         CALL WRTSTR('  ',2,FGCOLOR,BGCOLOR)
         CALL WRTSTR(CHOICE(ICHOICE),CLENGTH,FGCOLOR,BGCOLOR)
  100 CONTINUE
  200 CONTINUE
C
C   DRAW THE REPLY LINE WITHIN THE BORDER
C
      ICOL3 = (WIDTH/2) - ((PMTLEN+10)/2) + STRTCOL 
      CALL LOCATE (ENDROW,ICOL3,IERR)
      CALL WRTSTR(PROMPT,PMTLEN,15,0)
      CALL WRTSTR(' (0 - ',6,15,0)
      IF (NUMCHOICE.GT.9) THEN
         WRITE(WRTTXT,'(I2,A1,1X)') NUMCHOICE,')'
         CALL WRTSTR(WRTTXT,4,15,0)
      ELSE
         WRITE(WRTTXT,'(I1,A1,2X)') NUMCHOICE,')'
         CALL WRTSTR(WRTTXT,3,15,0)
      END IF
C
C   READ THE REPLY
C
  400 CONTINUE
      CREPLY = '  '
      CALL LOCATE(ENDROW,ENDCOL,IERR)
      IPOS = 1
  410 CONTINUE
      CALL LOCATE(ENDROW,ENDCOL+IPOS-1,IERR)
      CALL GETCHAR(0,INCHAR)
      RETURN
  900 CONTINUE
      CALL WRTMSG(4,98,12,1,1,' ',0)
      RETURN
      END
$PAGE
       SUBROUTINE CHGNAM(MENUNAME,NBRMSG,IOPT,RTNFLAG)
C
C   ROUTINE TO ASK IF A MODIFIED MENU SHOULD BE WRITTEN UNDER A NEW
C       NAME 
C
      CHARACTER*12 MENUNAME,NEWNAME,INNAME,BLANK
      CHARACTER*2 INCHAR,RTNFLAG,YESUP,YESLO,NOUP,NOLO
      CHARACTER*1 DELMARK
      INTEGER*2 IOPT
      LOGICAL FIRSTCALL
      DATA FIRSTCALL /.TRUE./
      DATA BLANK /'            '/
C
      IF (FIRSTCALL) THEN
         FIRSTCALL = .FALSE.
         CALL GETYN(1,2,YESUP,YESLO)
         CALL GETYN(2,2,NOUP,NOLO)
      ENDIF     
C
  40  CONTINUE
      CALL LOCATE(21,45,IERR)
      CALL WRTMSG(4,NBRMSG,14,0,0,' ',0)
      CALL GETCHAR(0,INCHAR)
      CALL CLRMSG(2)
      IF (INCHAR.EQ.YESUP .OR. INCHAR.EQ.YESLO) THEN
         CALL LOCATE(22,0,IERR)
         NEWNAME = BLANK
         CALL WRTSTR('New Name: ',10,14,0)
         CALL GETSTR(0,NEWNAME,12,15,1,RTNFLAG)
         CALL CLRMSG(4)
         CALL CLRMSG(3)
         IF (NEWNAME.EQ.BLANK.OR.RTNFLAG.EQ.'4F') THEN
            GO TO 40
         END IF
      ELSE IF (INCHAR.EQ.NOUP .OR. INCHAR.EQ.NOLO) THEN
         RTNFLAG = ' '
         RETURN
      ELSE IF (INCHAR.EQ.'4F') THEN
         RTNFLAG = '4F'
         RETURN
      ELSE
         CALL BEEP
         GO TO 40
      END IF
C
C   MAKE SURE THE NEW MENU NAME DOES NOT ALREADY EXIST
C
      DO 100 IREC = 1,999
         READ(14,REC=IREC,ERR=120) DELMARK,INNAME
         IF (INNAME.EQ.NEWNAME.AND.DELMARK.EQ.BLANK) THEN
            CALL WRTMSG(2,239,12,1,0,' ',0)
            GO TO 40
         END IF
  100 CONTINUE 
  120 CONTINUE
C         
      MENUNAME = NEWNAME
      RTNFLAG = ' '
      IOPT = 1
      RETURN
      END
