$STORAGE:2  
      SUBROUTINE BEEP
C
C       ** ROUTINE TO SOUND A BELL
C          NOTE:  TONE2 SHOULD BE IN UTILITY.LIB -- THE OBJECT CODE IS STORED
C                 IN \CLICOM\SRC\OBJ\TONE.OBJ -- THERE IS NO SOURCE CODE
C
      CALL TONE2 (1000,840,4)
      RETURN
      END

