$STORAGE:2
C
      SUBROUTINE CALCDP(TT,RH,DP)
C
C  CALCULATE DEW POINT - DRY BULB TEMP AND RELATIVE HUMIDITY ARE
C  REQUIRED.
C  TEMPS = DEG C.
C  RH = WHOLE PERCENT
C  EE = VAPOR PRESSURE
C  ES = SATURATION VAPOR PRESSURE
C
C  CALCULATE DEW POINT USING DRY BULB AND REL HUM
C
C  FIRST - CALCULATE SATURATION VAPOR PRESSURE
C          HANDBOOK OF METEOROLOGY PAGE 343, EQUATION 63.
C
      RHUN = RH * .01
      TOP = TT * 7.5
      BOTTOM = TT + 237.3
      POWER = TOP / BOTTOM
      HOLD = 10**POWER
      ES =  6.11 * HOLD
C
C  NOW - CALCULATE VAPOR PRESSURE      
C        HANDBOOK OF METEOROLOGY PAGE 353, EQUATION 119.
C
      EE = RHUN * ES
C
C  FINALLY - CALCULATE DEW POINT.  ALGORITHM IS DERIVED FROM       
C        HANDBOOK OF METEOROLOGY PAGE 343, EQUATION 63.
C
      HOLD = ALOG10(EE)
      TOP = HOLD * 237.3 - 186.527
      BOTTOM = 8.286 - HOLD
      DP = (TOP / BOTTOM)
C
      RETURN
      END
C
