$STORAGE:2
C
      SUBROUTINE CALCVP(TT,RH,VP)
C
C  CALCULATE VAPOR PRESSURE (REQUIRED FOR CALCULATING MIXING
C  RATIO) - DRY BULB TEMP AND RELATIVE HUMIDITY ARE REQUIRED.
C  TEMPS = DEG C.
C  RH = WHOLE PERCENT
C
C  FOLLOWING FORMULA IS FROM 'HANDBOOK OF METEOROLOGY' PAGE 343
C  TETENS FORMULA FOR VAPOR PRESSURE (VP).
C
      RRH = RH * .01
      VP = RRH * (6.11 * (10.0**(7.5 * TT/
     +          (237.3 + TT))))
C
      RETURN
      END
C
