$STORAGE:2
C
      SUBROUTINE CALCMR(VP,SP,MR)
C
C  CALCULATE MIXING RATIO - VAPOR PRESSURE AND STATION PRESSURE
C  ARE REQUIRED.
C
      REAL*4 MR
C
C  FORMULA FROM 'HANDBOOK OF METEOROLOGY' PAGE 354
C
      MR = ((622 * VP) / (SP - VP))
      RETURN
      END
C
