      SUBROUTINE CMDLIN(COMMND,CMDLEN,RESULT)
C
C   ROUTINE TO TAKE THE CONTENTS OF DOS COMMAND LINE PARAMETERS - 
C     BEGINNING AT ADDRESS COMMND AND PASS THEM BACK AS RESULT
C
      CHARACTER*64 COMMND,RESULT
      CHARACTER*1  CMDLEN,CHAR
C
      ILEN = ICHAR(CMDLEN)
      IF (ILEN.EQ.0) THEN
         CALL WRTMSG(4,113,12,1,0,' ',0)
         RESULT = ' '
      END IF
      DO 50 I = 1,ILEN
         CHAR = COMMND(I:I)
         IF (CHAR.NE.' '.AND.CHAR.NE.',') THEN
            GO TO 60
         END IF
         ISTRT = I
   50 CONTINUE
   60 CONTINUE
      RESULT = '  '
      RESULT(1:ILEN) = COMMND(ISTRT+1:ILEN)
      RETURN
      END

