$STORAGE:2
 
      SUBROUTINE DATASRC (STRTCOL,DATASOURCE,RTNCODE)
C
C   SUBROUTINE TO ASK THE USER WHETHER TO READ INFORMATION FROM THE    
C       MAIN DATA FILE OR A SUBSET.
C       THE ROUTINE ASKS THE USER FOR THE INFORMATION AND READS IT FROM
C       THE TERMINAL. 
C
C     PASSED VARIABLES
C         INPUT:
C            STRTCOL.....STARTING COLUMN FOR THE MENU
C         OUTPUT:
C            DATASOURCE..CODED DATA SOURCE (M = MAIN, S = SUBSET)
C            RTNCODE.....STATUS CODE (0 = OK, 1 = EXIT SELECTED)
C
      INTEGER*2 STRTCOL
      CHARACTER*1 DATASOURCE,RTNCODE
      CHARACTER*64 FILNAME
      DATA FILNAME /'P:\HELP\DATASRC.HLP'/

      RTNCODE = '0'

      CALL POSLIN(IROW,ICOL)
      CALL LOCATE(IROW,STRTCOL,IERR)
      CALL GETMNU('SELDATASRC  ',FILNAME,ICHOICE)
      IF (ICHOICE.EQ.0)  THEN
         RTNCODE = '1'
         RETURN
      ELSE IF (ICHOICE.EQ.1) THEN
         DATASOURCE = 'M'
      ELSE
         DATASOURCE = 'S'
      END IF
C
      RETURN
      END      
