$STORAGE:2
C
      SUBROUTINE DEC2HEX(HEXSTR,LNGTH,DECNUM,RTNCODE)
C
C  THIS SUBROUTINE CONVERTS A DECIMAL NUMBER TO A
C  HEXIDECIMAL CHARACTER STRING.
C
C  PASSED VARIABLES:
C     HEXSTR  = A HEXIDECIMAL CHARACTER STRING RETURNED
C     DECNUM  = THE DECIMAL NUMBER PASSED IN
C     LNGTH   = THE LENGTH OF THE HEXIDECIMAL STRING
C     RTNCODE = RETURN CODE
C                  0 = SUCCESSFUL CONVERSION
C                  1 = ERROR IN CONVERSION
C
       CHARACTER*1 HEXSTR(LNGTH), HLDHEX(16)
C
       INTEGER DECNUM, LNGTH, RTNCODE, HLDNUM
       INTEGER HLDPTR
C
      REAL HLDREM
C
      DATA HLDHEX /'0','1','2','3','4','5','6','7','8','9',
     +             'A','B','C','D','E','F'/
C
      RTNCODE = 0
C
      HLDNUM = DECNUM
C
C  BEGIN DECODE
C
      DO 100 I = LNGTH,1,-1
      HLDREM = MOD(HLDNUM,16)
      HLDPTR = HLDREM + 1
      HEXSTR(I) = HLDHEX(HLDPTR)
      HLDNUM = HLDNUM / 16
  100 CONTINUE
C
      RETURN
      END
