$STORAGE:2
      SUBROUTINE GETELEM(ELEMCODE,ITYPE)
C
C   ROUTINE TO DISPLAY THE ELEM.DEF FILE AND ALLOW THE USER TO 
C      SELECT THE ELEMENT-CODE WANTED
C
C      ELEMENT-CODE = SPACES ON RETURN IF NONE SELECTED
C
C   -------------------------------------------------------------------
C   WARNING - THIS ROUTINE HAS BEEN INCLUDED IN THE ADMIN PROGRAM SOURCE
C             CODE TO GET AROUND A COMPILER OR LINKER ERROR.  IF YOU
C             MAKE ANY CHANGES TO THIS ROUTINE YOU MUST REPEAT THE CHANGES
C             IN THE COPY INSIDE ADMIN.
C   -------------------------------------------------------------------
C
      CHARACTER*3 ELEMCODE
      CHARACTER*80 ELEMREC
C
C   OPEN THE ELEM.DEF FORTRAN FILE
C
20    CONTINUE
      OPEN(30,FILE='P:\DATA\ELEM.DEF',STATUS='OLD',ACCESS='DIRECT'
     +      ,RECL=110,SHARE='DENYWR',MODE='READ',IOSTAT=IOCHK)
      IF (IOCHK.NE.0) THEN
         CALL OPENMSG('P:\DATA\ELEM.DEF      ','GETELEM     ',IOCHK)
         GO TO 20
      END IF
C
C   CALL THE VALUE-WINDOW ROUTINE TO ALLOW USER TO SELECT ELEMENT-CODE
C      
      CALL VALWIN(30,ELEMREC,80,2,ITYPE)
      ELEMCODE = ELEMREC(1:3)
C
      CLOSE(30)
      RETURN
      END
