$STORAGE:2

      SUBROUTINE GETLIMIT(STARTSTN,ENDSTN,STRTYRMO,ENDYRMO,FILNAME
     +          ,RTNCODE)
C
C   SUBROUTINE TO SOLICIT A RANGE OF STATIONS AND YEARS TO BE PROCESSED
C       THE ROUTINE ASKS THE USER TO SUPPLY THE INFORMATION AND READS IT
C       FROM THE KEYBOARD BY CALLING ROUTINE GETFRM. 
C
      CHARACTER*8 STARTSTN,ENDSTN
      INTEGER*4 STRTYRMO, ENDYRMO
      CHARACTER*1 RTNCODE
      CHARACTER*2 RTNFLAG
      CHARACTER*64 FILNAME
      CHARACTER*20 FIELD(6)
      FIELD(1) = '        '
      FIELD(2) = '        '
      FIELD(3) = '    '
      FIELD(4) = '  ' 
      FIELD(5) = '    '
      FIELD(6) = '  '
      RTNCODE = '0'
      CALL POSLIN(IROW,ICOL)
C
C   BUILD AND READ THE DATA ENTRY FORM 
C
   40 CONTINUE
      CALL LOCATE(IROW,ICOL,IERR)
      RTNFLAG = 'SS'
      CALL GETFRM('GETLIM  ',FILNAME,FIELD,20,RTNFLAG)
      IF (RTNFLAG.EQ.'4F') THEN
         RTNCODE = '1'
         RETURN
      END IF
C
C   CHECK THE INPUT DATA 
C
      STARTSTN = FIELD(1)
      ENDSTN = FIELD(2)
      READ(FIELD(3),'(I4)') IYEAR
      READ(FIELD(4),'(I2)') IMON
      RYEAR = IYEAR
      RMON = IMON
      RYRMON = RYEAR*100. + RMON
      STRTYRMO = INT4(RYRMON)
      READ(FIELD(5),'(I4)') IYEAR
      READ(FIELD(6),'(I2)') IMON
      RYEAR = IYEAR
      RMON = IMON
      RYRMON = RYEAR*100. + RMON
      ENDYRMO = INT4(RYRMON)
      IF (ENDYRMO.LT.STRTYRMO) THEN
         CALL WRTMSG(3,71,12,1,0,' ',0)
         GO TO 40
      END IF
C
      IROW = IROW + 9 
      CALL LOCATE(IROW,1,IERR) 
C
      RETURN
      END
