$STORAGE:2
C
      SUBROUTINE GETMSG(MSGNUM,MESSAG)
C
C   THIS ROUTINE READS MESSAGE NUMBER MSGNUM FROM THE MESSAGE FILE AND
C     RETURNS THE CONTENTS AS MESSAG
C
C     IT OPENS THE MESSAGE FILE ON THE FIRST CALL AND CLOSES THEN 
C     MESSAGE FILE IF THE MSGNUM REQUESTED = 999
C
      INTEGER*2 MSGNUM
      CHARACTER*78 MESSAG
      CHARACTER*2 INCHAR
      LOGICAL FILEOPEN
      DATA FILEOPEN /.FALSE./
C
      RTNFLAG = '0'    
C
C   IF MSGNUM = 999 CLOSE THE MESSAGE FILE AND RETURN
C
      IF (MSGNUM.EQ.999) THEN
         CLOSE(18)
         FILEOPEN = .FALSE.
         RETURN
      END IF
C
C   IF THE MESSAGE FILE IS NOT OPEN, OPEN IT
C
      IF (.NOT.FILEOPEN) THEN
         OPEN (18,FILE='P:\DATA\MESSAGES.FTN',STATUS='OLD',
     +         ACCESS='DIRECT',RECL=78,SHARE='DENYWR',MODE='READ',
     +         ERR=990,IOSTAT=ISTAT)
         FILEOPEN = .TRUE.
      END IF
C      
      READ(18,REC=MSGNUM,ERR=900,IOSTAT=ISTAT) MESSAG
      RETURN
C
C   GET HERE IF THERE IS A SYSTEM ERROR - MESSAGES NOT FOUND
C
  900 CONTINUE
      MESSAG = 'Message file /DATA/MESSAGES.FTN is in error  '
      GO TO 995
C      
  990 CONTINUE
      MESSAG = 'Error in opening file /DATA/MESSAGES.FTN     '
      GO TO 995
C      
  995 CONTINUE
      CALL LOCATE(23,0,IERR)
      CALL WRTSTR(MESSAG,45,12,0)    
      WRITE(MESSAG,996) MSGNUM,ISTAT
  996 FORMAT('Message number=',I5,'  Error status=',I5)
      CALL LOCATE(24,0,IERR)
      CALL WRTSTR(MESSAG,40,12,0)    
      CALL BEEP
      CALL WRTSTR(' - Press any key to continue',28,15,0)
      CALL GETCHAR(0,INCHAR)
      MESSAG=' '
      RETURN
C      
      END
