$STORAGE:2
      SUBROUTINE GETMAP(MAPNAME)
C
C   ROUTINE TO DISPLAY THE MAPNAMES INDEX FILE AND ALLOW THE USER TO 
C      SELECT THE MAP WANTED
C
C      MAPNAME = SPACES ON RETURN IF NO STATION SELECTED
C
      CHARACTER*8 MAPNAME
      CHARACTER*41 DESCREC
C
         OPEN (51,FILE='O:\DATA\MAPNAMES.IDX',STATUS='OLD'
     +       ,FORM='BINARY',ACCESS='DIRECT',RECL=43,IOSTAT=IOCHK)
         IF (IOCHK.NE.0) THEN
            CALL OPENMSG('O:\DATA\MAPNAMES.IDX    ','GETMAP    ',IOCHK)
            STOP 2
         END IF
         DESCREC = ' '
         CALL VALWIN(51,DESCREC,41,3,IFLAG)
         CLOSE(51)
         MAPNAME = DESCREC(1:8)
      RETURN
      END

