$STORAGE:2
      SUBROUTINE GETSTN(STNID)
C
C   ROUTINE TO DISPLAY THE STNGEOG.INF FILE AND ALLOW THE USER TO 
C      SELECT THE STATION WANTED
C
C      STNID = SPACES ON RETURN IF NO STATION SELECTED
C
      CHARACTER*8  STNID
      CHARACTER*40 STNREC
C
C   OPEN THE STN-GEOG FORTRAN FILE
C
20    CONTINUE
      OPEN (35,FILE='P:\DATA\STNGEOG.INF',STATUS='OLD',
     +      ACCESS='DIRECT',RECL=80,SHARE='DENYWR',MODE='READ'
     +      ,IOSTAT=IOCHK)
      IF (IOCHK.NE.0) THEN
         CALL OPENMSG('P:\DATA\STNGEOG.INF   ','GETSTN      ',IOCHK)
         GO TO 20
      END IF
C
C   CALL THE VALUE-WINDOW ROUTINE TO ALLOW USER TO SELECT STATION-ID
C      
      CALL VALWIN(35,STNREC,40,1,ITYPE)
      STNID = STNREC(1:8)
C
      CLOSE(35)
      RETURN
      END

