$STORAGE:2
C
      SUBROUTINE GETTLS(TLTEXT,ILEN,TLLEN,IDIM)
C
C       ** OBJECTIVE:  THIS ROUTINE READS TEXT FROM THE MESSAGES FILE AND
C                      PARSES IT INTO SEPARATE VALUES FOR 7 COMMON TITLES
C                      SUCH AS "STATION-NAME", "MONTH", "DISTRICT", ETC 
C
C       ** INPUT:
C             ILEN.....THE LENGTH OF THE CHARACTER STRING TLTEXT
C             IDIM.....THE NUMBER OF TITLES TO LOOK FOR 
C       ** OUTPUT
C             TLTEXT...THE TEXT OF THE TITLES FOUND
C             TLLEN....THE LENGTH OF EACH OF THE TITLES FOUND
C
      PARAMETER (MXTTL=7)
      CHARACTER*(*) TLTEXT(IDIM)
      CHARACTER*78 MSGLIN
      CHARACTER*1  RTNCODE
      INTEGER*2 TLLEN(IDIM)
C
C       ** INITIALZE
C
      NTTL = MIN0(IDIM,MXTTL)
      DO 20 I = 1,NTTL
         TLTEXT(I)(1:ILEN) = ' '
         TLLEN(I) = 0
   20 CONTINUE
C
C       ** READ THE TITLES FROM THE MESSAGE FILE
C
      CALL GETMSG(307,MSGLIN)
      CALL GETMSG(999,MSGLIN)
C
C   PARSE THE MESSAGE LINES READ INTO THE TITLES - THEY SHOULD
C   BE SEPARATED BY COMMAS (,).
C
      CALL PARSE1(MSGLIN,78,NTTL,ILEN,TLTEXT,RTNCODE)
      IF (RTNCODE.NE.'0')GO TO 900
      DO 40 I=1,NTTL
         TLLEN(I) = LNG(TLTEXT(I))
   40 CONTINUE            
C            
      RETURN
C
C       ** ERROR PROCESSING
C
  900 CONTINUE
      CALL WRTMSG(3,268,12,1,1,' 307 '//RTNCODE,6)
      CALL CLRMSG(3)      
      CALL CLRMSG(2)      
      STOP 2
C      
      END
      