$STORAGE:2
      SUBROUTINE GETYN(YNFLG,NCHLTR,LTRUP,LTRLO)
C
C       ** OBJECTIVE:  GET VALUES FOR YES/NO RESPONSES FROM THE
C                      FILE MESSAGES.FTN
C       ** INPUT:      
C             YNFLG....FLAG TO INDICATE DESIRED RESPONSE
C                      1=YES  2=NO
C             NCHLTR...NUMBER OF CHARACTERS IN OUTPUT VARIABLES
C       ** OUTPUT:
C             LTRUP....FIRST LETTER OF RESPONSE -- UPPERCASE
C             LTRLO....FIRST LETTER OF RESPONSE -- LOWERCASE
C
      INTEGER*2 YNFLG,NCHLTR
      CHARACTER*(*) LTRUP,LTRLO
C
      CHARACTER*1  LETTER(2,2),RTNCODE
      CHARACTER*80 MSGLIN
      LOGICAL FIRSTCALL
      DATA FIRSTCALL/.TRUE./
C
      IF (FIRSTCALL) THEN
         FIRSTCALL=.FALSE.
         CALL GETMSG(500,MSGLIN)
         CALL PARSE1(MSGLIN,80,2,1,LETTER(1,1),RTNCODE)
         CALL GETMSG(501,MSGLIN)
         CALL PARSE1(MSGLIN,80,2,1,LETTER(1,2),RTNCODE)
         CALL GETMSG(999,MSGLIN)
      ENDIF
C
      LTRUP(1:NCHLTR)=' '
      LTRLO(1:NCHLTR)=' '
      LTRUP(1:1)=LETTER(1,YNFLG)
      LTRLO(1:1)=LETTER(2,YNFLG)
C
      RETURN      
      END                        
      