$STORAGE:2


      SUBROUTINE INSCHR(FLDTYPE,INVAL,FLDLEN,FIELDPOS,VALPOS,INCHAR
     +                  ,ICOL)
C
C   THIS ROUTINE INSERTS CHARACTER INCHAR AT POSITION FIELDPOS
C
       CHARACTER*1 INVAL(6),INCHAR
       INTEGER*2 FLDTYPE,FLDLEN,FIELDPOS,VALPOS
C
C     FLDTYPE ... IF INVAL = 2 IT'S TREATED AS A NUMBER , ELSE ALPHA 

      IF (FLDTYPE.NE.2.AND.FIELDPOS.LT.FLDLEN) THEN
         DO 150 I = FLDLEN-1,FIELDPOS,-1
            INVAL(I+1) = INVAL(I)
  150    CONTINUE
      ELSE IF (FIELDPOS.GT.1) THEN
         DO 160 I = 2,FIELDPOS
            INVAL(I-1) = INVAL(I)
            VALPOS = VALPOS + 1
  160    CONTINUE
      END IF
      INVAL(FIELDPOS) = INCHAR
      IF (FLDTYPE.NE.2.AND.FIELDPOS.LT.FLDLEN) THEN
         FIELDPOS = FIELDPOS + 1
         VALPOS = VALPOS + 1
         ICOL = ICOL + 1
      END IF
      RETURN 
      END
