$STORAGE:2
      SUBROUTINE LAT2REAL(LAT,LON,REALLAT,REALLON)
C
C   ROUTINE CONVERTS LATITUDE AND LONGITUDE IN CHARACTER FORMAT OF
C   DEGREES, MINUTES AND HEMISPHERE INTO REAL NUMBERS.  OUTPUT 
C   VALUES ARE IN FLOATING POINT DEGREES WITH SOUTH LATITUDES AND
C   WEST LONGITUDES AS NEGATIVE NUMBERS.
C
C   Input:
C      LAT......CHAR*7 Latitude (such as 4230N)
C      LON......CHAR*8 Longitude
C   Output:
C      REALLAT..REAL*4 Latitude in floating point degrees
C      REALLON..REAL*4 Longitude in floating point degrees
C
      CHARACTER*7 LAT
      CHARACTER*8 LON
      CHARACTER*1 SPHERE
      REAL REALLAT,REALLON,XDEG,XMIN,XSEC
C      
      READ(LAT,'(3F2.0,A1)') XDEG,XMIN,XSEC,SPHERE
      REALLAT = XDEG + (XMIN/60.) + (XSEC/3600.)
      IF (SPHERE.EQ.'S') THEN
         REALLAT = - REALLAT
      END IF

      READ(LON,'(F3.0,2F2.0,A1)') XDEG,XMIN,XSEC,SPHERE
      REALLON = XDEG + (XMIN/60.) + (XSEC/3600.)
      IF (SPHERE.EQ.'W') THEN
         REALLON = - REALLON
      ELSE
      END IF
      RETURN
      END
