$STORAGE:2

      SUBROUTINE OKREPLY (REPLY,RTNCODE)
C
C   SUBROUTINE SOLICITS A YES/NO RESPONSE TO A QUESTION .
C   AND RETURNS 'Y' OR 'N' AS REPLY
C
C       RTNCODE = 1 IF AN F4 IS ENTERED, ELSE IT = 0
C
      CHARACTER*1 REPLY,RTNCODE,YESUP,NOUP,CDUM
      CHARACTER*5 CTEMP(2)
      CHARACTER*2 INCHAR
      CHARACTER MSGLIN*80,NOWRD*7,YESWRD*7  
      LOGICAL FIRSTCALL
      DATA FIRSTCALL/.TRUE./
C
      IF (FIRSTCALL) THEN
         FIRSTCALL=.FALSE.        
         CALL GETYN(1,1,YESUP,CDUM)
         CALL GETYN(2,1,NOUP,CDUM)
C         
         MSGLIN = ' '
         NMSG=502
         CALL GETMSG(NMSG,MSGLIN)
         CALL PARSE1(MSGLIN,80,2,5,CTEMP(1),RTNCODE)
         YESWRD=' '
         YESWRD(2:)=CTEMP(1)
         NCHYES=MIN0(LNG(CTEMP(1))+2,7)
         NOWRD=' '
         NOWRD(2:)=CTEMP(2)
         NCHNO=MIN0(LNG(CTEMP(2))+2,7)
C
         CALL GETMSG(503,MSGLIN)
         CALL GETMSG(999,MSGLIN)
      ENDIF   
C
      RTNCODE = '0'
C
      CALL POSLIN(IROW,ICOL)
      CALL WRTSTR(MSGLIN,15,14,0)
   50 CONTINUE
      CALL LOCATE(IROW,ICOL+11,IERR)
      CALL GETCHAR(0,INCHAR)
      IF (INCHAR(2:2).NE.' ') THEN
         IF (INCHAR.EQ.'4F') THEN
            REPLY = 'N'
            RTNCODE = '1'
            RETURN
         ELSE
            CALL WRTMSG(3,247,12,1,0,' ',0)
            GO TO 50 
         END IF
      ELSE
         REPLY = INCHAR(1:1)
         IF (REPLY.EQ.YESUP) THEN
            REPLY='Y'
            CALL WRTSTR(YESWRD,NCHYES,15,1)
         ELSE IF (REPLY.EQ.NOUP) THEN
            REPLY='N'
            CALL WRTSTR(NOWRD,NCHNO,15,1)
         ELSE
            CALL WRTMSG(3,247,12,1,0,' ',0)
            GO TO 50
         END IF 
      END IF
C
      RETURN
      END
