$STORAGE:2 

      SUBROUTINE OPENLD (RECTYPE,RTNFLAG)
C
C   ROUTINE TO OPEN THE TEMPORARY LOAD FILE FOR THE RECTYPE SPECIFIED.
C   IF REQUESTS THE DATASET-ID NEEDED FROM THE USER.
C
C   INPUT:  RECTYPE...'MLY','DLY',etc
C   OUTPUT: RTNFLAG...'4F' IF USER PRESSED F4 WHEN ASKED FOR THE
C                     DATASET-ID - NO FILE OPENED.
C
      CHARACTER*12 TEMPFILE
      CHARACTER*3 RECTYPE,DDSID
      CHARACTER*2 RTNFLAG
C
      CALL POSLIN(IROW,ICOL)
      JROW = IROW + 9
20    CONTINUE
      CALL LOCATE(JROW,13,IERR)
      CALL WRTSTR('Dataset-Id: ',12,14,0)
      CALL GETSTR(3,DDSID,3,15,1,RTNFLAG)
      IF (DDSID.EQ.'  '.OR.RTNFLAG.EQ.'4F') THEN
         RETURN
      END IF
C
      TEMPFILE = 'Q:'
      TEMPFILE(3:5) = RECTYPE
      TEMPFILE(6:8) = DDSID
      TEMPFILE(9:12) = '.DAT'
      OPEN (25,FILE=TEMPFILE,STATUS='OLD',FORM='BINARY',SHARE='DENYWR'
     +       ,MODE='READ',IOSTAT=IOCHK)
      IF (IOCHK.NE.0) THEN
         CALL OPENMSG(TEMPFILE,'GRAFINIT    ',IOCHK)
         GO TO 20
      END IF
      RETURN
      END
