$STORAGE:2

      SUBROUTINE OPENWIN(IWIN,BUFFER,STROW,STCOL,ENDROW,ENDCOL)
C
C   ROUTINE TO OPEN A WINDOW ON THE SCREEN (TEXT MODE).
C   THE WINDOW IS DEFINED BY THE CORNERS OF  STROW,STCOL AND ENDROW,ENDCOL.
C
C   INPUT:
C      IWIN...........THE CURRENT WINDOW NUMBER (1 OR 2).
C      BUFFER.........BUFFER SPACE TO HOLD THE WINDOW TEXT
C      STROW,STCOL....UPPER LEFT CORNER OF THE WINDOW (LOW ROW)
C      ENDROW,ENDCOL..LOWER RIGHT CORNER OF THE WINDOW (HIGH ROW)
C
C
C      MAIN ENTRY POINT -  SAVES THE SCREEN, DRAWS THE WINDOW BORDER, 
C           AND CLEARS THE WINDOW.
C      CLOSWIN - CLOSES THE WINDOW BY RESTORING THE SCREEN
C      CLRWIN -  CLEARS THE CURRENT WINDOW.
C
      INTEGER*2 BUFFER(*),STROW,STCOL,ENDROW,ENDCOL
     +         ,IROW1(2),IROW2(2),ICOL1(2),ICOL2(2)
      LOGICAL WOPEN(2)
      DATA  WOPEN /2*.FALSE./
C
      IROW1(IWIN) = STROW
      ICOL1(IWIN) = STCOL
      IROW2(IWIN) = ENDROW
      ICOL2(IWIN) = ENDCOL
C
      CALL WINSAV(BUFFER,2048,0,IROW1(IWIN),ICOL1(IWIN)
     +           ,IROW2(IWIN),ICOL2(IWIN),IFLAG)    
      CALL DRWBOX(ICOL1(IWIN),IROW1(IWIN),ICOL2(IWIN)
     +           ,IROW2(IWIN),2,0,3) 
      WOPEN(IWIN) = .TRUE.
C -------------------------------------------------------------------------
C  ENTRY POINT TO CLEAR THE WINDOW BY SCROLLING ALL LINES WITHIN THE WINDOW 
C  UP 
C -------------------------------------------------------------------------
      ENTRY CLRWIN(IWIN)

      CALL CLTEXT(3,0,IERR)
      NUMLIN = IROW2(IWIN) - IROW1(IWIN) - 1
      CALL SCROLL(1,NUMLIN,IROW1(IWIN)+1,ICOL1(IWIN)+1
     +           ,IROW2(IWIN)-1,ICOL2(IWIN)-1)
      CALL CLTEXT(0,0,IERR)
      RETURN
C -----------------------------------------------------------------------
C  ENTRY POINT TO CLOSE THE WINDOW AND RESTORE THE SCREEN BEHIND IT
C -----------------------------------------------------------------------
      ENTRY CLOSWIN(IWIN,BUFFER)

      IF (WOPEN(IWIN)) THEN
         CALL WINSAV(BUFFER,2048,1,IROW1(IWIN),ICOL1(IWIN)
     +              ,IROW2(IWIN),ICOL2(IWIN),IFLAG)
         WOPEN(IWIN) = .FALSE.
      END IF
      RETURN
      END
      