$STORAGE:2
C
      SUBROUTINE OPENMSG(FILNAM,ROUTINE,IOCHK)
C
C   ROUTINE TO ASK IF A USER WANTS TO TRY TO OPEN A FILE AGAIN
C   IF NOT - PROCESSING IS STOPPED AND ERRORLEVEL IS SET TO 2
C
      CHARACTER*2 INCHAR
      CHARACTER*(*) ROUTINE
      CHARACTER*(*) FILNAM
      CHARACTER*44 MESSAG
      INTEGER*2 IOCHK
C
      CALL WRTMSG(4,43,12,1,0,' ',0)
      CALL LOCATE(22,0,IERR)
      LNGF = MIN0(LNG(FILNAM),24)
      LNGR = MIN0(LNG(ROUTINE),12)
      WRITE (MESSAG,15) FILNAM(1:LNGF),ROUTINE(1:LNGR),IOCHK
   15 FORMAT(A,2X,A,2X,I4)
      CALL WRTSTR(MESSAG,44,12,0)
      CALL WRTMSG(2,248,12,0,0,' ',0)
   50 CONTINUE
      CALL GETCHAR(0,INCHAR)
      IF (INCHAR.EQ.'R ')THEN
         CALL CLRMSG(4)
         CALL CLRMSG(3)
         CALL CLRMSG(2)
         RETURN
      ELSE IF (INCHAR.EQ.'A ')THEN
         CALL CLRMSG(4)
         CALL CLRMSG(3)
         CALL CLRMSG(2)
         STOP 2
      ELSE
         CALL BEEP
         GO TO 50
      END IF
C
      END
