$STORAGE:2
      SUBROUTINE OPENINPUT(RECTYPE,DATASOURCE)
C
C   SUBROUTINE TO OPEN INPUT FILE 25 USING THE APPROPRIATE FILE NAME.         
C       HOURLY DATA IS IN DATAEASE FORM "HOURLY DATA" OR "H HLY DATA"
C       DAILY DATA IS IN DATAEASE FORM "DAILY DATA" OR "H DLY DATA"
C       SYNOPTIC DATA IS IN DATAEASE FORM "SYNOPTIC DATA" OR "H SYN DATA"
C       UPPER AIR DATA IS IN DATAEASE FORM "UPPER AIR DATA" OR "H U-A
C       MONTHLY DATA IS IN DATAEASE FORM "MONTHLY DATA".
C
C  PROGRAM CONTROL VARIABLES
C
      CHARACTER*1 DATASOURCE
      CHARACTER*3 RECTYPE,TYPDEF(7) 
      CHARACTER*22 FILNAME
      CHARACTER*24 FRMNAM(14)
      INTEGER*4 NUMREC
      DATA TYPDEF /'MLY','10D','DLY','SYN','HLY','15M','U-A'/
      DATA FRMNAM /'MONTHLY DATA','TEN DAY DATA','DAILY DATA'
     +   ,'SYNOPTIC DATA','HOURLY DATA','FIFTEEN MINUTE DATA'
     +   ,'UPPER-AIR DATA','H MLY DATA','H 10D DATA','H DLY DATA'
     +   ,'H SYN DATA','H HLY DATA','H 15M DATA','H U-A DATA'/
C
C   FIND THE RELATIVE NUMBER OF THE DATATYPE WANTED TO INDEX INTO THE
C   FRMNAM ARRAY
C
      DO 20 I = 1,7
         IF (RECTYPE.EQ.TYPDEF(I)) THEN
            ITYPE = I
            GO TO 30
         END IF
20    CONTINUE
      CALL WRTMSG(3,81,12,1,1,RECTYPE,3)
      STOP 2
30    CONTINUE
      IF (DATASOURCE.NE.'M'.AND.DATASOURCE.NE.'m'.AND.DATASOURCE.NE.
     +     'S'.AND.DATASOURCE.NE.'s') THEN
         CALL WRTMSG(3,83,12,1,1,DATASOURCE,1)
         DATASOURCE = 'S'
      END IF
      IF (DATASOURCE.EQ.'S'.OR.DATASOURCE.EQ.'s') THEN
         ITYPE = ITYPE + 7
      END IF
C  
C   FIND THE FILE NAME OF THE DATAEASE FORM WANTED
C
      CALL FNDFIL(FRMNAM(ITYPE),FILNAME,NUMREC)
      IF (FILNAME.EQ.'       ') THEN
         STOP 2
      END IF
C   
C   OPEN THE DATA FILE WANTED
C
200   CONTINUE
      OPEN (25,FILE=FILNAME,STATUS='OLD',FORM='BINARY',SHARE='DENYNONE'
     +       ,MODE='READ',IOSTAT=IOCHK)
      IF (IOCHK.NE.0) THEN
         CALL OPENMSG(FILNAME,'OPENINPUT   ',IOCHK)
         GO TO 200
      END IF
      RETURN
      END
************************************************************************
$PAGE
************************************************************************
      SUBROUTINE READMLY(DDSID,STNID,ELEM,YEAR,VALUE,FLAG1,RTNCODE)     
C
C    THIS SUBROUTINE READS A MLY FORMAT DATAEASE RECORD
C       THE INPUT DATA IS READ AS AN UNFORMATTED BINARY FILE,
C       READING ALL INPUT INTO THE CHARACTER ARRAY INREC.  THE 
C       VARIABLES WITHIN THE RECORD ARE EQUIVALENCED TO THE 
C       APPROPRIATE POSITION WITHIN INREC.
C
C  LOCAL VARIABLES
      CHARACTER*8 LOCALID
      CHARACTER*4 IYEAR
      CHARACTER*3 IELEM,IDDSID
      CHARACTER*1 INREC(84) 
      CHARACTER*84 INREC2
      INTEGER*2 HEADER(5)
C  PASSED VARIABLES
      CHARACTER*8 STNID
      INTEGER*2 DDSID,ELEM,YEAR
      CHARACTER*4 VALUE(12)
      CHARACTER*1 FLAG1(12),RTNCODE
C
C    EQUIVALENCE THE INPUT VARIABLES TO THE INPUT RECORD STRING
C
      EQUIVALENCE (HEADER,INREC(1)),(IDDSID,INREC(7)), 
     +            (LOCALID,INREC(10)),
     +            (IELEM,INREC(18)),(IYEAR,INREC(21))
      EQUIVALENCE (INREC(1),INREC2)
C
      RTNCODE = '0'
   10 CONTINUE
      READ(25,END=100) INREC
      IF(HEADER(1).NE.12.AND.HEADER(1).NE.14) GO TO 10
      STNID = LOCALID
      READ(IDDSID,'(I3)') DDSID
      READ(IYEAR,'(I4)') YEAR
      READ(IELEM,'(I3)') ELEM
      DO 50 I=1,12
         IPOS = 25 + (I-1)*5
         VALUE(I) = INREC2(IPOS:IPOS+3)
         FLAG1(I) = INREC(IPOS+4)
   50 CONTINUE
      RETURN   
C      
  100 CONTINUE
      RTNCODE = '1'
      RETURN
      END
$PAGE
***********************************************************************
      SUBROUTINE READ10D(DDSID,STNID,ELEM,YEAR,VALUE,FLAG1
     +    ,RTNCODE)     
C
C    THIS SUBROUTINE READS A 10D FORMAT DATAEASE RECORD
C       THE INPUT DATA IS READ AS AN UNFORMATTED BINARY FILE,
C       READING ALL INPUT INTO THE CHARACTER ARRAY INREC.  THE 
C       VARIABLES WITHIN THE RECORD ARE EQUIVALENCED TO THE 
C       APPROPRIATE POSITION WITHIN INREC.
C
C  LOCAL VARIABLES
      CHARACTER*8 LOCALID
      CHARACTER*4 IYEAR
      CHARACTER*3 IELEM,IDDSID
      CHARACTER*1 INREC(210) 
      CHARACTER*100 INREC2
      INTEGER*2 HEADER(6)
C  PASSED VARIABLES
      CHARACTER*8 STNID
      INTEGER*2 DDSID,ELEM,YEAR
      CHARACTER*4 VALUE(36)
      CHARACTER*1 FLAG1(36),RTNCODE
C
C    EQUIVALENCE THE INPUT VARIABLES TO THE INPUT RECORD STRING
C
      EQUIVALENCE (HEADER,INREC(1)),(IDDSID,INREC(13)), 
     +            (LOCALID,INREC(16)),
     +            (IELEM,INREC(24)),(IYEAR,INREC(27))
      EQUIVALENCE (INREC(1),INREC2)

C
      RTNCODE = '0'
   10 CONTINUE
      READ(25,END=100) INREC
      IF(HEADER(1).NE.12.AND.HEADER(1).NE.14) GO TO 10
      STNID = LOCALID
      READ(IDDSID,'(I3)') DDSID
      READ(IYEAR,'(I4)') YEAR
      READ(IELEM,'(I3)') ELEM
      DO 50 I=1,36
         IPOS = 31 + (I-1)*5
         VALUE(I) = INREC2(IPOS:IPOS+3)
         FLAG1(I) = INREC(IPOS+4)
   50 CONTINUE
      RETURN
C      
  100 CONTINUE
      RTNCODE = '1'
      RETURN
      END
$PAGE
***********************************************************************
      SUBROUTINE READDLY(DDSID,STNID,ELEM,YEAR,MONTH,VALUE,FLAG1
     +    ,RTNCODE)     
C
C    THIS SUBROUTINE READS A DLY FORMAT DATAEASE RECORD
C       THE INPUT DATA IS READ AS AN UNFORMATTED BINARY FILE,
C       READING ALL INPUT INTO THE CHARACTER ARRAY INREC.  THE 
C       VARIABLES WITHIN THE RECORD ARE EQUIVALENCED TO THE 
C       APPROPRIATE POSITION WITHIN INREC.
C
C  LOCAL VARIABLES
      CHARACTER*8 LOCALID
      CHARACTER*4 IYEAR
      CHARACTER*3 IELEM,IDDSID
      CHARACTER*2 IMONTH
      CHARACTER*1 INREC(186) 
      CHARACTER*100 INREC2
      INTEGER*2 HEADER(5)
C  PASSED VARIABLES
      CHARACTER*8 STNID
      INTEGER*2 DDSID,ELEM,YEAR,MONTH
      CHARACTER*4 VALUE(31)
      CHARACTER*1 FLAG1(31),RTNCODE
C
C
C    EQUIVALENCE THE INPUT VARIABLES TO THE INPUT RECORD STRING
C
      EQUIVALENCE (HEADER,INREC(1)),(IDDSID,INREC(12)), 
     +            (LOCALID,INREC(15)),
     +            (IELEM,INREC(23)),(IYEAR,INREC(26)),
     +            (IMONTH,INREC(30))
      EQUIVALENCE (INREC(1),INREC2)

C
      RTNCODE = '0'
   10 CONTINUE
      READ(25,END=100) INREC
      IF(HEADER(1).NE.12.AND.HEADER(1).NE.14) GO TO 10
      STNID = LOCALID
      READ(IDDSID,'(I3)') DDSID
      READ(IYEAR,'(I4)') YEAR
      READ(IMONTH,'(I2)') MONTH
      READ(IELEM,'(I3)') ELEM
      DO 50 I=1,31
         IPOS = 32 + (I-1)*5
         VALUE(I) = INREC2(IPOS:IPOS+3)
         FLAG1(I) = INREC(IPOS+4)
   50 CONTINUE
      RETURN
C      
  100 CONTINUE
      RTNCODE = '1'
      RETURN
      END
$PAGE
**********************************************************************
      SUBROUTINE READHLY(DDSID,STNID,ELEM,YEAR,MONTH,DAY,VALUE,FLAG1
     +    ,RTNCODE)     
C
C    THIS SUBROUTINE READS A HLY FORMAT DATAEASE RECORD
C       THE INPUT DATA IS READ AS AN UNFORMATTED BINARY FILE,
C       READING ALL INPUT INTO THE CHARACTER ARRAY INREC.  THE 
C       VARIABLES WITHIN THE RECORD ARE EQUIVALENCED TO THE 
C       APPROPRIATE POSITION WITHIN INREC.
C
C  LOCAL VARIABLES
      CHARACTER*8 LOCALID
      CHARACTER*4 IYEAR
      CHARACTER*3 IELEM,IDDSID
      CHARACTER*2 IMONTH,IDAY
      CHARACTER*1 INREC(151) 
      CHARACTER*100 INREC2
      INTEGER*2 HEADER(4)
C  PASSED VARIABLES
      CHARACTER*8 STNID
      INTEGER*2 DDSID,ELEM,YEAR,MONTH,DAY
      CHARACTER*4 VALUE(24)
      CHARACTER*1 FLAG1(24),RTNCODE
C
C
C    EQUIVALENCE THE INPUT VARIABLES TO THE INPUT RECORD STRING
C
      EQUIVALENCE (HEADER,INREC(1)),(IDDSID,INREC(10)), 
     +            (LOCALID,INREC(13)),
     +            (IELEM,INREC(21)),(IYEAR,INREC(24)),
     +            (IMONTH,INREC(28)),(IDAY,INREC(30))
      EQUIVALENCE(INREC(1),INREC2)
C
      RTNCODE = '0'
   10 CONTINUE
      READ(25,END=100) INREC
      IF(HEADER(1).NE.12.AND.HEADER(1).NE.14) GO TO 10
      STNID = LOCALID
      READ(IDDSID,'(I3)') DDSID
      READ(IYEAR,'(I4)') YEAR
      READ(IMONTH,'(I2)') MONTH
      READ(IDAY,'(I2)') DAY
      READ(IELEM,'(I3)') ELEM
      DO 50 I=1,24
         IPOS = 32 + (I-1)*5
         VALUE(I) = INREC2(IPOS:IPOS+3)
         FLAG1(I) = INREC(IPOS+4)
   50 CONTINUE
      RETURN   
C
  100 CONTINUE
      RTNCODE = '1'
      RETURN
      END
************************************************************************
$PAGE
      SUBROUTINE READ15M(DDSID,STNID,ELEM,YEAR,MONTH,DAY,VALUE,FLAG1
     +    ,RTNCODE)     
C
C    THIS SUBROUTINE READS A 15M FORMAT DATAEASE RECORD
C       THE INPUT DATA IS READ AS AN UNFORMATTED BINARY FILE,
C       READING ALL INPUT INTO THE CHARACTER ARRAY INREC.  THE 
C       VARIABLES WITHIN THE RECORD ARE EQUIVALENCED TO THE 
C       APPROPRIATE POSITION WITHIN INREC.
C
C  LOCAL VARIABLES
      CHARACTER*8 LOCALID
      CHARACTER*4 IYEAR
      CHARACTER*3 IELEM,IDDSID
      CHARACTER*2 IMONTH,IDAY
      CHARACTER*1 INREC(529) 
      CHARACTER*100 INREC2
      INTEGER*2 HEADER(13)
C  PASSED VARIABLES
      CHARACTER*8 STNID
      INTEGER*2 DDSID,ELEM,YEAR,MONTH,DAY
      CHARACTER*4 VALUE(96)
      CHARACTER*1 FLAG1(96),RTNCODE
C
C
C    EQUIVALENCE THE INPUT VARIABLES TO THE INPUT RECORD STRING
C
      EQUIVALENCE (HEADER,INREC(1)),(IDDSID,INREC(28)), 
     +            (LOCALID,INREC(31)),
     +            (IELEM,INREC(39)),(IYEAR,INREC(42)),
     +            (IMONTH,INREC(46)),(IDAY,INREC(48))
      EQUIVALENCE(INREC(1),INREC2)
C
      RTNCODE = '0'
   10 CONTINUE
      READ(25,END=100) INREC
      IF(HEADER(1).NE.12.AND.HEADER(1).NE.14) GO TO 10
      STNID = LOCALID
      READ(IDDSID,'(I3)') DDSID
      READ(IYEAR,'(I4)') YEAR
      READ(IMONTH,'(I2)') MONTH
      READ(IDAY,'(I2)') DAY
      READ(IELEM,'(I3)') ELEM
      DO 50 I=1,96
         IPOS = 50 + (I-1)*5
         VALUE(I) = INREC2(IPOS:IPOS+3)
         FLAG1(I) = INREC(IPOS+4)
   50 CONTINUE
      RETURN   
C
  100 CONTINUE
      RTNCODE = '1'
      RETURN
      END
************************************************************************
$PAGE
      SUBROUTINE READSYN(DDSID,STNID,ELEM,YEAR,MONTH,DAY,VALUE,FLAG1
     +    ,RTNCODE)     
C
C    THIS SUBROUTINE READS A SYNOPTIC FORMAT DATAEASE RECORD
C       THE INPUT DATA IS READ AS AN UNFORMATTED BINARY FILE,
C       READING ALL INPUT INTO THE CHARACTER ARRAY INREC.  THE 
C       VARIABLES WITHIN THE RECORD ARE EQUIVALENCED TO THE 
C       APPROPRIATE POSITION WITHIN INREC.
C
C  LOCAL VARIABLES
      CHARACTER*8 LOCALID
      CHARACTER*4 IYEAR
      CHARACTER*3 IELEM,IDDSID
      CHARACTER*2 IMONTH,IDAY
      CHARACTER*1 INREC(67)
      CHARACTER*67 INREC2 
      INTEGER*2 HEADER(2)
C  PASSED VARIABLES
      CHARACTER*8 STNID
      INTEGER*2 DDSID,ELEM,YEAR,MONTH,DAY
      INTEGER*4 VALUE(8)
      CHARACTER*1 FLAG1(8),RTNCODE
C
C
C    EQUIVALENCE THE INPUT VARIABLES TO THE INPUT RECORD STRING
C
      EQUIVALENCE (HEADER,INREC(1)),(IDDSID,INREC(6)),  
     +            (LOCALID,INREC(9)),
     +            (IELEM,INREC(17)),(IYEAR,INREC(20)),
     +            (IMONTH,INREC(24)),(IDAY,INREC(26))
      EQUIVALENCE (INREC(1),INREC2)
C
      RTNCODE = '0'
   10 CONTINUE
      READ(25,END=100) INREC
      IF(HEADER(1).NE.12.AND.HEADER(1).NE.14) GO TO 10
      STNID = LOCALID
      READ(IDDSID,'(I3)') DDSID
      READ(IYEAR,'(I4)') YEAR
      READ(IMONTH,'(I2)') MONTH
      READ(IDAY,'(I2)') DAY
      READ(IELEM,'(I3)') ELEM
      DO 50 I=1,8 
         IPOS = 28 + (I-1)*5
         VALUE(I) = INREC2(IPOS:IPOS+3)
         FLAG1(I) = INREC(IPOS+4)
   50 CONTINUE
      RETURN   
C
  100 CONTINUE
      RTNCODE = '1'
      RETURN
      END
************************************************************************
$PAGE
      SUBROUTINE READUA(DDSID,STNID,YEAR,MONTH,DAY,HOUR,NUMLVL,LVLNUM,
     +    PRESSURE,HEIGHT,TEMP,DEWPTDEP,WNDDIR,WNDSPEED,FLAGS,RTNCODE)
C
C    THIS SUBROUTINE READS A UPPER AIR FORMAT DATAEASE RECORD
C       THE INPUT DATA IS READ AS AN UNFORMATTED BINARY FILE,
C       READING ALL INPUT INTO THE CHARACTER ARRAY INREC.  THE 
C       VARIABLES WITHIN THE RECORD ARE EQUIVALENCED TO THE 
C       APPROPRIATE POSITION WITHIN INREC.
C
C  LOCAL VARIABLES
      CHARACTER*62 INREC2
      CHARACTER*8 LOCALID
      CHARACTER*6 IFLAGS
      CHARACTER*3 IDDSID,INUMLVL,ILVLNUM
      CHARACTER*4 IYEAR
      CHARACTER*2 IMONTH,IDAY,IHOUR
      CHARACTER*1 INREC(62) 
      INTEGER*2 HEADER(2)
C  PASSED VARIABLES
      CHARACTER*8 STNID
      CHARACTER*6 FLAGS
      INTEGER*2 DDSID,YEAR,MONTH,DAY,HOUR,NUMLVL,LVLNUM
      REAL*4 PRESSURE,HEIGHT,TEMP,DEWPTDEP,WNDDIR,WNDSPEED
      CHARACTER*1 RTNCODE
C
C    EQUIVALENCE THE INPUT VARIABLES TO THE INPUT RECORD STRING
C
      EQUIVALENCE (HEADER,INREC(1)),(IDDSID,INREC(6)),
     +            (LOCALID,INREC(9)),(IYEAR,INREC(17)),
     +            (IMONTH,INREC(21)),(IDAY,INREC(23)),
     +            (IHOUR,INREC(25)),(INUMLVL,INREC(27)),
     +            (ILVLNUM,INREC(30)),(IFLAGS,INREC(57))
      EQUIVALENCE (INREC(1),INREC2)
C
      RTNCODE = '0'
   10 CONTINUE
      READ(25,END=100) INREC
      IF(HEADER(1).NE.12.AND.HEADER(1).NE.14) GO TO 10
      STNID = LOCALID
      READ(IDDSID,'(I3)') DDSID
      READ(IYEAR,'(I4)') YEAR
      READ(IMONTH,'(I2)') MONTH
      READ(IDAY,'(I2)') DAY
      READ(IHOUR,'(I2)') HOUR
      READ(INUMLVL,'(I3)') NUMLVL
      READ(ILVLNUM,'(I3)') LVLNUM
      PRESSURE = INREC2(33:36)
      HEIGHT   = INREC2(37:40)
      TEMP     = INREC2(41:44)
      DEWPTDEP = INREC2(45:48)
      WNDDIR   = INREC2(49:52)
      WNDSPEED = INREC2(53:56)
      FLAGS = IFLAGS 
      RETURN   
C      
  100 CONTINUE
      RTNCODE = '1'
      RETURN
      END
************************************************************************
$PAGE
      SUBROUTINE READNML (STNID,PERIOD,MONTH,ELEM,NORMAL,NMLTYP
     +                   ,NORMFLG,SDEV,EXTMAX,EMAXFLG,MAXYR
     +                   ,EXTMIN,EMINFLG,MINYR,MLYMAXMN,SDMAX
     +                   ,MLYMINMN,SDMIN,PQM,PQX,PQN,BITVAL,RTNCODE)
C
C    THIS SUBROUTINE READS A NORMALS FORMAT DATAEASE RECORD
C       THE INPUT DATA IS READ AS AN UNFORMATTED BINARY FILE,
C       READING ALL INPUT INTO THE CHARACTER ARRAY INREC.  THE 
C       VARIABLES WITHIN THE RECORD ARE EQUIVALENCED TO THE 
C       APPROPRIATE POSITION WITHIN INREC.
C
C   NOTE:  NUMERIC VARIABLES ARE EQUIVALENCED TO THE CHARACTER VARIABLE INREC.
C          SOME OF THE NUMERIC VARIABLES START ON ODD-BYTE BOUNDARIES.  EVEN
C          THOUGH THE DOCUMENTATION FOR MICROSOFT 5.0 FORTRAN SPECIFIES THAT
C          NON-CHARACTER ENTITIES MUST START ON EVEN-BYTE BOUNDARIES, THIS IS
C          NOT AN ACTUAL FORTRAN REQUIREMENT.  THIS HAS BEEN VERIFIED WITH
C          MICROSOFT TECHNICAL SUPPORT.  THE CURRENT EQUIVALENCES WORK AS
C          WRITTEN.  (5-20-91)
C
C       .. PASSED VARIABLES
      CHARACTER*8 STNID,PERIOD
      CHARACTER*4 MAXYR,MINYR
      CHARACTER*3 ELEM
      CHARACTER*1 RTNCODE,EMAXFLG,EMINFLG
      INTEGER*2 MONTH,NMLTYP,NORMFLG,BITVAL(30)
      REAL*4 NORMAL,SDEV,EXTMAX,EXTMIN,MLYMAXMN,MLYMINMN,SDMAX,
     +       SDMIN,PQM(5),PQX(5),PQN(5)
C     
C       .. LOCAL VARIABLES
C
      CHARACTER*1 INREC(165)
C
      CHARACTER*8 LOCALID,NPERIOD
      CHARACTER*4 MXYR,MNYR
      CHARACTER*3 ELEM1
      CHARACTER*2 OMONTH
      CHARACTER*1 EMAXFG,EMINFG
      INTEGER*1 TYPNML,NMLFG
      INTEGER*2 HEADER(2)
      REAL*4 NORM,MEAN,EMAX,EMIN,MYMX,MYMN,SDEMAX,SDEMIN
     +      ,P1(5),P2(5),P3(5) 
C
C
C    EQUIVALENCE THE INPUT VARIABLES TO THE INPUT RECORD STRING
C
      EQUIVALENCE (HEADER,INREC(1)),(LOCALID,INREC(11)),
     +            (NPERIOD,INREC(19)),(OMONTH,INREC(27)),
     +            (ELEM1,INREC(29)),(NORM,INREC(32)),(TYPNML,INREC(36)),
     +            (NMLFG,INREC(37)),(MEAN,INREC(38)),(EMAX,INREC(42)),
     +            (EMAXFG,INREC(46)),(MXYR,INREC(47)),(EMIN,INREC(51)),
     +            (EMINFG,INREC(55)),(MNYR,INREC(56)),(P1,INREC(60)),
     +            (MYMX,INREC(80)),(SDEMAX,INREC(84)),(P2,INREC(88)),
     +            (MYMN,INREC(108)),(SDEMIN,INREC(112)),(P3,INREC(116))
C
      RTNCODE = '0'
   10 CONTINUE
      READ(25,END=100) INREC
      IF(HEADER(1).NE.12.AND.HEADER(1).NE.14) GO TO 10
      STNID = LOCALID
      PERIOD = NPERIOD
      READ(OMONTH,'(I2)') MONTH
      ELEM = ELEM1
      NORMAL = NORM
      NMLTYP = INT2(TYPNML)
      NORMFLG = INT2(NMLFG)
      SDEV = MEAN
      EXTMAX = EMAX
      EMAXFLG = EMAXFG
      MAXYR = MXYR
      EXTMIN = EMIN
      EMINFLG = EMINFG
      MINYR = MNYR
      MLYMAXMN = MYMX
      SDMAX = SDEMAX
      MLYMINMN = MYMN
      SDMIN = SDEMIN
C
      DO 50 I=1,5
          PQM(I) = P1(I)
          PQX(I) = P2(I)
          PQN(I) = P3(I)
  50  CONTINUE
C
      DO 75 I=1,30
         IPOS = 136+ (I-1)
         BITVAL(I) = INREC(IPOS)
   75 CONTINUE
      RETURN   
C
  100 CONTINUE
      RTNCODE = '1'
      RETURN
      END
