
      SUBROUTINE RDDEFS(IUNIT,FLDNAME,FLDVALUES,RTNCODE)
C
C   ROUTINE TO READ FILE IUNIT (SHOULD BE POSITIONED AT DEFINITIONS FOR 
C     DATAEASE CHOICE FIELD FLDNAME), FIND OUT HOW MANY CHOICES THERE 
C     ARE AND LOAD THEM INTO FLDVALUES 
C
      CHARACTER*14 FLDNAME
      CHARACTER*20 FLDVALUES(99),MSGTXT
      CHARACTER*1  RTNCODE
C
      CHARACTER*1 INCHAR,NULL
      INTEGER*2 ZERO
      INTEGER*4 NUMDEF
C
      ZERO = 0
      NULL = CHAR(ZERO)
      NUMDEF = 0
C
C   FIND OUT HOW MANY DEFINITIONS THERE ARE
C
      READ(IUNIT,END=400) INCHAR
      READ(IUNIT,END=400) INCHAR
      CALL MOVBYT(1,INCHAR,1,NUMDEF,1)
      IF (NUMDEF.LT.1.OR.NUMDEF.GT.99) THEN
         WRITE(MSGTXT,'(A14,1X,I3)') FLDNAME,NUMDEF
         CALL WRTMSG(4,95,12,1,1,MSGTXT,20)
         RTNCODE = '1'
         RETURN
      END IF
c
C   READ THE DEFINITIONS AND STORE INTO FLDVALUES
C
      DO 300 IDEF = 1,NUMDEF  
         DO 200 I1 = 1,21
            READ(IUNIT,END=400) INCHAR
            IF (INCHAR.EQ.NULL) THEN
               GO TO 300
            ELSE
               IF (I1.LT.21) THEN
                  FLDVALUES(IDEF)(I1:I1) = INCHAR
               END IF
            END IF
  200    CONTINUE
C
C     ONLY GET HERE IF A DEFINITION IS LONGER THAN 20 CHARACTERS
C
         WRITE(MSGTXT,'(A14,1X,I2)') FLDNAME,IDEF
         CALL WRTMSG(4,88,12,1,1,MSGTXT,20)
         DO 250 I1 = 1,999
            READ(IUNIT,END=400) INCHAR
            IF (INCHAR.EQ.NULL) THEN
               GO TO 300
            END IF
  250    CONTINUE
         WRITE(MSGTXT,'(A14,1X,I2)') FLDNAME,IDEF
         CALL WRTMSG(4,80,12,1,1,MSGTXT,20)
         WRITE(*,270) FLDNAME
  270    FORMAT(9X,A14,' definition stops here')
         RETURN
C 
  300 CONTINUE
      RETURN
C
C   GET HERE IF AN UNEXPECTED EOF IS READ
C
  400 CONTINUE 
      WRITE(MSGTXT,'(A14,1X,I3)') FLDNAME,IDEF
      CALL WRTMSG(4,96,12,1,1,MSGTXT,20)
      RETURN
      END
