$STORAGE:2
      SUBROUTINE SETCLR(FGCOLOR,BGCOLOR)
C
C   ROUTINE TO SET THE CURRENT FOREGROUND AND BACKGROUND COLORS
C
      CHARACTER*78 TEXT(7)
      CHARACTER*2 INCHAR
      INTEGER*2 FGCOLOR,BGCOLOR
C
      CALL GETMSG(257,TEXT(2))
      CALL GETMSG(258,TEXT(3))
      CALL GETMSG(259,TEXT(4))
      CALL GETMSG(260,TEXT(5))
      CALL GETMSG(999,TEXT(5))
      TEXT(1) = ' '
      TEXT(6) = ' '
      DO 10 I = 1,7
         TEXT(I)(33:33) = CHAR(0)
10    CONTINUE
C
      CALL POSLIN(IROW,ICOL)
      CALL ACTPAG(2,IERR)
      CALL CLS
C
C   DRAW THE COLOR PALETTE
C
      CALL LOCATE(4,8,IERR)
      CALL CLTEXT(1,0,IERR)
      TEXT(7) = '      Color Palette      '
      TEXT(7)(25:25) = CHAR(0)
      CALL CWRITE(TEXT(7),15,IERR)
      DO 100 IBG = 0,7
         CALL CLTEXT(IBG,0,IERR)
         JCOL = IBG*3 + 8
         DO 100 IFG = 0,15
            CALL LOCATE(IFG+5,JCOL,IERR)
            TEXT(7) = ' *  '
            TEXT(7)(4:4) = CHAR(0)
            CALL CWRITE(TEXT(7),IFG,IERR)  
  100 CONTINUE
C
C   ALLOW THE USER TO SELECT THE COLOR OF INTEREST - DISPLAY
C   SOME TEXT IN THE CURRENT COLOR
C
      IF (FGCOLOR.LT.0.OR.FGCOLOR.GT.15) THEN
         BGCOLOR = 1
         FGCOLOR = 15
      END IF
  200 CONTINUE
      CALL CLTEXT(BGCOLOR,0,IERR)
      DO 220 ITEXT = 1,6
         CALL LOCATE (9+ITEXT,35,IERR) 
         CALL CWRITE (TEXT(ITEXT),FGCOLOR,IERR)
  220 CONTINUE
      JCOL = BGCOLOR*3 + 8
      CALL LOCATE (FGCOLOR+5,JCOL,IERR)
      TEXT(7) = '|*| '
      TEXT(7)(4:4) = CHAR(0)
      CALL CWRITE (TEXT(7),FGCOLOR+128,IERR)
      CALL LOCATE (16,35,IERR)
      CALL GETCHAR(0,INCHAR)
      CALL LOCATE (FGCOLOR+5,JCOL,IERR)
      TEXT(7) = ' *  '
      TEXT(7)(4:4) = CHAR(0)
      CALL CWRITE (TEXT(7),FGCOLOR,IERR)
  250 CONTINUE
      IF (INCHAR.EQ.'LA') THEN
         IF (BGCOLOR.GT.0) THEN
            BGCOLOR = BGCOLOR - 1
         ELSE
            BGCOLOR = 7
         END IF
      ELSE IF (INCHAR.EQ.'RA') THEN
         IF (BGCOLOR.LT.7) THEN
            BGCOLOR = BGCOLOR + 1
         ELSE
            BGCOLOR = 0
         END IF
      ELSE IF (INCHAR.EQ.'UA') THEN
         IF (FGCOLOR.GT.0) THEN
            FGCOLOR = FGCOLOR - 1
         ELSE
            FGCOLOR = 15
         END IF
      ELSE IF (INCHAR.EQ.'DA') THEN
         IF (FGCOLOR.LT.15) THEN
            FGCOLOR = FGCOLOR + 1
         ELSE
            FGCOLOR = 0
         END IF
      ELSE IF (INCHAR.EQ.'2F') THEN
         CALL ACTPAG(0,IERR)
         CALL LOCATE(IROW,ICOL,IERR)
         RETURN
      ELSE IF (INCHAR.EQ.'4F') THEN
         FGCOLOR = -1
         BGCOLOR = -1
         CALL ACTPAG(0,IERR)
         CALL LOCATE(IROW,ICOL,IERR)
         RETURN
      END IF
      IF (FGCOLOR.EQ.BGCOLOR) THEN
         GO TO 250
      END IF
      GO TO  200

      END

    