$STORAGE:2
C
      SUBROUTINE WRTMSG(MSGLIN,MSGNUM,FGCOLOR,BEEPON,WAIT,TEXT,TXTLEN)
C
C   THIS ROUTINE WRITES MESSAGE NUMBER MSGNUM INTO THE APPROPRIATE LINE
C     OF THE MESSAGE AREA AT THE BOTTOM OF THE SCREEN - LINE 1 IS BOTTOM
C     AFTER WRITING THE MESSAGE, IT BEEPS IF WANTED AND PAUSES IF
C     WANTED. THEN THE CURSOR IS RETURNED TO ITS LOCATION BEFORE THIS
C    ROUTINE WAS CALLED.  
C
      PARAMETER(JMAX=77)
      INTEGER*2 MSGLIN,FGCOLOR,BEEPON,MSGNUM,WAIT,TXTLEN
      CHARACTER*2 INCHAR
      CHARACTER*10 TEXT
      CHARACTER*78 WAITMSG
      CHARACTER*78 OUTMSG
      LOGICAL FRSTCL
      DATA FRSTCL /.TRUE./
C
C   ON FIRST CALL TO THIS ROUTINE SET TEXT FOR COLOR OR B&W MODE
C
      IF (FRSTCL) THEN
         FRSTCL = .FALSE.
         CALL STATUS(IMODE,ICLTYP,IPAGE)
      END IF
      IF (IMODE.EQ.3) THEN
         IFG = FGCOLOR
         IBG = 0
      ELSE
         IF (FGCOLOR.EQ.1) THEN
            IFG = 1
            IBG = 0
         ELSE IF (FGCOLOR.EQ.12.OR.FGCOLOR.EQ.4) THEN
            IBG = 7
            IFG = 0
         ELSE IF (FGCOLOR.EQ.14) THEN
            IBG = 0
            IFG = 15
         END IF
      END IF
C
C   READ THE MESSAGE WANTED
C
      CALL GETMSG(MSGNUM,OUTMSG)
      CALL GETMSG(202,WAITMSG)
      CALL GETMSG(999,WAITMSG)
C
C   APPEND TEXT TO THE MESSAGE IF WANTED
C      
      IF (TXTLEN.GT.0) THEN
         DO 100 J = JMAX,1,-1
            IF (OUTMSG(J:J).NE.' ') THEN
               JEND = J + 2
               GO TO 110
            END IF
  100    CONTINUE
         JEND = 1
  110    CONTINUE
         JTOTAL = JEND+TXTLEN-1
         IF (JTOTAL.LE.JMAX) THEN
            OUTMSG(JEND:JTOTAL) = TEXT(1:TXTLEN)
         ELSE
            OUTMSG(JEND:JMAX) = TEXT(1:JMAX-JEND+1)
         END IF
      END IF
C
C   DISPLAY THE MESSAGE
C
      IF (OUTMSG.EQ.' ') THEN
         GO TO 900
      END IF
      OUTMSG(78:78) = CHAR(0)
      CALL POSLIN(IROW,ICOL)
      CALL LOCATE(25-MSGLIN,0,IERR)
      CALL CLTEXT(IBG,0,IERR)
      CALL CWRITE(OUTMSG,IFG,IERR)
C
C   BEEP AND/OR PAUSE IF WANTED
C
      IF (BEEPON.EQ.1) THEN
         CALL BEEP
      END IF
      IF (WAIT.EQ.1) THEN
         NROW = 26 - MSGLIN
         IF (NROW.GT.24) THEN
            NROW = NROW - 2
         END IF
         CALL LOCATE(NROW,0,IERR)
         CALL WRTSTR(WAITMSG,32,15,0)
         CALL GETCHAR(0,INCHAR)               
         CALL CLRMSG(MSGLIN)
         CALL CLRMSG(25-NROW)
      END IF
C
      CALL LOCATE(IROW,ICOL,IERR)
      RETURN
C
C   GET HERE IF THERE IS A SYSTEM ERROR - MESSAGES NOT FOUND
C
  900 CONTINUE
      CALL LOCATE(23,0,IERR)
      CALL WRTSTR('Message file /DATA/MESSAGES.FTN is in error',43,12,0)
      WRITE(OUTMSG,910) MSGNUM
  910 FORMAT('Message number ',I5,' can not be found')
      CALL LOCATE(24,0,IERR)
      CALL WRTSTR(OUTMSG,40,12,0)    
      CALL BEEP
      CALL WRTSTR(' - Hit any key to continue',26,15,0)
      CALL GETCHAR(0,INCHAR)
      RETURN
      END
C
***********************************************************************

      SUBROUTINE CLRMSG(MSGLINE)
C
C   THIS ROUTINE CLEARS THE APPROPRIATE LINE OF THE
C      MESSAGE AREA AT THE BOTTOM OF THE SCREEN - LINE 1 IS BOTTOM
C
      PARAMETER (NCMSG=81)
      INTEGER*2 MSGLINE
      CHARACTER*1 OUTMSG(NCMSG)
      DATA OUTMSG/NCMSG*' '/
      OUTMSG(NCMSG) = CHAR(0)
C
      CALL POSLIN(IROW,ICOL) 
      CALL LOCATE(25-MSGLINE,0,IERR)
      CALL CLTEXT(0,0,IERR)
      CALL CWRITE(OUTMSG,7,IERR)
      CALL LOCATE(IROW,ICOL,IERR)
      RETURN
      END
