$STORAGE:2
      SUBROUTINE CKINTGR(INTVAL,IER)
C
C       ** OBJECTIVE:  SET ERROR FLAG TO 1 IF THE INTEGER VALUE IS TOO BIG
C                      FOR I5 FORMAT.  REDEFINE THE INTEGER TO THE MAXIMUM
C                      POSITIVE OR MINIMUM NEGATIVE VALUE THAT WILL FIT IN 
C                      AN I5 FORMAT.     
C       ** REVISION 8-31-93  NEW ROUTINE 
C
      INTEGER*4 INTVAL
      INTEGER*2 IER
C
      IER = 0
      IF (INTVAL.LT.-9999) THEN
         INTVAL=-9999
         IER   =1
      ELSE IF (INTVAL.GT.99999) THEN
         INTVAL = 99999
         IER = 1
      ENDIF
      RETURN
      END      
