$STORAGE:2
C
C     PROGRAM CSDRVINF
C
c     THE PROGRAM CONSTRUCTS THE "CSADDRS.DAT" BATCH FILE BASED ON THE ADDRESS
C     FOUND IN THE CSINFO.DAT FILE.  THE CSINFO.DAT FILE CREATED BY USING DEBUG
C     COMMAND TO SEARCH THE ADDRESS OF THE TEXT ":\COSORT\COSORT.COR" WHERE 
C     LOCATED IN THE COSORT.EXE FILE DURING THE EXECUTION OF MODCSDRV.BAT.
C
C     NOTE:
C
C     IF THE FILE "CSINFO.DAT" IS NOT FOUND, THE PROGRAM SETS TO ERRORLEVEL 2.
C     IF THE ADDRESS OF TEXT "\COSORT\CORORT.COR" IS NOT FOUND IN THE FILE
C     COSORT.EXE, THE PROGRAM SETS TO ERRORLEVEL 3.  OTHERWISE, THE PROGRAM
C     SETS TO ERRORLEVEL 0. 
C
      PROGRAM CSDRVINF
C
      CHARACTER*1  CHAR1,CHAR2
      INTEGER*2    BGNADDRS,ENDADDRS
      CHARACTER*2  INVALUE(20)
      CHARACTER*80 LINE,OUTFRMT
      DATA INVALUE /'5C','43','4F','53','4F','52','54','5C','43','4F'
     +             ,'53','4F','52','54','2E','43','4F','52','00','00'/
      DATA CHAR1,CHAR2 /'W','Q'/
C
      OPEN(51,FILE='C:\CSADDRS.DAT',STATUS='UNKNOWN',FORM='FORMATTED')
C
      BGNADDRS = 0
      ENDADDRS = 0
C
      OPEN(75,FILE='C:\CSINFO.DAT',STATUS='OLD',FORM='FORMATTED',
     +    IOSTAT=IOCHK)
      IF (IOCHK.NE.0)THEN
         STOP 2
      END IF
C
C     READ THE ADDRESS WHERE THE ":\COSORT\COSORT.COR" LOCATED IN THE FILE
C     COSORT.EXE FROM THE FILE CSINFO.DAT.
C
      READ(75,*)
      READ(75,'(5X(Z4))') BGNADDRS
      IF (BGNADDRS .EQ. 0) THEN
         STOP 3
      END IF
C
C     COMPUTE THE STARTING AND ENDING ADDRESS OF THE TEXT LOCATED IN THE FILE
C     COSORT.EXE
C
      BGNADDRS = BGNADDRS - 1 
      ENDADDRS = BGNADDRS + 19
C
      WRITE(LINE,500)BGNADDRS,ENDADDRS,(INVALUE(J),J=1,20)
 500  FORMAT('F',1X,Z4,1X,Z4,20(1X,A2))
      CALL GETFRMT(LINE,OUTFRMT)
      WRITE(51,OUTFRMT) LINE
      WRITE(51,'(A1)')CHAR1
      WRITE(51,'(A1)')CHAR2
      CLOSE(51)
C
      STOP ' '
      END      
