$STORAGE:2
      SUBROUTINE BGNQCMAP(XLONMN,XLATMN,XLONMX,XLATMX,XKWMX,YKWMX)
C
C       ** OBJECTIVE:  INITIAL MAP PROJECTION AND SCREEN COORDINATES FOR
C                      AREA-QC MAPS.  THIS ROUTINE IS CALLED BY BOTH BUILDMAP
C                      AND DRWMAP (IN AQC12).  USE OF THIS ROUTINE INSURES THAT
C                      THE COORDINATES IN EFFECT AT THE TIME THE MAP BACKGROUND
C                      IS SAVED ARE THE SAME AS THOSE IN EFFECT WHEN THE MAP
C                      BACKGROUND IS RESTORED.
C       ** INPUT:
C             XLONMN,XLATMN....MINIMUN LAT/LON COORDINATES OF MAP
C             XLONMX,XLATMX....MAXIMUM LAT/LON COORDINATES OF MAP
C       ** OUTPUT:        
C             XKWMX............MAXIMUM X-SCALE VALUE IN THE WORLD
C                              COORDINATE SYSTEM USED BY K.W. ROUTINES
C             YKWMX............MAXIMUM Y-SCALE VALUE IN THE WORLD
C                              COORDINATE SYSTEM USED BY K.W. ROUTINES
C
C       ** SET SCREEN COORDINATES
C
      MAPPRJ = 1
      CTRLON = 0.
      GANWLF = 0.025
      GANWRT = 0.975
      GANWBT = 0.025
      GANWTP = 0.975
C
      CALL KSETUP(MAPPRJ,GANWLF,GANWRT,GANWBT,GANWTP,
     +     XPLTSZ,YPLTSZ,XPLTCEN,YPLTCEN,XKWMX,YKWMX) 
C
      CALL KWAREA (XPLTSZ,YPLTSZ,XPLTCEN,YPLTCEN,
     +             XLONMN,XLATMN,XLONMX,XLATMX,CTRLON)
      RETURN
      END
