$STORAGE:2
      SUBROUTINE INITPV(VPNDLF,VPNDRT,VPNDBT,VPNDTP,IPAL,KLRBKGN)
C
C       ** OBJECTIVE:  INITIAL SETUP FOR PLOT:  PALETTE,BACKGROUND COLOR
C                      INITIAL VIEWPORT
C       ** INPUT:
C             VPNDLF.....X-COORDINATE OF LEFT SIDE OF VIEWPORT
C             VPNDRT.....X-COORDINATE OF RIGHT SIDE OF VIEWPORT
C             VPNDBT.....Y-COORDINATE OF BOTTOM OF VIEWPORT
C             VPNDTP.....Y-COORDINATE OF TOP OF VIEWPORT
C             IPAL.......PALETTE NUMBER
C             KLRBKGN....BACKGROUND COLOR   
C
C       ** NOTE:  VIEWPORT COORDINATES ARE SPECIFIED AS NORMALIZED DEVICE
C                 COORDINATES   
C
C       ** SET PALETTE AND BACKGROUND COLOR; INITIAL TEXT CURSOR TO CURRENT
C          BACKGROUND COLOR
C
      CALL SETIPAL(KLRBKGN,IPAL)      
      CALL INITTC(1,1,KLRBKGN)      
C
C       ** SET VIEWPORT    
C
      CALL SETVIE(VPNDLF,VPNDTP,VPNDRT,VPNDBT,-1,KLRBKGN)      
      RETURN
      END
