$STORAGE:2
      SUBROUTINE MAPMAN(XWIN,YWIN,PALETTE,PALDEF,
     +                  MPCODE,MPLNTHK,MPLNTYP)
C
      REAL*4     XWIN(*),YWIN(*)
      INTEGER *2 PALETTE,PALDEF(16,*),MPCODE(5),MPLNTHK,MPLNTYP
C
      INTEGER*2 WINSTAT,HELPLVL        
      CHARACTER *2 INCHAR
C      
C       ** INITIAL WINDOW CONTROL VARIABLES;  WINSTAT IS SET TO DRAW MENU,
C          AND GET CHOICE; SCREEN IS NOT SAVED
C
      MENUNUM = 39
      HELPLVL = 39
      WINSTAT = 2
C
C       ** LOOP TO DISPLAY AND PROCESS MENU CHOICES
C      
   70 CONTINUE
      CALL GRAFMNU(WINSTAT,MENUNUM,XWIN(1),YWIN(1),HELPLVL,INCHAR)
      IF (INCHAR.EQ.'ES') THEN
C
C          .. ESC SAVES CURRENT DEFINITION AND EXITS
         GO TO 100
      ELSE IF (INCHAR.EQ.'1 ') THEN
C
C          .. CHOOSE MAP DETAIL
         CALL MPLIN(XWIN(2),YWIN(2),MPCODE)
      ELSE IF (INCHAR.EQ.'2 ') THEN
C
C          .. CHOOSE MAP LINE COLOR      
         CALL MPCLR(XWIN(2),YWIN(2),PALETTE,PALDEF,MPCODE)
      ELSE IF (INCHAR.EQ.'3 ') THEN
C
C          .. CHOOSE MAP LINE PATTERN     
         ICNTRL=2
         CALL LNATRIB(ICNTRL,XWIN(2),YWIN(2),MPLNTYP) 
      ELSE 
C
C          .. CHOOSE MAP LINE THICKNESS
         ICNTRL=1
         CALL LNATRIB(ICNTRL,XWIN(2),YWIN(2),MPLNTHK) 
      ENDIF
C
C       ** RETURN TO GET ANOTHER MENU CHOICE; MENU WILL NOT BE REDRAWN
C      
      WINSTAT = 3
      GO TO 70     
C
C       ** END OF THIS MENU; REMOVE MENU FROM SCREEN
C      
  100 CONTINUE
      WINSTAT = 0
      CALL GRAFMNU(WINSTAT,MENUNUM,XWIN(1),YWIN(1),HELPLVL,INCHAR)
      RETURN
      END
            