$STORAGE:2

      SUBROUTINE PICKFONT(IFONT,XWIN,YWIN,RTNCODE)
C
C   ROUTINE TO POP-UP A WINDOW AND ALLOW USER TO PICK ONE OF THE HALO
C   FONTS AVAILABLE TO CLICOM GRAPHICS.
C
C        IFONT.......INPUT  - CURRENT CLICOM FONT NUMBER
C                    OUTPUT - FONT SELECTED
C        XWIN,YWIN...INPUT/OUTPUT - LOWER LEFT CORNER OF WINDOW IN
C                    NORMALIZED DEVICE COORDS.
C        RTNCODE..OUTPUT - = '0' IF FONT HAS BEEN SELECTED
C                          = '1' IF USER HAS DECIDED TO IGNORE SELECTION
C                                AND KEEP THE OLD FONT.
C
      REAL XWIN,YWIN,HEIGHT,ASP,CURSSTEP,MOUSSTEP
      INTEGER*2 IFONT,LINE,FILL,PATH,PRVFONT
      CHARACTER*1 RTNCODE
C
      CHARACTER*2 INCHAR
      CHARACTER* 20 SAMPLE
      DATA SAMPLE /'^ABCDEGabcdeg135^'/
C
C   DETERMINE AND SAVE THE CURRENT TEXT ATTRIBUTES, XOR STATUS,
C   AND CROSS-HAIR CURSOR LOCATION.
C
      CALL SETLNW(1)
      CALL INQTEX(JHEIGHT,JWIDTH,JFG,JBG,JPATH,JMODE)
      CALL INQSTE(HEIGHT,ASP,LINE,FILL,PATH)
      CALL INQXOR(IXOR)
      CALL INQASP(DEVASP)
      ASPTXT = 1.1 / DEVASP
C
C   SET UP WINDOW FOR DISPLAY OF THE SAMPLE TEXT FONTS.  POP IT UP AT THE 
C   NORMALIZED DEVICE COORDS PASSED AND HAVE IT TAKE AN AREA OF
C   33% OF X AND 50% OF Y. 
C    
C      IF (ICNTRL.EQ.2) THEN
C         GO TO 150
C      END IF
      CALL INQHCU(XOLD,YOLD,IDUMMY)
      XWIN2 = XWIN + .33
      YWIN1 = YWIN - .50
      CALL GRAFWIN(1,XWIN,YWIN1,XWIN2,YWIN)
C
C   FIND CURRENT WORLD COORDS AND SET CURSOR STEP TO ONE 1000TH OF
C   THE WORLD AND MOUSE STEP TO 1 50TH.
C
      CALL INQWOR(XLOW,YLOW,XHIGH,YHIGH)
      CURSSTEP = (YHIGH - YLOW) / 1000.
      MOUSSTEP = (YHIGH - YLOW) / 50.
      YCENTER = (YHIGH - YLOW) / 2.0
      YHEIGHT = (YHIGH - YLOW) / 9
      XWIDTH = XHIGH - XLOW
C      
C   DISPLAY THE SAMPLE TEXT 
C
      DO 100 I = 1,9
         YPOS = YHIGH - I*YHEIGHT
         CALL MOVTCA(XLOW+XWIDTH*.05,YPOS)
         CALL DELTCU( )
         CALL SETCFON(I)
         CALL SETSTE(YHEIGHT*.9,ASPTXT,0)
         CALL SETSTC(0,0)
         CALL STEXT(SAMPLE)
100   CONTINUE         
C
C   SETUP SELECTION HIGHLIGHT
C
      CALL SETXOR(1)
      JFONT = IFONT
      PRVFONT = JFONT
      YCOORD = YHIGH - JFONT*YHEIGHT
      CALL SETCOL(1)
      CALL SETHAT(1)
      CALL BAR(XLOW,YCOORD,XHIGH,YCOORD+YHEIGHT)
C
C   SET LOCATOR POSITION, IF ANY, AND READ IT BACK TO ACCOUNT FOR ROUND OFF
C
C      XPOS = XLOW
C      YPOS = YCENTER
C      CALL ORGLOC(XPOS,YPOS)
C      CALL RDLOC(XLOW,YCENTER,INCHAR,RTNCODE)
C      XPOS = XLOW
C      YPOS = YCENTER
      CALL RDLOC(XPOS,YPOS,INCHAR,RTNCODE)
      XPOS = XLOW
      YPOS = YCENTER
      CALL ORGLOC(XLOW,YCENTER)
      CALL RDLOC(XPOS,YPOS,INCHAR,RTNCODE)
      IF (RTNCODE .EQ. '1') THEN
         YCENTER = YPOS
      ENDIF
C
C   ALLOW USER TO MOVE HIGHLIGHT TO SELECT THE FONT WANTED 
C
120   CONTINUE      
         CALL RDLOC(XPOS,YPOS,INCHAR,RTNCODE)
         IF (INCHAR.EQ.'RE') THEN
            RTNCODE = '0'
            GO TO 150
         ELSE IF(INCHAR.EQ.'4F') THEN
            RTNCODE = '1'
            GO TO 150
         END IF         
C
C    IF A NEW SELECTION IS MADE CHANGE FONT.
C
         IF (RTNCODE.EQ.'1') THEN
            YFACTOR = MOUSSTEP
         ELSE
            YFACTOR = CURSSTEP
         END IF
         IF (YPOS.NE.YCENTER) THEN
            IF (YPOS.GT.YCENTER+YFACTOR) THEN
               JFONT = JFONT - 1
               XPOS = XLOW
               YPOS = YCENTER
               CALL ORGLOC(XPOS,YPOS)
            ELSE IF (YPOS.LT.YCENTER-YFACTOR) THEN
               JFONT = JFONT + 1
               XPOS = XLOW
               YPOS = YCENTER
               CALL ORGLOC(XPOS,YPOS)
            END IF
            IF (JFONT.GT.9) THEN
               JFONT = 9
            ELSE IF (JFONT.LT.1) THEN
               JFONT = 1
            END IF
         END IF
         IF (JFONT.NE.PRVFONT) THEN
            YCOORD = YHIGH - PRVFONT*YHEIGHT
            CALL BAR(XLOW,YCOORD,XHIGH,YCOORD+YHEIGHT)
            YCOORD = YHIGH - JFONT*YHEIGHT
            CALL BAR(XLOW,YCOORD,XHIGH,YCOORD+YHEIGHT)
            PRVFONT = JFONT
         END IF
         GO TO 120
C
C   RESTORE THE WINDOW, SET THE FONT TO THE ONE WANTED AND EXIT.
C
150   CONTINUE
      CALL SETXOR(IXOR)
      CALL GRAFWIN(0,XWIN,YWIN1,XWIN2,YWIN)
      IF (RTNCODE.EQ.'0') THEN
         IFONT = JFONT
      END IF
      CALL SETCFON(IFONT)
      CALL SETSTE(HEIGHT,ASP,PATH)
      CALL SETTCL(JFG,JBG)
      CALL SETSTC(LINE,FILL)
      RETURN
      END
