$STORAGE:2
      SUBROUTINE SKTDIM2(RVAL,MXDATROW,NPLTROW,QCTFLG,RTNCODE)
C------------------------------------------------------------------------------
C     INTERMEDIATE ROUTINE TO CONVERT RVAL FROM A ONE TO TWO DIMENSIONAL 
C     ARRAY.  SKEWT MUST BE CALLED WITH INDIVIDUAL ARGUMENTS PASSED IN ORDER
C     TO COORDINATE ITS USE IN GRAPHICS WITH THAT IN AREAQC      
C
C     INPUT ARGUMENTS:
C
C     RVAL      REAL ARRAY   ONE DIMENSIONAL ARRAY WITH SOUNDING PRESSURES,
C                            HEIGHTS, TEMPERATURES, DEW POINT DEPRESSIONS,
C                            WIND DIRECTION, WIND SPEED 
C     MXDATROW  INT2         MAXIMUM NUMBER OF ROWS IN ARRAY RVAL
C     NPLTROW   INT2         NUMBER OF SOUNDING LEVELS INPUT
C     QCTFLG    CHAR ARRAY   SOUNDING QC FLAGS (C=ERROR, OTHERS OK)
C     RTNCODE   CHAR         FLAG TO INDICATE CALLING ROUTINE
C                            'G'= GRAPHICS  'Q'=AREAQC
C
C     OUTPUT ARGUMENTS:
C
C     RTNCODE   CHAR         RETURN STATUS: 0 = OK, 1 = QUIT VIA ESC-F4 KEY
C-----------------------------------------------------------------------------

      INTEGER*2   MXDATROW,NPLTROW
      REAL*4      RVAL(MXDATROW,*)
      CHARACTER*1 QCTFLG(*),RTNCODE
C
      CALL SKEWT(RVAL(1,1),RVAL(1,2),RVAL(1,3),RVAL(1,4),RVAL(1,5),
     +           RVAL(1,6),QCTFLG,NPLTROW,RTNCODE)
C
      RETURN
      END      
