$STORAGE:2
      PROGRAM TSTPAL
C
C       ** OBJECTIVE:  THE GRAPH MANAGER COMBINES THE GRAPH DEFINITION IN THE
C                      GDF FILE WITH THE DATA IN THE API FILE AND DISPLAYS THE
C                      RESULTANT GRAPH.  IT ALLOWS USERS TO TAILOR THE GRAPHS
C                      TO THEIR REQUIREMENTS.  USERS MODIFY THE GRAPHS BY
C                      SPECIFYING VALUES IN FORMS AND MANIPULATING GRAPHS
C                      DIRECTLY ON THE SCREEN.
C
$INCLUDE: 'GRFPARM.INC'
$INCLUDE: 'GRAFVAR.INC'
$INCLUDE: 'DATAVAL.INC'
$INCLUDE: 'CURRPLT.INC'
C
      INTEGER*2 HELPLVL,DATAOPT,NTTL,NOKD,LENMSG
      PARAMETER(NOKD=2)
      CHARACTER INCHAR*2, RTNCODE*1, RTNFLG*2
      CHARACTER*2 EXITOPT,OKOPT(NOKD)
      CHARACTER*1 TTLSAV(2)
      CHARACTER*28 GRAFNAME
      CHARACTER*14 MSGTXT
      CHARACTER*2 YESUP,YESLO
      LOGICAL PLTONSCR,FIRSTCALL
      DATA FIRSTCALL/.TRUE./
      DATA NTTL/1/
C       .. VALID OPTION FLAGS IN FILE DATACOM.CON
C          GO=RETURN FROM OPTMAN  ZZ=INITIAL CALL AFTER GRAFINIT      
      DATA OKOPT/'GO','ZZ'/
C       .. OPTION FLAG WRITTEN TO DATACOM.CON WHEN EXITING TO GRAFINIT
      DATA EXITOPT/'ZZ'/      
C
      IF (FIRSTCALL) THEN
         FIRSTCALL=.FALSE.
         CALL GETYN(1,2,YESUP,YESLO)
      ENDIF   
C
C       **  Open and read GRAPHICS.GDF file and store the values in the
C           GRAFVAR common block.
C
      CALL RDGRAF('GRAPHICS',ITYPE,NELEM,RTNCODE)
C
C       ** INITIAL GRAPHICS
C
      IF (RTNCODE.EQ.'0') THEN
C          .. NORMAL RETURN FROM RDGRAF -- DEFINE PALETTES
         CALL BGNHALO(1,PALETTE,PALDEF)
      ELSE
C          .. ERROR RETURN FROM RDGRAF -- USE DEFAULT PALETTES
         CALL BGNHALO(0,PALETTE,PALDEF)
         GO TO 900
      ENDIF      
C
C       ** OPEN AND READ DATACOM.CON FILE AND STORE CONSTANTS IN THE
C          DATAVAL COMMON BLOCK; CLOSE FILE
      CALL RDDCON(0,OKOPT,NOKD,INCHAR,RTNCODE)
      IF (RTNCODE.EQ.'2') THEN
C          .. ERROR IN OPENING FILE      
         GO TO 905        
      ENDIF
      MXDATROW = NROWDIM
      PLTONSCR=.FALSE.
C
C  Display the main menu 
C
C    1.RE_PLOT  2.NXT_PLOT  3.POS DATA  4.OUTPUT  5.COLORS  6.LABELS  
C    7.LINES    8.SIZE      9.DATA MGR    F1-Help   Esc-Exit
C
   20 CONTINUE
      HELPLVL=2
      XWIN=.1
      YWIN=.8
      CALL GRAFMNU(1,2,XWIN,YWIN,HELPLVL,INCHAR)
C      
      IF (INCHAR.EQ.'ES') THEN
C      
C          .. EXIT GRAFMAN 
            IFPFLG=-2
            IPSFLG=0
            IDCFLG=0
            ISTP=0
            INCHAR=EXITOPT
            GO TO 100
      ELSE IF (INCHAR.EQ.'5 ') THEN
C      
C          .. CHOOSE COLOR PALETTE AND ADJUST PALETTE COLORS      
         CALL CLRMAN(PALETTE,PALDEF)
      ENDIF   
      GO TO 20
C
  100 CONTINUE
      ITYPE = IOBSTYP
      ITEMP = 1
      CALL FINHALO
      STOP ' '
C
C       ** FATAL ERROR      
C
  900 CONTINUE
C          .. ERROR READING FILE: GRAPHICS.GDF  
         MSGN1=191
         MSGTXT='  GRAPHICS.GDF'
         LENMSG=14
         GO TO 990
  905 CONTINUE
C          .. ERROR READING FILE: DATACOM.CON  
         MSGN1=191
         MSGTXT='  DATACOM.CON'
         LENMSG=13
         GO TO 990
  910 CONTINUE
C          .. ERROR WRITING FILE: DATACOM.CON  
         MSGN1=192
         MSGTXT='  DATACOM.CON'
         LENMSG=13
         GO TO 990
  990 CONTINUE         
         MSGN2=202
         XWIN=.1
         YWIN=.95
         CALL GRAFNOTE(XWIN,YWIN,MSGN1,MSGN2,MSGTXT,LENMSG,INCHAR)
         INCHAR = EXITOPT
         CALL FINHALO
         CALL LOCATE(23,0,IERR)
         STOP 1
      END
