name: User story
description: Add a user story
title: "[User story]: "
labels: ["user-story"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to add this user story!
  - type: textarea
    id: user-story
    attributes:
      label: User story
      description: Also, why is this important?
      placeholder: What will the outcome be!
      value: "As a (CDMS user type), I want to (do something) so that (goal)."
    validations:
      required: true
  - type: input
    id: priority
    attributes:
      label: Priority
      description: How important is this [1 (low) - 5 (high)] ?
      placeholder: priority
      value: "3"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Please provide 1..n acceptance criteria to help further understand the requirement
      placeholder: Tell us what you see!
      value: "- [ ] Criteria 1"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Definition of done
      description: Predefined list of what done looks like
      options:
        - label: unit/functional tests added/updated
          required: false
        - label: documentation updated
          required: false
        - label: live demonstration provided
          required: false
  - type: textarea
    id: references
    attributes:
      label: References
      description: Please provide any additional information of links to extertnal references here.
      placeholder: references
      value: "WMO No. 1131, requirement 3.1.1.3 (Usage constraints)"
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
