        SUBROUTINE INTGPH
%NOLIST
%INCLUDE    '/SYS/INS/IOS.INS.FTN'
%INCLUDE    '/SYS/INS/ERROR.INS.FTN'
%INCLUDE    '/SYS/INS/SIO.INS.FTN'
%INCLUDE    '/SYS/INS/PGM.INS.FTN'
%INCLUDE    '/SYS/INS/VFMT.INS.FTN'
%LIST
       INTEGER*4  STATUS
C
       CALL GRAPINT  
       CALL CLRTAB 
       CALL JGCOLOR(-99)
       CALL KWCLEAR(3,STATUS)
       CALL KWCOLOR(16,STATUS)
c
       RETURN
       END
