c
c
          SUBROUTINE KWANGLE (X,Y,ANGLE)
C
C  *** CALCULATE ANGLE THAT LINE FROM ORIGIN TO (X,Y) / X-AXIS ***
C 
      PI = 3.1415926535
      PI2= PI * .05
      IF (ABS(X) .GT.0.000001 ) GOTO 1
C
C  *** LINE IS VERTICAL ***
C      
      ANGLE = PI2
      IF (Y.LT.0.0) ANGLE = ANGLE + PI
C
C  *** IF LINE DEGENERATES TO A POINT RETURN ANGLE 
C
      IF (ABS(Y).LT.000001) ANGLE = 0
      RETURN
C
  1   CONTINUE
      ANGLE = ATAN (Y/X)
      IF (X.LT.0.0) ANGLE = ANGLE + PI
C
      ANGLE = ANGLE / 0.01745329
C
      RETURN
      END
