      SUBROUTINE SCLCON(XIN,YIN,XOUT,YOUT)
      COMMON /KWSCLE1/  SCNSCF , XSCNMV , YSCNMV ,SCNSCL
C
      XOUT = (XIN * SCNSCF - XSCNMV)
      YOUT = (YIN * SCNSCF - YSCNMV)
C
      RETURN
      END
