$STORAGE:2
$DEBUG
C
C      PROGRAM MDFRMIDX
C
C   ROUTINE TO UPDATE THE FORM INDEX FILE (FTNFORM.IDX).  THIS PROGRAM ONLY
C   USE FOR INSTATLLATION THE "KEY-ENTRY FILES MERGER".
C   THE DRIVE LETTER OF HARD DISK WHERE THE CLICOM AND CLIGRAF DIRECTORIES
C   WAS LOCATED MUST BE INCLUDED ON THE COMMAND LINE CALLING THIS ROUTINE.
C
C           EXAMPLE:    MDFRMIDX  C   C
C
C      PASSED PARAMTER ARE:
C            %1 = CLICOM DRIVE
C            %2 = CLIGRAF DRIVE
C
C   ** NOTE: 
C           IF THE PARAMETERS ARE MISSING, IT SETS ERRORLEVEL 2.
C           IF THE FILE (FTNFORM.IDX) IS NOT FOUND, IT SETS ERRORLEVEL 1.
C
C   LOCAL VARIABLES 
C
      INTERFACE TO SUBROUTINE CMDLIN2(ADDRES,LENGTH,RESULT)
      INTEGER*4 ADDRES[VALUE],LENGTH[VALUE]
      CHARACTER*1 RESULT
      END
C
      PROGRAM MDFRMIDX
C
      CHARACTER*1  CHRRTN,LNFEED,CLICDRV,CLIGDRV
      CHARACTER*8  FORMNAME(4)
      CHARACTER*32 FORMDESC(4)
      CHARACTER*43 INREC,RESULT,RECFRM(4)
      CHARACTER*78 MSG,FORMIDX
      INTEGER*2    IREC
      INTEGER*4    PSP,PSPNCHR,OFFSET
      LOGICAL      FRMEXIST(4),UPDFORM
      DATA         BLANK /'        '/
C
C   FOLLOWING STATEMENT REQUIRED FOR FORTRAN 3.3 - NOT ALLOWED IN FTN 4
C      EXTERNAL LDDATA
C
C   LOCATE SEGMENTED ADDRESS OF THE BEGINNING OF THIS PROGRAM
C
      OFFSET = #00100000
      PSP = LOCFAR(MDFRMIDX)
C
C   COMPUTE THE BEGINNING OF THE PROGRAM SEGMENT PREFIX (PSP)
C
      PSP = (PSP - MOD(PSP,#10000)) - OFFSET 
C
C   LOCATE POSITION OF COMMAND PARAMTERS WITHIN THE PSP
C
      PSPNCHR = PSP + #80
      PSP = PSP + #81
C
C   PASS THE ADDRESS OF THE COMMAND PARAMTERS TO CMDLIN WHICH DECODES
C      THE COMMAND AND RETURNS IT AS RESULT.
C
      RESULT = '             '
      CALL CMDLIN2(PSP,PSPNCHR,RESULT)
      IF (RESULT.EQ.' ') THEN
         CALL CLS
         CALL BEEP
         CALL LOCATE(14,0,IERR)
         CALL POSLIN(IR,IC)
         MSG = '   This program uses to install the "KEY-ENTRY'
     +        //' FILES MERGER" only.'
         IR = IR + 1
         CALL SCRNMSGI(MSG,IR,14)
         MSG = '   USAGE is: MDFRMIDX  [drive letter]  [drive letter]'
         IR = IR + 2
         CALL SCRNMSGI(MSG,IR,14)
         MSG = '   For example:   MDFRMIDX  C   C '
         IR = IR + 2
         CALL SCRNMSGI(MSG,IR,14)
         CALL LOCATE(24,0,IERR)
         STOP 2
      END IF
C
C   PULL THE COMMANDS OUT OF THE RESULT:
C     CLICDRV -- CLICOM DRIVE
C     CLIGDRV -- CLIGRAF DRIVE
C
      CLICDRV = RESULT(1:1)
      DO 50 N = 2,42
         IF (RESULT(N:N).NE.' ') THEN
            IF (RESULT(N:N).EQ.':'.OR.RESULT(N:N).EQ.';') THEN
               CLIGDRV = RESULT(N-1:N-1)
            ELSE
               CLIGDRV = RESULT(N:N)
            END IF
         END IF
 50   CONTINUE
C
C     GET FORM NAMES AND FTNFORM.IDX FILE
C
      CHRRTN = CHAR(13)
      LNFEED = CHAR(10)
      DO 60 I = 1,4
         RECFRM(I) = BLANK
         FRMEXIST(I) = .FALSE.
 60   CONTINUE
      UPDFORM = .FALSE.
      FORMNAME(1) = 'PRNLSTWF' 
      FORMDESC(1) = 'Select key-entry file'
      FORMNAME(2) = 'MRGDUPID' 
      FORMDESC(2) = 'Duplicate ID in key-entry file'
      FORMNAME(3) = 'MRGTWFIO' 
      FORMDESC(3) = 'Select key-entry files to merge'
      FORMNAME(4) = 'LSTKEFRM' 
      FORMDESC(4) = 'Select drive to list KE forms'
      FORMIDX     = CLICDRV//':\CLICOM\FORM\FTNFORM.IDX'
C
C     OPEN THE FORTRAN FORM DEFINITION INDEX FILE
C
      OPEN (51,FILE=FORMIDX,STATUS='OLD',FORM='BINARY',
     +      ACCESS='DIRECT',RECL=43,IOSTAT=IOCHK)
      IF (IOCHK.NE.0) THEN
         STOP 1
      END IF
C
C     UPDATE THE FORTRAN FORM DEFINITION INDEX FILE
C
      DO 155 I = 1,9999
         IREC = I
         READ(51,REC=I,ERR=160) INREC
         IF (INREC(1:8).EQ.FORMNAME(1)) THEN
            FRMEXIST(1)  = .TRUE.
            UPDFORM = .TRUE.
         ELSE IF (INREC(1:8).EQ.FORMNAME(2)) THEN
            FRMEXIST(2)  = .TRUE.
            UPDFORM = .TRUE.
         ELSE IF (INREC(1:8).EQ.FORMNAME(3)) THEN
            FRMEXIST(3)  = .TRUE.
            UPDFORM = .TRUE.
         ELSE IF (INREC(1:8).EQ.FORMNAME(4)) THEN
            FRMEXIST(4)  = .TRUE.
            UPDFORM = .TRUE.
         END IF
 155  CONTINUE
 160  CONTINUE
      DO 170 I = 1, 4
         WRITE(RECFRM(I),'(A8,1X,A32,2A1)') FORMNAME(I),FORMDESC(I),
     +         CHRRTN,LNFEED
 170  CONTINUE
C
      IF (UPDFORM) THEN
         DO 220 J = 1,4
            IF (.NOT.FRMEXIST(J)) THEN
               WRITE(51,REC=IREC) RECFRM(J)
               IREC = IREC + 1
            END IF
 220     CONTINUE
      ELSE
         DO 230 K = 1,4
            WRITE(51,REC=IREC) RECFRM(K)
            IREC = IREC + 1
 230     CONTINUE
      END IF
      CLOSE (51)
C
      STOP ' '
      END
