$STORAGE:2
$DEBUG
C
C      PROGRAM MDTWFMNU
C
C   ROUTINE TO MODIFY THE USER MENUS (USERMENU.DEF) FILE.
C   THIS PROGRAM ONLY USE FOR INSTATLLATION THE "KEY-ENTRY FILE MERGER'.
C   THE DRIVE LETTER OF HARD DISK WHERE THE CLICOM AND CLIGRAF DIRECTORIES
C   WAS LOCATED MUST BE INCLUDED ON THE COMMAND LINE CALLING THIS ROUTINE.
C
C           EXAMPLE:    MDTWFMNU  C   C
C
C      PASSED PARAMTER ARE:
C            %1 = CLICOM DRIVE
C            %2 = CLIGRAF DRIVE
C
C   ** NOTE: 
C           IF THE FILE (USERMENU.DEF) IS NOT FOUND, IT SETS ERRORLEVEL 1.
C           IF THE PARAMETERS ARE MISSING, IT SETS ERRORLEVEL 2.
C           IF THE FILE (MRGTWF?.MNU) IS NOT FOUND, IT SETS ERRORLEVEL 3.
C           OTHERWISE, IT SETS ERRORLEVEL 0.
C
C   LOCAL VARIABLES 
C
      INTERFACE TO SUBROUTINE CMDLIN2(ADDRES,LENGTH,RESULT)
      INTEGER*4 ADDRES[VALUE],LENGTH[VALUE]
      CHARACTER*1 RESULT
      END
C
      PROGRAM MDTWFMNU
C
      PARAMETER    (MAXCHOICE=16) 
      INTEGER*2    WIDTH,NUMCHOICE,FGCOLOR,BGCOLOR,HDRFGC,HDRBGC,
     +             TLENGTH,CLENGTH
      INTEGER*2    WDTH,FGCOL,BGCOL,TLNTH,CLNTH,HBGC,HFGC
      INTEGER*4    PSP,PSPNCHR,OFFSET
      CHARACTER*80 MSG
      CHARACTER*60 TITLE,TTLE
      CHARACTER*32 CHOICE(MAXCHOICE),CHCE(MAXCHOICE)
      CHARACTER*42 MENUFILE(2),USERFILE,RESULT
      CHARACTER*12 INNAME,BLANK,INNME,MENUNAME(2)
      CHARACTER*1  BORDER,DELMARK,BRDR,CLICDRV,CLIGDRV,DELMK
      LOGICAL      NEWMENU,USERERR,MENUSERR
      DATA         BLANK /'        '/
C
C   FOLLOWING STATEMENT REQUIRED FOR FORTRAN 3.3 - NOT ALLOWED IN FTN 4
c      EXTERNAL LDDATA
C
C   LOCATE SEGMENTED ADDRESS OF THE BEGINNING OF THIS PROGRAM
C
      OFFSET = #00100000
      PSP = LOCFAR(MDTWFMNU)
C
C   COMPUTE THE BEGINNING OF THE PROGRAM SEGMENT PREFIX (PSP)
C
      PSP = (PSP - MOD(PSP,#10000)) - OFFSET 
C
C   LOCATE POSITION OF COMMAND PARAMTERS WITHIN THE PSP
C
      PSPNCHR = PSP + #80
      PSP = PSP + #81
C
C   PASS THE ADDRESS OF THE COMMAND PARAMTERS TO CMDLIN WHICH DECODES
C      THE COMMAND AND RETURNS IT AS RESULT.
C
      RESULT = ' '
      CALL CMDLIN2(PSP,PSPNCHR,RESULT)
      IF (RESULT.EQ.' ') THEN
         CALL CLS
         CALL BEEP
         CALL LOCATE(14,0,IERR)
         CALL POSLIN(IR,IC)
         MSG = '   This program uses to install the "KEY-ENTRY'
     +        //' FILES MERGER" only.'
         IR = IR + 1
         CALL SCRNMSGI(MSG,IR,14)
         MSG = '   USAGE is: MDTWFMNU  [drive letter]  [drive letter]'
         IR = IR + 2
         CALL SCRNMSGI(MSG,IR,14)
         MSG = '   For example:   MDTWFMNU  C   C '
         IR = IR + 2
         CALL SCRNMSGI(MSG,IR,14)
         CALL LOCATE(24,0,IERR)
         STOP 2
      END IF
C
C   PULL THE COMMANDS OUT OF THE RESULT:
C     CLICDRV -- CLICOM DRIVE
C     CLIGDRV -- CLIGRAF DRIVE
C
      CLICDRV = RESULT(1:1)
      DO 50 N = 2,42
         IF (RESULT(N:N).NE.' ') THEN
            IF (RESULT(N:N).EQ.':'.OR.RESULT(N:N).EQ.';') THEN
               CLIGDRV = RESULT(N-1:N-1)
            ELSE
               CLIGDRV = RESULT(N:N)
            END IF
         END IF
 50   CONTINUE
C
C     GET MENUS NAME AND MENUS FILES
C
      USERERR     = .FALSE.
      MENUSERR    = .FALSE.
      MENUFILE(1) = 'C:\MRGTWF1.MNU'
      MENUFILE(2) = 'C:\MRGTWF2.MNU'
      MENUNAME(1) = 'LIST/MRG-TWF' 
      MENUNAME(2) = 'KE-OUTPUT   ' 
      USERFILE    = CLICDRV//':\CLICOM\FORM\USERMENU.DEF'
C
C   OPEN THE MENU FILE FOR NON-SHARED WRITE ACCESS
C
      OPEN (14,FILE=USERFILE,STATUS='OLD',ACCESS='DIRECT'
     +    ,RECL=602,IOSTAT=IOCHK)
      IF(IOCHK.NE.0) THEN
         USERERR = .TRUE.
         GO TO 300
      END IF   
C
      DO 250 K = 1,2
C
C     INITIALIZE FORM VARIABLES
C
      WIDTH = 0
      TITLE = BLANK
      FGCOLOR = 14
      BGCOLOR = 0
      HDRFGC = 15
      HDRBGC = 1
      DO 100 I1 = 1,MAXCHOICE
         CHOICE(I1) = BLANK
 100  CONTINUE
C
C    INSTALL USER MENUS
C
      OPEN (66,FILE=MENUFILE(K),STATUS='OLD',ACCESS='DIRECT'
     +       ,RECL=602,IOSTAT=IOCHK)
      IF(IOCHK.NE.0) THEN
         MENUSERR = .TRUE.
         GO TO 300
      END IF
C
C     READ THE MENU DEFINITION
C
       READ(66,REC=1) DELMARK,INNAME,TITLE,BORDER,
     +       (CHOICE(J),J=1,MAXCHOICE),WIDTH,NUMCHOICE,
     +       HDRFGC,HDRBGC,FGCOLOR,BGCOLOR,TLENGTH,CLENGTH
C
C     DETERMINE IF THE MENU ALREADY EXISTS IN USERMENU.DEF
C
      NEWMENU = .TRUE.
      DO 150 IREC = 1,999
         READ(14,REC=IREC,ERR=170) DELMK,INNME,TTLE,BRDR
     +       ,(CHCE(J),J=1,MAXCHOICE),WDTH,NMCHCE
     +       ,HFGC,HBGC,FGCOL,BGCOL,TLNTH,CLNTH
         IF (DELMK.NE.'*' .AND. INNME.EQ.MENUNAME(K)) THEN 
C             .. MENU NAME EXISTS
            NEWMENU = .FALSE.
            GO TO 250
         END IF
  150 CONTINUE
  170 CONTINUE
      IF (NEWMENU) THEN
C
C             FIND NEXT EMPTY RECORD         
C
         DO 200 I = 1,999
            IREC = I
            READ(14,REC=I,ERR=220) DELMARK
            IF (DELMARK.EQ.'*') THEN
               GO TO 220
            END IF  
  200    CONTINUE
  220 CONTINUE
      MNUREC = IREC
      DELMARK = ' '
      WRITE(14,REC=MNUREC) DELMARK,MENUNAME(K),TITLE,BORDER
     +       ,(CHOICE(J),J=1,MAXCHOICE),WIDTH,NUMCHOICE
     +       ,HDRFGC,HDRBGC,FGCOLOR,BGCOLOR,TLENGTH,CLENGTH
      ENDIF      
  250 CONTINUE
C
  300 CONTINUE
      CLOSE(14)
      CLOSE(66)
      IF (USERERR) THEN
         STOP 1
      ELSE IF (MENUSERR) THEN
         STOP 3
      END IF
      STOP ' '
      END
