$STORAGE:2
      PROGRAM LOGON1
C
C   ROUTINE TO ASK THE CURRENT USER FOR HIS NAME, CHECK IT AGAINST
C   THE VALID USER NAMES AND WRITE THE USERS AUTHORITY TO THE
C   DOS ENVIRONMENT.
C
      CHARACTER*1  INCHAR
      CHARACTER*4  LEVEL,HLDLVL(3)
      CHARACTER*2 RTNFLAG
      CHARACTER*8 ERASE
      CHARACTER*12 USER,PASWRD
      CHARACTER*20 COMMAND
      CHARACTER*72 MESSAGE
      DATA HLDLVL /'LOW','MED','HI'/
C
      INCHAR = CHAR(27)
      ERASE(1:1) = INCHAR
      ERASE(2:5) = '[40D'
      ERASE(6:6) = INCHAR
      ERASE(7:8) = '[K'
      CALL GETMSG(222,MESSAGE)
      CALL GETMSG(999,MESSAGE)
C
C  DETERMINE THE LENGTH OF THE USER-ID PROMPT
C
      DO 10 I = 24,1,-1
         IF (MESSAGE(I:I).NE.' ') THEN
             LENGTH = I+1
             GO TO 15
         END IF
10    CONTINUE
15    CONTINUE    

C
C  READ THE NAME OF THE CURRENT USER
C
      CALL SETMOD(3,IERR)
   20 CONTINUE
      USER = ' '
      JCOL = 22 + LENGTH + 16
      CALL DRWBOX(22,8,JCOL,12,2,11,0)      
      CALL LOCATE(10,24,IERR)
      CALL WRTSTR(MESSAGE,LENGTH,14,0)
      CALL GETSTR(9,USER,12,15,1,RTNFLAG)
      IF (RTNFLAG.EQ.'4F') THEN
         GO TO 20
      END IF
C
C   CHECK THE NAME AGAINST VALID PASSWORDS 
C
      OPEN (4,FILE='P:\DATA\USERS.DAT',STATUS='OLD'
     +     ,FORM='UNFORMATTED')
      DO 100 I = 1,99
         CALL RDUSER(PASWRD,ILEVEL,IEOF)
         IF (IEOF.NE.0) THEN
            GO TO 120
         END IF 
C
C   IF NAME IS VALID, WRITE THE AUTHORITY TO THE OUTPUT BATCH FILE
C
         IF (USER.EQ.PASWRD) THEN
            LEVEL = HLDLVL(ILEVEL)
            CLOSE(4)
            OPEN (61,FILE='P:\BATCH\LOGON2.BAT',STATUS='UNKNOWN'
     +          ,FORM='FORMATTED')
   50       CONTINUE
            COMMAND = 'SET $X=  '
            COMMAND(8:10) = LEVEL
            COMMAND(11:18) = ERASE
            WRITE(61,'(A20)') COMMAND
            WRITE(61,'(A21)') 'P:\BATCH\DLOGON2'
            CLOSE(61)
            CALL CLS
            STOP ' '
         END IF
  100 CONTINUE
  120 CONTINUE
      CALL LOCATE(12,1,IERR)
      CALL WRTSTR('Unknown user',12,14,0)
      REWIND (4)
      GO TO 20
      END         
           