$STORAGE:2
      SUBROUTINE PCTRL(IOPT,RTNCODE)
C
C       ** OBJECTIVE:  DRAW THE GRAPH USING THE CURRENT VALUES IN THE
C                      DEFINITION FILE.  ROUTINES STOP DRAWING
C                      AND RETURN IF USER PRESSES ESC.
C
C       ** NOTE:       THIS VERSION OF ROUTINE PCTRL IS CONTAINED IN FILE
C                      PCTRL2. IT IS USED IN GRFMN2.EXE TO PLOT MAPS. 
C       ** INPUT:
C            IOPT......GRAPH OPTION FLAG THAT CONTROLS SELECTION OF DATA
C                      THAT WILL BE PLOTTED AND PLOT CONTROLS
C                     -1=REDRAW CURRENT PLOT -- REGRID DATA
C                      0=REDRAW CURRENT PLOT -- DO NOT REGRID DATA
C                      1=NEXT PLOT IN CURRENT DATA FRAME
C                      2=NEW DATA FRAME
C                      4=REDRAW CURRENT SCREEN FOR PRINTING
C       ** OUTPUT:
C            RTNCODE...ONE CHARACTER ERROR FLAG
C                      '0'=NORMAL EXIT
C                      '1'=EXIT USING ESC OR F4
C                      '0'=NORMAL EXIT
C                      '1'=EXIT USING ESC OR F4
C                      '2'=NO MORE PLOTS IN DATASET
C                      '3'=PCTRL2 CALLED WITH PLOT TYPE = TIMESERIES(1),
C                          SKEWT(3), OR WINDROSE(4)
C                      '4'=RESERVED FOR PCTRL134 
C                      '5'=NO DATA AVAILABLE FOR CURRENT PLOT
C                      '6'=RESERVED FOR WINDROSE 
C                      '7'=RESERVED FOR SKEWT
C
      INTEGER*2 IOPT
      CHARACTER*1 RTNCODE
C
$INCLUDE: 'GRFPARM.INC'
$INCLUDE: 'GRAFVAR.INC'
$INCLUDE: 'DATAVAL.INC'
C **REVISION (JML 8-02-93)    ADD COMMON FRMPOS
$INCLUDE: 'FRMPOS.INC'
C
      IF (IGRAPH.EQ.2) THEN
C
C          .. PLOT CONTOUR AND MAP      
         CALL INITPV(VPNDLF,VPNDRT,VPNDBT,VPNDTP,PALETTE,BKGNCLR)
C         CALL CONMAP(IOPT,CVAL,RVAL,I1VAL,MXDATROW,NPLTROW,RTNCODE)
C **REVISION (JML 8-02-93)
         IDX = LORFRM
         CALL CONMAP(IOPT,CVAL(IDX),RVAL(IDX),I1VAL,MXDATROW,NPLTROW,
     +               RTNCODE)
      ELSE 
C
C          .. ERROR: TIMESERIES, SKEWT, OR WINDROSE WAS REQUESTED
         RTNCODE='3'
      ENDIF
C
      RETURN
      END      
