$STORAGE:2
      SUBROUTINE CHKQVAL(IELEM,ILINE,HLDFLAG,IRTN,RTNFLAG)
C
C   ROUTINE TO ASK THE USER WHAT ACTION SHOULD BE TAKEN FOR THIS
C     QUESTIONABLE FIELD - AND THEN TAKE THE ACTION
C
$INCLUDE: 'VAL1.INC'
C
      CHARACTER*1 HLDFLAG,CHOICE,BIGA,SMALLE
      CHARACTER*2 RTNFLAG
      CHARACTER*6 SPACES
C
      INTEGER*2 IROW,ICOL
C
      DATA BIGA,SMALLE /'A','e'/
C
      IRTN = 0
      SPACES = '      '
C
      CALL POSLIN(IROW,ICOL)
      CALL QCCHOICE(IROW,ICOL,CHOICE,RTNFLAG)
      IF (CHOICE.EQ.'1')THEN
         FLAGARRAY(IELEM,ILINE,1) = SMALLE
         HLDFLAG = FLAGARRAY(IELEM,ILINE,1)
         CALL WRTVAL(VALARRAY(IELEM,ILINE),HLDFLAG,IROW,ICOL)
         IELEM = IELEM + 1
         IRTN = 1
      ELSE IF (CHOICE.EQ.'2')THEN
         VALARRAY(IELEM,ILINE)(6:6) = 'D'
         FLAGARRAY(IELEM,ILINE,1) = SMALLE
         HLDFLAG = FLAGARRAY(IELEM,ILINE,1)
         CALL WRTVAL(VALARRAY(IELEM,ILINE),HLDFLAG,IROW,ICOL)
         IELEM = IELEM + 1
         IRTN = 1
      ELSE IF (CHOICE.EQ.'3')THEN
         VALARRAY(IELEM,ILINE) = SPACES
         FLAGARRAY(IELEM,ILINE,1) = BIGA
         FLAGARRAY(IELEM,ILINE,2) = BIGA
         HLDFLAG = FLAGARRAY(IELEM,ILINE,1)
         CALL WRTVAL(VALARRAY(IELEM,ILINE),HLDFLAG,IROW,ICOL)
         CALL LOCATE(IROW,ICOL,IERR)
      ELSE IF (CHOICE.EQ.'4')THEN
         VALARRAY(IELEM,ILINE) = SPACES
         FLAGARRAY(IELEM,ILINE,1) = BIGA
         FLAGARRAY(IELEM,ILINE,2) = BIGA
         HLDFLAG = FLAGARRAY(IELEM,ILINE,1)
         CALL WRTVAL(VALARRAY(IELEM,ILINE),HLDFLAG,IROW,ICOL)
         CALL LOCATE(IROW,ICOL,IERR)
         IRTN = 3
      ELSE IF (CHOICE.EQ.'5')THEN
         IRTN = 2
         CALL LOCATE(IROW,ICOL,IERR)
      END IF
      RETURN
      END
C
$PAGE
C
      SUBROUTINE QCCHOICE(IROW,ICOL,CHOICE,RTNFLAG)
C
C  THIS ROUTINE DISPLAYS A MENUE ON LINE 21 OF THE SCREEN WHEN A 'RED'
C  FLAGGED ELEMENT IS ENCOUNTERED.  THIS MENUE SOLICITS THE FOLLOWING
C  CHOICES:  1 = ACCEPT AS ACCURATE
C            2 = ACCEPT AS QUESTIONABLE
C            3 = REPLACE WITH ACTUAL VALUE
C            4 = REPLACE WITH ESTIMATED VALUE
C            5 = SKIP THIS VALUE
C  ENTRY OF A VALID CONTROL CHARACTER ALLOWS THE VALIDATOR TO GO ON 
C  WITHOUT RESOLVING THE ERROR.  IN THIS CASE FLAG(1) REMAINS A 'C'
C  AND THIS DATA SET CAN NOT BE LOADED INTO DATA EASE UNTIL IT IS
C  RESOLVED.  IF A VALID CONTROL CHARACTER IS ENTERED '5' IS RETURNED
C  IN CHOICE AND THE CONTROL CHARACTER IS RETURNED IN RTNFLAG.
C
      CHARACTER*1 CHOICE,SPACES(80)
      CHARACTER*2 INCHAR,RTNFLAG
      CHARACTER*20 MSGTX1, MSGTX2, MSGTX3, MSGTX4
      CHARACTER*78 MESSAG
      CHARACTER*64 HELPFILE
      LOGICAL FIRSTCL
C
      DATA SPACES/80*' '/, FIRSTCL /.TRUE./
     +    ,HELPFILE /'P:\HELP\KE-QC-3.HLP'/
C
C  ON THE FIRST CALL TO THIS ROUTINE READ THE TEXT OF THE CHOICE LINE
C
      IF (FIRSTCL) THEN
         FIRSTCL = .FALSE.
         CALL GETMSG(271,MESSAG)
         READ(MESSAG,'(I2,2X,A20)') IMSG1,MSGTX1
         IF (IMSG1.LT.20) THEN
            MSGTX1(IMSG1+1:20) = ' '
         END IF
         CALL GETMSG(272,MESSAG)
         READ(MESSAG,'(I2,2X,A20)') IMSG2,MSGTX2
         IF (IMSG2.LT.20) THEN
            MSGTX2(IMSG2+1:20) = ' '
         END IF
         CALL GETMSG(273,MESSAG)
         READ(MESSAG,'(I2,2X,A20)') IMSG3,MSGTX3
         IF (IMSG3.LT.20) THEN
            MSGTX3(IMSG3+1:20) = ' '
         END IF
         CALL GETMSG(274,MESSAG)
         READ(MESSAG,'(I2,2X,A20)') IMSG4,MSGTX4
         IF (IMSG4.LT.20) THEN
            MSGTX4(IMSG4+1:20) = ' '
         END IF
         CALL GETMSG(999,MESSAG)
      END IF
C
      RTNFLAG = '  '
      CHOICE = ' '
      INCHAR = '  '
C
      CALL LOCATE(21,1,IERR)
      CALL WRTSTR(SPACES,79,14,0)
      CALL LOCATE(21,1,IERR)
      CALL WRTSTR('1-',2,14,0)
      CALL WRTSTR(MSGTX1,IMSG1,15,4)
      CALL WRTSTR('  2-',4,14,0)
      CALL WRTSTR(MSGTX2,IMSG2,15,4)
      CALL WRTSTR('  3-',4,14,0)
      CALL WRTSTR(MSGTX3,IMSG3,15,4)
      CALL WRTSTR('  4-',4,14,0)
      CALL WRTSTR(MSGTX4,IMSG4,15,4)
C
  100 CONTINUE
      CALL LOCATE(IROW,ICOL,IERR)
      CALL GETCHAR(0,INCHAR)
      IF (INCHAR.EQ.'1F') THEN
         CALL DSPWIN(HELPFILE)
         GO TO 100
      ELSE IF (INCHAR(2:2).EQ.' ')THEN
         IF (INCHAR.LT.'1 '.OR.INCHAR.GT.'4 ')THEN
            CALL BEEP
            GO TO 100
         ELSE
            CHOICE = INCHAR(1:1)
         END IF
      ELSE IF (INCHAR.EQ.'6F') THEN
         CHOICE = '3'
      ELSE
         CHOICE = '5'
         RTNFLAG = INCHAR
      END IF
C
  110 CALL LOCATE(21,1,IERR)
      CALL WRTSTR(SPACES,79,14,0)
C
      RETURN
      END
