$STORAGE:4
      SUBROUTINE IROUND4(R4VAL,I4VAL)
C
C       ** OBJECTIVE:  ROUND REAL VALUES TO INTEGER*4 VALUES -- THIS ROUTINE
C                      ALLOWS NINT TO PRODUCE AN INTEGER*4 VALUE.  NINT WILL
C                      ALWAYS PRODUCE AN INTEGER*2 VALUE IN ROUTINES THAT ARE
C                      DECLARED $STORAGE: 2
C       ** INPUT:
C             R4VAL.....REAL*4 ARGUMENT THAT WILL BE ROUNDED
C       ** OUTPUT:
C             I4VAL.....INTEGER*4 RESULT AFTER ROUNDING
C
      REAL*4    R4VAL
      INTEGER*4 I4VAL
C      
      I4VAL = NINT(R4VAL)
C
      RETURN
      END       