$STORAGE:2

      SUBROUTINE MSGS2TXT
C
C   ROUTINE TO CONVERT THE MESSAGE FILE (P:\DATA\MESSAGES.FTN) FROM A
C   DIRECT FORTRAN FILE TO THE TEXT FILE P:\DATA\MESSAGES.TXT THAT CAN BE
C   MODIFIED WITH A STANDARD EDITOR OR WORD PROCESSOR.
C
      CHARACTER*78 MSGLIN,MSGTXT(4)
      CHARACTER*2 INCHAR
C
C   OPEN THE MESSAGE FILE AND CONVERT IT TO TEXT FILE
C      
  40  CONTINUE
      OPEN (18,FILE='P:\DATA\MESSAGES.FTN',STATUS='OLD',ACCESS='DIRECT'
     +    ,RECL=78,IOSTAT=IOCHK)
      IF (IOCHK.NE.0) THEN
         CALL OPENMSG('P:\DATA\MESSAGES.FTN  ','MSGS2TXT    ',IOCHK)
         GO TO 40
      END IF            
      OPEN (17,FILE='P:\DATA\MESSAGES.TXT',STATUS='UNKNOWN'
     +      ,FORM='FORMATTED')
      DO 50 I = 1,9999
         READ(18,REC=I,ERR=60) MSGLIN
         WRITE(17,'(I4.4,''-'',A78)') I,MSGLIN
         IEND = I
  50  CONTINUE
  60  CONTINUE
      CLOSE(17)
      READ(18,REC=286) MSGTXT(1)
      READ(18,REC=287) MSGTXT(2)
      READ(18,REC=288) MSGTXT(3)
      READ(18,REC=202) MSGTXT(4)
      CLOSE(18)
C
C   WRITE THE PROGRAM SUMMARY LINE
C
      CALL LOCATE(19,0,IERR)
      WRITE(MSGLIN,'(I4,1X,A72)') IEND,MSGTXT(1)
      WRITE(*,*) MSGLIN
      WRITE(*,*) MSGTXT(2)
      WRITE(*,*) MSGTXT(3)
      WRITE(*,*) MSGTXT(4)
      CALL GETCHAR(0,INCHAR)
      RETURN
      END