$STORAGE:2
      SUBROUTINE RDDATCFG(IFMT)
C
      INTEGER*2 IFMT
C
      PARAMETER (MXFMT=3)
      CHARACTER*3 DEVER
      CHARACTER*6 DATEFMT(MXFMT),DATECFG
      CHARACTER*8 CFGREC
      CHARACTER*18 FILENAME
      CHARACTER*24 MSG
C      
C
C       ** FORMAT    DATE       NAME      
C          1         MM-DD-YY   NORTH AMERICAN
C          2         DD-MM-YY   INTERNATIONAL
C          3         YY-MM-DD   METRIC
C
      DATA DATEFMT/'MMDDYY','DDMMYY','YYMMDD'/
C
      FILENAME = 'P:\DATA\DEDATE.CFG'
   10 OPEN(62,FILE=FILENAME,STATUS='OLD',MODE='READ',
     +        IOSTAT=IOCHK)
      IF(IOCHK.NE.0) THEN
         CALL OPENMSG(FILENAME,'RDATECFG    ',IOCHK)
         GO TO 10
      END IF   
      READ(62,'(A)',ERR=900,IOSTAT=IOCHK) CFGREC           
      CLOSE (62)
C
      DATECFG(1:2) = CFGREC(1:2)      
      DATECFG(3:4) = CFGREC(4:5)      
      DATECFG(5:6) = CFGREC(7:8)      
      CALL LOW2UP(DATECFG)
C
      DO 20 I=1,MXFMT
         IF(DATECFG.EQ.DATEFMT(I)) GO TO 25
   20 CONTINUE    
      GO TO 910
   25 CONTINUE
      IFMT = I
C
      CALL GETDEASE(DEVER)
      IF (DEVER.EQ.'2.5') THEN
         IF (IFMT.GT.2) GO TO 910
      END IF
      RETURN
C
C       ** ERROR PROCESSING
C
  900 CONTINUE
C       .. ERROR READING FILE:  P:\DATA\DEDATE.CFG
      CLOSE (62)
      LGTH = LEN(FILENAME)
      WRITE(MSG,'(A,2X,I4.4)')FILENAME(1:LGTH),IOCHK
      LGTH = LEN(MSG)
      CALL WRTMSG(3,191,12,1,1,MSG,LGTH)
      GO TO 999
  910 CONTINUE
C       .. ILLEGAL DATE FORMAT
      LGTH = LEN(CFGREC)
      CALL WRTMSG(3,342,12,1,1,CFGREC,LGTH)
C
  999 CONTINUE
      CALL LOCATE(24,0,IERR)
      STOP 2
      END      
                  