$STORAGE:2
      SUBROUTINE RDLIMS(KEYQC,QCTYPE,RTNCODE)
C
C   ROUTINE TO DO A BINARY SEARCH OF THE ELEM.LIM FILE TO FIND THOSE
C   ELEMENTS SPECIFIED IN THE CURRENT SETUP FILE THAT THE ELEMCHKS 
C   FILE INDICATES STATION-MONTH-LIMITS ARE NEEDED. THE ELEMENTS ARE
C   FOUND FOR THE STATION, OBS-TYPE AND MONTH SPECIFIED IN KEYQC.
C
C   KEYQC = STATION-ID, OBS-TYPE, MONTH
C
C      IF QC-TYPE = 'A' THEN READ ONLY THOSE ELEMENTS FOR WHICH SCALED
C           AREA-QC IS WANTED 
C      ELSE READ THOSE ELEMENTS FOR WHICH STN-LIMITS ARE WANTED IN EDIT
C
$INCLUDE: 'VAL1.INC'
$INCLUDE: 'ELEMCHKS.INC'
C
      CHARACTER*1 REPLY,RTNCODE,QCTYPE
      CHARACTER*3 OBSTYPE,OBSTBL(7)
      CHARACTER*8 STNID
      CHARACTER*13 KEYQC
      CHARACTER*12 SRCHKY,HLDKEY
C
      INTEGER*2 MONTH,ELEM,SOURCE,BYEAR,EYEAR,YEARS,MAXFLAG,MINFLAG,
     +          IOCHK,SRCHELEM,ITYPE
      LOGICAL NOSTN,STNFOUND,FILOPN
C
      INTEGER*4 MAXDATE,MINDATE
      INTEGER*4 NUMREC,ITOPHLD,IBOTHLD,ITOP,IBOT,K
      REAL MAXVALUE,MINVALUE,MAXCHNG
      REAL*8 STNDRDDEV,MEANVALUE
      DATA OBSTBL/'MLY','10D','DLY','SYN','HLY','15M','U-A'/
      DATA FILOPN /.FALSE./
C
C  SET DEFAULT QC LIMITS - USED IF NO EXTREMES ARE FOUND FOR AN ELEMENT
C 
      DO 5 I = 1,MAXELEM
         TBLMAX(I) = 99999.0
         TBLMIN(I) = -9999.0
         TBLMXCR(I) = 99999.0
         TBLSTDDEV(I) = 99999.0
         TBLMEAN(I) = 0.0
    5 CONTINUE
C
      IF (.NOT.FILOPN) THEN
   20    CONTINUE
         OPEN(31,FILE='P:\DATA\ELEM.LIM',STATUS='OLD',ACCESS='DIRECT',
     +        RECL=62,SHARE='DENYWR',MODE='READ',IOSTAT=IOCHK)
         IF(IOCHK.NE.0) THEN
            CALL OPENMSG('P:\DATA\ELEM.LIM      ','RDLIMS      ',IOCHK)
            GO TO 20
         FILOPN = .TRUE.
         END IF   
      END IF
C
C   INITIALIZE THE BINARY SEARCH LOOP VARIABLES
C
      READ(KEYQC,'(A8,A3,I2)') STNID,OBSTYPE,MONTH
      DO 50 I = 1,7
         IF (OBSTBL(I).EQ.OBSTYPE) THEN
            ITYPE = I
            GO TO 55
         END IF
   50 CONTINUE
   55 CONTINUE
      WRITE(SRCHKY,'(A8,I2.2,I2.2)') STNID,ITYPE,MONTH
      NOSTN = .FALSE.
      STNFOUND = .FALSE.
      READ(31,REC=1) NUMREC
      ITOPHLD = NUMREC + 2
      IBOTHLD = 1
      RTNCODE = '0'
C
C   BEGIN THE LOOP TO SEARCH FOR THE ELEMENTS IN THE SETUP FILE THAT
C   REQUIRE STN-MONTH LIMITS
C
      DO 500 IELEM = 1,NUMELEM
         DO 80 ICHK = 1,MAXCHK
            IF (QCTYPE.EQ.'E'.AND.CHKTYP(IELEM,ICHK).GE.51) THEN
               GO TO 90
            ELSE IF (QCTYPE.EQ.'A'.AND.CHKTYP(IELEM,ICHK).EQ.55) THEN
               GO TO 90
            ELSE IF (CHKTYP(IELEM,ICHK).EQ.0) THEN
               GO TO 500
            END IF
   80    CONTINUE
         GO TO 500
   90    CONTINUE                  
C
C          ** NO STATION LIMIT CHECKS IF DATA TYPE IS MLY, 10D, U-A
C
         IF (OBSTYPE.EQ.'MLY' .OR. OBSTYPE.EQ.'10D' .OR.
     +                             OBSTYPE.EQ.'U-A') THEN
            CALL WRTMSG(3,427,12,1,1,OBSTYPE,3)
            GO TO 550
         ENDIF    
         SRCHELEM = TBLELEM(IELEM)
C
C   BEGIN THE BINARY SEARCH LOOP FOR THE CURRENT STN/OBSTYPE/MONTH/ELEM
C 
         IBOT = IBOTHLD
         ITOP = ITOPHLD
  100    CONTINUE
C
C      FIRST LOCATE THE STATION/OBSTYPE/MONTH
C
         IF (ITOP-IBOT.GT.1) THEN
            K = (ITOP+IBOT)/2
            IF(K.LT.2) THEN
               K = 2
            END IF   
            READ(31,REC=K)STNID,IOBS,MONTH,ELEM,SOURCE,
     +                 BYEAR,EYEAR,YEARS,MAXVALUE,MAXDATE,
     +                 MAXFLAG,MINVALUE,MINDATE,MINFLAG,
     +                 MEANVALUE,STNDRDDEV,MAXCHNG
C
            WRITE(HLDKEY,'(A8,I2.2,I2.2)') STNID,IOBS,MONTH
            IF (SRCHKY.LT.HLDKEY) THEN
               ITOP = K
               ITOPHLD = K
               GO TO 100
            ELSE IF (SRCHKY.GT.HLDKEY) THEN
               IBOT = K
               IBOTHLD = K
               GO TO 100
            END IF
         ELSE
            IF (SRCHKY.NE.HLDKEY) THEN
               IF (STNFOUND) THEN
                  GO TO 200
               ELSE
                  GO TO 300
               END IF
            END IF
         END IF
C
C      STATION/OBSTYPE/MONTH HAS BEEN FOUND - LOCATE THE PROPER ELEM
C
         STNFOUND = .TRUE.
         IF (ITOP-IBOT.GT.1) THEN
            IF (SRCHELEM.LT.ELEM) THEN
               ITOP = K
               GO TO 100
            ELSE IF (SRCHELEM.GT.ELEM) THEN
               IBOT = K
               GO TO 100
            END IF
         ELSE
            IF (SRCHELEM.NE.ELEM) THEN
               GO TO 200
            END IF
         END IF
C
C      PROPER STN/MONTH/ELEM HAS BEEN FOUND - FINISHED
C
         IF (MAXVALUE.NE.-9999.)THEN
            TBLMAX(IELEM) = MAXVALUE
         END IF
         TBLMIN(IELEM) = MINVALUE
         IF (MEANVALUE.NE.-9999.)THEN
            TBLMEAN(IELEM) = MEANVALUE
         END IF
         IF (STNDRDDEV.NE.-9999.)THEN
            TBLSTDDEV(IELEM) = STNDRDDEV
         END IF
         IF (MAXCHNG.NE.-9999.)THEN
            TBLMXCR(IELEM) = MAXCHNG
         END IF
         GO TO 500 
C
C      GET HERE IF STATION/OBS/MONTH FOUND BUT ELEM NOT FOUND
C
  200    CONTINUE
         IF (RELELEM(IELEM).NE.-8888) THEN
            CALL WRTMSG(5,42,12,1,0,TBLEABRV(IELEM),6)
            GO TO 310
         ELSE
            GO TO 500
         END IF
C
C      GET HERE IF STATION/OBS/MONTH IS NOT FOUND
C
  300    CONTINUE
         NOSTN = .TRUE.
         CALL WRTMSG(5,60,12,1,0,' ',0)
  310    CALL LOCATE(21,5,IERR)
         CALL OKREPLY(REPLY,RTNCODE)
         IF (REPLY.EQ.'N'.OR.RTNCODE.EQ.'1')THEN
            CALL CLRMSG(5)
            CALL CLRMSG(4)
            RTNCODE = '1'
            GO TO 550
         ELSE
            CALL WRTMSG(3,426,12,0,1,' ',0)
            CALL CLRMSG(5)
            CALL CLRMSG(4)
         END IF
         IF (NOSTN) THEN
            GO TO 550
         END IF
C 
  500 CONTINUE
  550 CONTINUE
      IF (QCTYPE.NE.'A') THEN
         CLOSE (31)
         FILOPN = .FALSE.
      END IF
      RETURN
      END
