$STORAGE:2

      SUBROUTINE UAPLOT(IDKEY)

************************************************************************ 
*     ASSEMBLE U-A DATA FROM THE KEY-ENTRY/QC ARRAY (VALARRAY) AND PLOT
*     IT AS A SKEW-T DIAGRAM
************************************************************************ 

      IMPLICIT INTEGER*2 (A-Z)
      CHARACTER*78 MSGLIN
      CHARACTER*21 IDKEY
      CHARACTER*1  RTNCODE
C
C  .. COMMONS FOR SKEWT PLOT
$INCLUDE: 'GRFPARM.INC'
$INCLUDE: 'GRAFVAR.INC'
$INCLUDE: 'CURRPLT.INC'
      LOGICAL MOVFLG,REPLTSKT
      REAL*4 X1,Y1,X2,Y2,XN3,YN3,XN4,YN4
C
$INCLUDE:'VAL1.INC'
      CHARACTER*1 FLAG(MAXLINE)
$INCLUDE:'RAOBQC.INC'
C
C   COPY THE FLAGARRAY FOR TEMPERATURE VALUES INTO FLAG SO ERRONEOUS
C   VALUES CAN BE PLOTTED IN A DIFFERENT COLOR
C
      DO 50 I = 1,MAXLINE
         FLAG(I) = FLAGARRAY(3,I,1)
50    CONTINUE         
C
C       ** INITIAL CONTROLS FOR SKEWT PLOT
C
      CALL INITSKT(IDKEY)
C
C       ** OPEN AND INITIALIZE HALO ENVIRONMENT 
C
      CALL BGNHALO(1,PALETTE,PALDEF)
C
C   DISPLAY THE PLOT - DO NOT ZOOM IN TO LOWER 600 MB UNLESS USER REQUESTS
C   IT BY PRESSING F8.
      MOVFLG = .FALSE.
      ZOOMED = .FALSE.
      NUMLVLS = MAXLINE
100   CONTINUE
      CALL INITPV(VPNDLF,VPNDRT,VPNDBT,VPNDTP,PALETTE,BKGNCLR)
      RTNCODE='Q'
      CALL SKEWT(PRESSURE,HEIGHT,TEMP,DEWPTDEP,WINDDIR
     +          ,WINDSPEED,FLAG,NUMLVLS,RTNCODE)
      IF (RTNCODE.NE.'0') THEN
         IF (RTNCODE.EQ.'7') THEN
C             .. SKEWT ERROR:  PRESSURE AND/OR HEIGHT VALUES OUT OF SORT      
C                              SKEWT CANNOT DRAW HEIGHT LABELS
            CALL GETMSG(443,MSGLIN)
            RTNCODE = ' '
         ELSE IF (RTNCODE.EQ.'8') THEN   
C             .. SKEWT ERROR:  NO DATA TO PLOT.  EITHER VALUES MISSING OR 
C                              PRESSURE TOO LOW TO PLOT.
            CALL GETMSG(442,MSGLIN)
            RTNCODE = ' '
         ELSE   
C             .. UNKNOWN RETURN CODE FROM SKEWT
            CALL GETMSG(186,MSGLIN)
            LGTH = LNG(MSGLIN)
         ENDIF            
         CALL GETMSG(999,MSGLIN)
         LGTH = LNG(MSGLIN)
         IF (RTNCODE.NE.' ') LGTH=LGTH+1
         CALL INQVIE(XN3,YN3,XN4,YN4)
C          .. IN ORDER TO OPEN THE VIEWPORT TO THE ENTIRE SCREEN, A MAX VALUE
C             EQUAL TO .999 MUST BE USED.  A VALUE OF 1.0 IS A SPECIAL SIGNAL
C             FOR HALO TO 'TURN OFF' THE VIEWPORT WHICH DOES NOT RESET ASPECT 
C             RATIOS
         CALL SETVIE(0.0,0.0,.999,.999,-1,-1)
         CALL INQWOR(X1,Y1,X2,Y2)
         CALL SETWOR(X1,0.,X2,1.)
         CALL SETTEX(2,1,0,1)
         CALL MOVTCA(X1,.8)
         CALL GRFTXT(LGTH,MSGLIN//RTNCODE,1,3)
         CALL SETVIE(XN3,YN3,XN4,YN4,-1,-1)
         CALL SETWOR(X1,Y1,X2,Y2)
      ENDIF
      CALL SETZOOM(MOVFLG,ZOOMED,REPLTSKT)
      IF (REPLTSKT) GO TO 100
C      
      CALL FINHALO
      RETURN
      END
      