$STORAGE:2
      SUBROUTINE GTOLDLST(STNSTAT,MXRSTNG,LSTNAM,NSTNLST)
C
      INTEGER*2 MXRSTNG,NSTNLST
      INTEGER*1 STNSTAT(MXRSTNG)
      CHARACTER*8  LSTNAM
C
      CHARACTER*80 MSGTXT
      CHARACTER*20 LSTFIL
      CHARACTER*24 LSTABRV
      CHARACTER*8  LSTID
      CHARACTER*1  RTNCODE
C
      NSTNLST=0
      IF (LSTNAM.NE.' ' .AND. LSTNAM.NE.'STNGEOG') THEN
         LSTFIL='O:\DATA\'//LSTNAM
         IC=LNG(LSTFIL)
         LSTFIL(IC+1:)='.LST'
         OPEN (51,FILE=LSTFIL,STATUS='OLD',ACCESS='DIRECT',RECL=36,
     +            IOSTAT=ISTAT)
         IF (ISTAT.NE.0) THEN
            WRITE(MSGTXT,'(A,2X,I4.4)') LSTFIL,ISTAT
            LGTH = LNG(MSGTXT)
            CALL WRTMSG(2,157,12,1,1,MSGTXT,LGTH)
            GO TO 100
         ENDIF   
         READ(51,REC=1,IOSTAT=ISTAT) NRECL
         IF (ISTAT.NE.0) THEN
            WRITE(MSGTXT,'(A,2X,I4.4)') LSTFIL,ISTAT
            LGTH = LNG(MSGTXT)
            CALL WRTMSG(2,191,12,1,1,MSGTXT,LGTH)
            GO TO 50
         ENDIF         
C         
         CALL CKRECNBR(RTNCODE)
         IF (RTNCODE.NE.'0') THEN
            CALL GTRECNBR(MXRSTNG,RTNCODE)
            IF (RTNCODE.EQ.'2' .OR. RTNCODE.EQ.'3') GO TO 50
         ENDIF   
C          .. READ THE NUMBER OF STATIONS IN CASE THE FILE WAS CHANGED BY
C             ROUTINE GTRECNBR
         READ(51,REC=1,ERR=50) NRECL
C         
         DO 45 IRECL=2,NRECL+1
            READ(51,REC=IRECL) IRECG,LSTID,LSTABRV
            STNSTAT(IRECG) = -1
   45    CONTINUE
         NSTNLST=NRECL
   50    CONTINUE
         CLOSE(51)
      ENDIF     
C
  100 CONTINUE
      RETURN
      END      
