$STORAGE:2
      SUBROUTINE GTSTNLST(I1WRK,I2WRK,MXRSTNG,I2WRKD,MAXLST,LSTNAM,
     +                    RTNCODE) 
C     
C       ** FILE STRUCTURE:
C          -- STATION LIST INDEX FILE (P:\DATA\MPSTNLST.IDX)
C                RECORD LENGTH = 43
C                FILE TYPE     = DIRECT, BINARY
C                LIST NAME+BLANK+DESCRIPTION+CR+LF
C                   8     +  1       32     +1 +1 =43
C
C       ** INPUT:
C             I1WRK.......INTEGER*1 WORK ARRAY
C             I2WRK.......INTEGER*2 WORK ARRAY
C             MXRSTNG.....MAXIMUM NUMBER OF RECORDS IN STNGEOG.INF THAT
C                         CAN BE PROCESSED FOR STATION SELECTION LIST
C             I2WRKD......DIMENSION OF I2WRK
C             MAXLST......MAXIMUM NUMBER OF STATIONS THAT CAN BE SELECTED FOR
C                         LIST FILE FOR THE CURRENT MAP DEFINITION 
C             LSTNAM......CURRENT NAME OF THE STATION SELECTION LIST FILE.
C                         DEFAULT VALUE ON FIRST ENTRY INTO ROUTINE IS
C                         STNGEOG AND IS SET BY CALLING ROUTINE.  IF RE-ENTRY
C                         INTO THIS ROUTINE, VALUE IS LAST NAME CHOSEN.
C       ** OUTPUT:
C             LSTNAM......NAME OF THE STATION SELECTION FILE CHOSEN BY THE
C                         USER.  DEFAULT VALUE IS STNGEOG
C             RTNCODE.....ERROR FLAG  0=NORMAL EXIT  1=EXIT WITH F4/ESC
C
      INTEGER*2 MXRSTNG,I2WRKD,I2WRK(I2WRKD)
      INTEGER*1 I1WRK(MXRSTNG)
      CHARACTER*8 LSTNAM
      CHARACTER*1 RTNCODE
C
      PARAMETER (IRECL=43)
      CHARACTER*(IRECL) LSTENTRY
      CHARACTER*78 MSGTXT
      CHARACTER*64 HELPFILE
      CHARACTER*8  SAVNAM
      CHARACTER*2  RTNFLAG
C      
      DATA HELPFILE/'P:\HELP\GTSTNLST.HLP'/
C
      RTNCODE='0'
      CALL GETMSG(580,MSGTXT)
      CALL GETMSG(999,MSGTXT)
      RTNFLAG = '  '
      SAVNAM  = LSTNAM
      CALL POSLIN(IROW,ICOL)
C
   20 CONTINUE
      CALL WRTFNC(11)
      CALL LOCATE(IROW,ICOL,IERR)
      NCHAR= LNG(MSGTXT)
      CALL WRTSTR(MSGTXT,NCHAR,14,0)
      CALL GETSTR(0,LSTNAM,8,15,1,RTNFLAG)      
      CALL CLRMSG(3)
      IF (RTNFLAG.EQ.'4F') THEN
         CALL CLRMSG(25-IROW)
         LSTNAM = ' '
         RTNCODE='1'
         GO TO 100
      ELSE IF (RTNFLAG.EQ.'1F') THEN
         CALL DSPWIN(HELPFILE)
      ELSE IF (RTNFLAG.EQ.'1S') THEN
   30    CONTINUE
         CALL LOCATE(IROW,ICOL,IERR)
         LSTENTRY = ' '
         ICNTRL=0
         OPEN (51,FILE='O:\DATA\MPSTNLST.IDX',STATUS='OLD',FORM='BINARY'
     +           ,ACCESS='DIRECT',RECL=IRECL)
         CALL VALWIN(51,LSTENTRY,IRECL,6,ICNTRL)
         CLOSE(51)
         IF (LSTENTRY.NE.' ') THEN
            LSTNAM = LSTENTRY(1:8)
            IF (ICNTRL.EQ.1) THEN
               CALL LOCATE(IROW+2,5,IERR)
               CALL OPSTNLST(I1WRK,I2WRK,MXRSTNG,I2WRKD,MAXLST,
     +                       LSTNAM,SAVNAM)
               LSTNAM=' '
               IF (SAVNAM.EQ.' ') SAVNAM='STNGEOG'
               GO TO 30
            ELSE
               SAVNAM=LSTNAM   
            ENDIF   
         ELSE
            LSTNAM=SAVNAM
         ENDIF
      ELSE IF (RTNFLAG.EQ.'2F') THEN
         IF (LSTNAM.EQ.' ') THEN
             CALL WRTMSG(3,597,12,1,0,' ',0)
         ELSE
C
C             .. ACCEPT FILE NAME FOR STATION LIST               
            GO TO 100
         ENDIF   
      ENDIF       
      GO TO 20
C
  100 CONTINUE
      IF (LSTNAM.EQ.' ') LSTNAM='STNGEOG '
C
      RETURN
      END
      