$STORAGE:2
      SUBROUTINE MPLIN(XWIN,YWIN,MPCODE)
C      
      INTEGER*2 MPCODE(5)
      REAL *4   XWIN(*),YWIN(*)
C      
$INCLUDE:  'SYSFONT.INC'
C
      PARAMETER (MAXCHAR=22,MAXCHOICE=9,MAXITEM=MAXCHOICE+1)
      INTEGER*2 WINSTAT,HELPLVL,MPCSAV(5)
      CHARACTER*2 INCHAR
      CHARACTER *(MAXCHAR) CHOICE(MAXITEM)
      CHARACTER *3 MPMRK
C
      DATA MPMRK/'^X^'/
      DATA ISPFAC/.7/
C
C       ** INITIAL WINDOW CONTROL VARIABLES;  WINSTAT IS SET TO DRAW MENU,
C          AND GET CHOICE; SCREEN IS NOT SAVED; SAVE FLAGS FOR MAP LINES
C
      WINSTAT = 2
      HELPLVL=1
      DO 10 I=1,5
         MPCSAV(I)=MPCODE(I)
   10 CONTINUE      
C   
C       .. GET THE CURRENT VIEWPORT AND WORLD COORDINATES
      CALL INQVIE(XWINLF,YWINTP,XWINRT,YWINBT)
      CALL INQWOR(XLOW,YLOW,XHIGH,YHIGH)
C
C       .. OPEN THE VIEWPORT TO THE ENTIRE SCREEN; SET WORLD COORDINATES      
      CALL SETVIE(0.,0.,.999,.999,-1,-1)
      CALL SETWOR(0.0,0.0,1.,1.)
C
C       .. GET THE ASPECT RATIO FOR THE MARKER CHARACTER WHEN THE VIEWPORT IS
C          OPENED TO THE ENTIRE SCREEN.
      ICLR    = 0
      IDFONT  = ISYSFNT
      STDASP  = SYSASP
      TXTHTND = SYSHTND
      IASPFLG = 0

      CALL DFHSTWIN(IDFONT,ICLR,TXTHTND,IASPFLG,STDASP,ADJASP)
      CALL INQVIE(XNDUL,YNDUL,XNDLR,YNDLR)
      CALL INQWOR(XWLL,YWLL,XWUR,YWUR)
      CALL INQSTS(MPMRK,HEIGHT,WIDSTR,OFFSET)
      CALL MAPWTN(XWLL+WIDSTR,YWLL+HEIGHT,XND,YND)
      WSTRND = XND-XNDUL

C
C       .. RETURN TO CURRENT VIEWPORT AND WORLD COORDINATES
      CALL SETVIE(XWINLF,YWINTP,XWINRT,YWINBT,-1,-1)
      CALL SETWOR(XLOW,YLOW,XHIGH,YHIGH)
C
C       ** DISPLAY MENU; GET INITIAL INPUT FROM USER
C          NOTE:  INITIAL INPUT POSITIONS CURSOR AND DISPLAYS INITIAL
C                 ON/OFF SETTINGS FOR MAP LINE FLAGS; A SECOND INPUT IS
C                 REQUIRED TO TOGGLE FLAGS ON/OFF
C       .. DISPLAY MENU WITH MAP LINE LABELS
      MENUNUM = 1
      CALL RDMENU(MENUNUM,MAXITEM,CHOICE,NUMCHOICE,RTNCODE)      
      NUMCHOICE = NUMCHOICE-1
      CALL ARGMENU(WINSTAT,CHOICE,NUMCHOICE,XWIN(1),YWIN(1),HELPLVL,
     +             INCHAR)
C
C       .. DRAW WINDOW FOR ON/OFF SETTINGS
      WBOXND = .05
      CALL XYWNDO(XWINLF,YWINTP,XWINRT,YWINBT)
      XBXLF = XWINRT + .01
      YBXBT = YWINBT
      XBXRT = XBXLF + WBOXND
      YBXTP = YWINTP
      ICNTRL = 1
      CALL WNDOBOX(ICNTRL,XBXLF,YBXTP,XBXRT,YBXBT)      
C
C       .. GET THE ASPECT RATIO FOR THE CURRENT WINDOW COORDINATES
      CALL INQVIE(XNDUL,YNDUL,XNDLR,YNDLR)
      XTRA_X = AMAX0(((XNDLR-XNDUL)-WSTRND),0.)

      CALL DFWINASP(MPMRK,IDFONT,ICLR,TXTHTND,XTRA_X,ADJASP,WINASP)

C
C       .. DISPLAY MAP FLAG SETTINGS IN WINDOW      
      CALL INQSTS(MPMRK,HEIGHT,CWIDTH,OFFSET)
      HTLIN = HEIGHT+ISPFAC*OFFSET
      CALL INQWOR(XLOW,YLOW,XHIGH,YHIGH)
      DXWIN = XHIGH-XLOW
      XPOS = XLOW + MAX0(.5*(DXWIN-CWIDTH),0)
      DO 20 I=1,5
         IF (MPCODE(I).EQ.-1) GO TO 20
            YPOS = YHIGH - (I+1)*HTLIN
            CALL MOVTCA(XPOS,YPOS)
            CALL DELTCU( )
            CALL STEXT(MPMRK)
   20 CONTINUE
C   
      IF (INCHAR.EQ.'ES') GO TO 100
      READ(INCHAR,'(I1)') NMPC
      IF (MPCODE(NMPC).GT.-1) THEN
         MPCODE(NMPC)=-1
      ELSE
         MPCODE(NMPC)=1
      ENDIF
C      
      ICNTRL = -1
      CALL WNDOBOX(ICNTRL,XBXLF,YBXTP,XBXRT,YBXBT)      
      WINSTAT=3
C      
   30 CONTINUE
      IF (INCHAR.EQ.'ES') GO TO 100
         READ(INCHAR,'(I1)') NMPC
         IF (MPCODE(NMPC).GT.-1) THEN
            MPCODE(NMPC)=-1
            ICLR=3
         ELSE
            MPCODE(NMPC)=MAX0(MPCSAV(NMPC),0)
            ICLR=0
         ENDIF
C         
         ICNTRL = 2
         CALL WNDOBOX(ICNTRL,XBXLF,YBXTP,XBXRT,YBXBT)      
         IASPFLG = 1

         CALL DFHSTWIN(IDFONT,ICLR,TXTHTND,IASPFLG,STDASP,WINASP)

C         
         YPOS = YHIGH - (NMPC+1)*HTLIN
         CALL MOVTCA(XPOS,YPOS)
         CALL DELTCU( )
         CALL STEXT(MPMRK)
         ICNTRL = -1
         CALL WNDOBOX(ICNTRL,XBXLF,YBXTP,XBXRT,YBXBT)      
         CALL ARGMENU(WINSTAT,CHOICE,NUMCHOICE,XWIN(1),YWIN(1),
     +                HELPLVL,INCHAR)
      GO TO 30
C      
  100 CONTINUE
      ICNTRL = -2
      CALL WNDOBOX(ICNTRL,XBXLF,YBXTP,XBXRT,YBXBT)      
      WINSTAT=0
      CALL ARGMENU(WINSTAT,CHOICE,NUMCHOICE,XWIN(1),YWIN(1),HELPLVL,
     +             INCHAR)
C
      RETURN
      END      
      