$STORAGE:2

      SUBROUTINE RGB2INT(IRGB,JCLR)
      INTEGER*2 IRGB(3)
      JCLR = IRGB(1)*100 + IRGB(2)*10 + IRGB(3)
      RETURN
      END
         
      SUBROUTINE INT2RGB(JCLR,IRGB)
      INTEGER*2 IRGB(3),JCLR
      ITMP    = JCLR
      IRGB(1) = ITMP/100
      ITMP    = ITMP - IRGB(1)*100
      IRGB(2) = ITMP/10
      IRGB(3) = ITMP - IRGB(2)*10
      RETURN
      END

      SUBROUTINE RGB2EGA(IRGB,EGACLR)
C
C   ROUTINE TO TRANSLATE RGB COLOR INDEX VALUES TO THE COLOR VALUE 
C   BITS USED BY EGA BOARDS.
C
C     INPUT - IRGB...RGB COLOR VALUES (3 ITEM ARRAY WITH VALUES 0-3)
C    OUTPUT - EGACLR...INTEGER COLOR VALUE(0-63) 
C
      INTEGER*2 IRGB(3),EGACLR
C
      EGACLR = 0
      DO 50 I = 1,3
         J = 4 - I
         IF (IRGB(J).EQ.0) THEN
            EGACLR = IBCLR(EGACLR,I-1)
            EGACLR = IBCLR(EGACLR,I+2)
         ELSE IF (IRGB(J).EQ.1) THEN
            EGACLR = IBSET(EGACLR,I+2)
            EGACLR = IBCLR(EGACLR,I-1)
         ELSE IF (IRGB(J).EQ.2) THEN
            EGACLR = IBSET(EGACLR,I-1)
            EGACLR = IBCLR(EGACLR,I+2)
         ELSE IF (IRGB(J).EQ.3) THEN
            EGACLR = IBSET(EGACLR,I-1)
            EGACLR = IBSET(EGACLR,I+2)
         END IF
50    CONTINUE                
      RETURN
      END
