$STORAGE:2

      SUBROUTINE SETCFON(IFONT)
C
C   ROUTINE TO SET THE HALO STROKE TEXT FONT TO ONE OF THE FONTS SUPPORTED
C   BY CLICOM.
C
C    IFONT...CLICOM STROKE TEXT FONT NUMBER (1-9)
C
      CHARACTER*3 STFONT(9)
      CHARACTER*26 FILNAME
      DATA FILNAME /'&P:\HALO\FONTS\AHD000.FNT&'/
      DATA STFONT /'104','102','106','107','201','203','204',
     +             '405','406'/
C
      FILNAME(19:21) = STFONT(IFONT)
      CALL SETFON(FILNAME)
      RETURN
      END
      