$STORAGE:2
      SUBROUTINE SCRNMSGI(MSG,IROW,ICLR)
C 
C       ** OBJECTIVE:  DISPLAY A MESSAGE ON THE SCREEN AT THE SPECIFIED
C                      ROW NUMBER.  IF THE ROW IS OFF THE SCREEN, SCROLL
C                      UP UNTIL THE ROW IS AT THE BOTTOM LINE.  
C       ** NOTE:  THIS ROUTINE IS USED IN THE INSTALLATION PROGRAMS
C                 WHERE THE MESSAGE FILE IS NOT AVAILABLE.  ROUTINE
C                 WRTMSG SHOULD BE USED FOR NORMAL CLICOM PROGRAMS. 
C                             
      CHARACTER*(*) MSG
C
      LGTH = MIN0(LNG(MSG),80)
      IF (LGTH.EQ.0) THEN
         LGTH = 80
         MSG  = ' '
      ENDIF   
      IF (IROW.GT.24) THEN
         NLIN = IROW - 24
         CALL CLTEXT(0,0,IERR)
         CALL SCROLL(1,NLIN,0,0,24,79)
         IROW = 24
      ENDIF   
      CALL LOCATE(IROW,0,IERR)
      CALL WRTSTR(MSG,LGTH,ICLR,0)
      CALL LOCATE(IROW,0,IERR)
C
      RETURN
      END      
