ECHO OFF
REM ----- SPECIAL COMPILATION OF GRAFWIN AND DRWLGND
IF EXIST GRAFWIN.OBJ COPY GRAFWIN.OBJ *.OSV
IF EXIST GRAFWIN.OBJ COPY DRWLGND.OBJ *.OSV
COPY \CLICOM\SRC\INCLUDES\QCSAVBUF.INC SAVBUF.INC
FL /FPi /Od /4Nb /I\CLICOM\SRC\CORE\GRAFMAIN /c \CLICOM\SRC\CORE\GRAFSUB\GRAFWIN.FOR 
FL /FPi /Od /4Nb /I\CLICOM\SRC\CORE\GRAFMAIN /c \CLICOM\SRC\CORE\GRAFSUB\DRWLGND.FOR 
DEL SAVBUF.INC
REM -----
FL /FPi /Od /4Nb /c TSTMNU.FOR 
link TSTMNU+GRAFWIN+C:\CLICOM\HALO\OBJECTS\AHDMSFL,TMNU2.EXE/SEG:512/NOE/EXEPACK,.MAP,CORELIB+KWLIB+ASM+UTILITY+PLTUTIL;
REM -----
FL /FPi /Od /4Nb /c TSTPRT.FOR 
LINK @LPRT2.LHP
DEL GRAFWIN.OBJ
DEL DRWLGND.OBJ
IF EXIST GRAFWIN.OSV REN GRAFWIN.OSV *.OBJ
IF EXIST DRWLGND.OSV REN DRWLGND.OSV *.OBJ
:EXIT
