echo off
c:\dos\SUBST P: C:\CLICOM
c:\dos\SUBST O: C:\CLIGRAF
SET HALOID=A
SET DEASE=2.5
COPY O:\DATA\DATACOM.SAV O:\DATA\DATACOM.CON
TSTMNU
:EXIT
ECHO EXIT TSTMNU
PAUSE
SET DEASE=
SET HALOID=
SUBST P: /D
SUBST O: /D
