$STORAGE:2
      PROGRAM TSTMNU
C------------------------------------------------------------------------------
C     UPPER LEVEL PROGRAM THAT MANAGES THE OUTPUT DISPOSITION (PRINTER, 
C     PLOTTER, OR DISK) OF THE GRAPH ON THE MONITOR'S SCREEN.
C------------------------------------------------------------------------------
$INCLUDE: 'GRFPARM.INC'
$INCLUDE: 'GRAFVAR.INC'
$INCLUDE: 'DATAVAL.INC'
$INCLUDE: 'FRMPOS.INC'
$INCLUDE: 'CURRPLT.INC'
$INCLUDE: 'SYSFONT.INC'
C
      INTEGER*2 HELPLVL,NTTL,NOKD,LENMSG
      PARAMETER(NOKD=3)
      CHARACTER*2 EXITOPT,OKOPT(NOKD),INCHAR,CHOICE1
      CHARACTER*1 TTLSAV(2),RTNCODE
      CHARACTER*28 GRAFNAME
      CHARACTER*14 MSGTXT
C **DEBUG
      CHARACTER*30 KRNLPATH
C **END DEBUG      
      DATA NTTL/1/
C       .. VALID OPTION FLAGS IN FILE DATACOM.CON
C          GO=RETURN FROM TSTOUT
      DATA OKOPT/'4','GO','ZZ'/
C       .. OPTION FLAG WRITTEN TO DATACOM.CON WHEN EXITING TO GRAFMAN
      DATA EXITOPT/'GO'/      
C
C **DEBUG
      DATA KRNLPATH/'^P:\HALO\KERNELS\AHDMSFL.KRN^'/
C
      ISYSFNT  = 9
      SYSASP   = 1.
      SYSHTND  = .03
C
      CALL SETKER(KRNLPATH)
      CALL CKHALOER(1,'SETKER',IER)
      IF (IER.NE.0) GO TO 995
       OPEN(999,FILE='TST1')
C **END DEBUG      
C
C       **  Open and read GRAPHICS.GDF file and store the values in the
C           GRAFVAR common block.
C
      CALL RDGRAF('GRAPHICS',ITYPE,NELEM,RTNCODE)
C
C       ** INITIAL GRAPHICS
C
      IF (RTNCODE.EQ.'0') THEN
C          .. NORMAL RETURN FROM RDGRAF -- DEFINE PALETTES
         CALL BGNHALO(1,PALETTE,PALDEF)
      ELSE
C          .. ERROR RETURN FROM RDGRAF -- USE DEFAULT PALETTES
         CALL BGNHALO(0,PALETTE,PALDEF)
         GO TO 900
      ENDIF      
C **DEBUG
        WRITE(999,*)'TSTOUT AFT BGNHALO PALETTE=',PALETTE,PALDEF(1,4)      
C
C       ** OPEN AND READ DATACOM.CON FILE AND STORE CONSTANTS IN THE
C          DATAVAL COMMON BLOCK; CLOSE FILE
      CALL RDDCON(1,OKOPT,NOKD,INCHAR,RTNCODE)
      IF (RTNCODE.EQ.'2') THEN
C          .. ERROR IN OPENING FILE      
         GO TO 905        
      ELSE IF (RTNCODE.EQ.'3') THEN
C          .. INVALID OPTION CHARACTER      
         GO TO 920
      ENDIF
      MXDATROW = NROWDIM
C
C       ** Open the GRAPHICS.API file as unit 17 and read the CURRENT DATASET
C          into memory.
C
      IDATAOPT=0
      CALL GETDSET(ITYPSET,IDATAOPT,2,NTTL,TTLSAV,INCSET,RTNCODE)
      IF (RTNCODE.NE.'0') GO TO 900
C
C   1.Save graph definition  2.Save screen  3.Printer  4.Plotter
C
      XL = 0.1
      YL = 0.5
      HELPLVL = 5
      CHOICE1=1
      IWINFLG=4
  100 CALL GRAFMNU(IWINFLG,5,XL,YL,HELPLVL,CHOICE1)
      IF (CHOICE1.EQ.'1 ') THEN
         GRAFNAME = GDFNAME     
         ITYPE = IOBSTYP
         ITEMP = 0 
         CALL WRTGRAF(GRAFNAME,ITYPE,ITEMP,INCHAR)
         IWINFLG=3
      ELSE IF (CHOICE1.EQ.'2 ') THEN
         CALL WRTGSCRN(PALETTE,PALDEF)
         IWINFLG=3
      ELSE IF (CHOICE1.EQ.'3 ') THEN
         IWINFLG=0
         CALL GRAFMNU(IWINFLG,5,XL,YL,HELPLVL,CHOICE1)
         IWINFLG=4
         CALL PRNTMAN(PALETTE,PALDEF,RTNCODE)
         IF (RTNCODE.EQ.'3' .OR. RTNCODE.EQ.'4') THEN
            INCHAR=RTNCODE
            ISTP = 0
            IPSFLG=1
            IDCFLG=1
            GO TO 300
         ENDIF
      ELSE IF (CHOICE1.EQ.'4 ') THEN
         IWINFLG=3
C ** DEBUG       
C         MSGN1=549
C         MSGN2=202
         MSGN1=411
         MSGN2=527
         XWIN=.1
         YWIN=.95
         CALL GRAFNOTE(XWIN,YWIN,MSGN1,MSGN2,' ',0,INCHAR)
C         CALL PLOTMAN(...) 
      ELSE IF (CHOICE1 .EQ. '4F' .OR. CHOICE1 .EQ. 'ES') THEN
         IWINFLG=0
         CALL GRAFMNU(IWINFLG,5,XL,YL,HELPLVL,CHOICE1)
         INCHAR=EXITOPT
         IPSFLG=0
         IDCFLG=0
         ISTP=1
         GO TO 300
      END IF
      GO TO 100
C    
  300 CONTINUE
      CALL WRFILPOS(-1,IGRAPH,NUMCOL,IDUM)
C       .. OPTION FLAG WRITTEN TO DATACOM.CON IS THE CURRENT MENU CHOICE VALUE
C          (7=LINES  8=SIZE/BKGND  9=DATA) OR 'ZZ' IF EXITING TO GRAFINIT
      CALL WRTDCON(IPSFLG,IDCFLG,INCHAR,RTNCODE)
      IF (RTNCODE.NE.'0') GO TO 910        
      CALL FINHALO
      CALL LOCATE(23,0,IERR)
      IF (ISTP.EQ.1) THEN
         STOP 1
      ELSE
         STOP ' '
      ENDIF   
C
C       ** FATAL ERROR      
C
  900 CONTINUE
C          .. ERROR READING FILE: GRAPHICS.GDF  
         MSGN1=191
         MSGTXT='  GRAPHICS.GDF'
         LENMSG=14
         GO TO 990
  905 CONTINUE
C          .. ERROR READING FILE: DATACOM.CON  
         MSGN1=191
         MSGTXT='  DATACOM.CON'
         LENMSG=13
         GO TO 990
  910 CONTINUE
C          .. ERROR WRITING FILE: DATACOM.CON  
         MSGN1=192
         MSGTXT='  DATACOM.CON'
         LENMSG=13
         GO TO 990
  915 CONTINUE
C          .. ERROR READING FILE: GRAPHICS.API  
         MSGN1=191
         MSGTXT='  GRAPHICS.API'
         LENMSG=14
         GO TO 990
  920 CONTINUE
C          .. ILLEGAL OPTIONS CHARACTER  
         MSGN1=551
         MSGTXT=' '
         LENMSG=0
         GO TO 990
  990 CONTINUE         
         MSGN2=202
         XWIN=.1
         YWIN=.95
         CALL GRAFNOTE(XWIN,YWIN,MSGN1,MSGN2,MSGTXT,LENMSG,INCHAR)
  995 CONTINUE         
         CALL WRFILPOS(-1,IGRAPH,NUMCOL,IDUM)
         INCHAR = EXITOPT
         CALL WRTDCON(0,0,INCHAR,RTNCODE)
         IF (RTNCODE.NE.'0') THEN
            MSGN1=192
            MSGTXT='  DATACOM.CON'
            LENMSG=13
            CALL GRAFNOTE(XWIN,YWIN,MSGN1,MSGN2,MSGTXT,LENMSG,INCHAR)
         ENDIF            
         CALL FINHALO
         OPEN (UNIT=62,FILE='O:\DATA\SQUX',ACCESS='DIRECT',
     +         FORM='BINARY',RECL=512,STATUS='OLD',IOSTAT=IOCHK)
         IF (IOCHK.EQ.0) THEN
            CLOSE(62,STATUS='DELETE')
         ENDIF   
         CALL LOCATE(23,0,IERR)
         STOP 1
      END
***************************************************************************
      SUBROUTINE PRNTMAN(PALETTE,PALDEF,RTNCODE)
C------------------------------------------------------------------------------
C     UPPER LEVEL PROGRAM THAT MANAGES THE ROUTINES THAT 1)-REVISE PRINTER
C     FUNCTIONS (FORM FEED, RESOLUTION, ETC) THRU A CLICOM FORM; 2)-SELECTS THE
C     PRINTER TO USE; AND 3)-PRINTS THE SCREEN IN QUICK OR HI-RESOLUTION MODE.
C
C     INPUT ARGUMENTS:
C
C     PALETTE       INT2       CURRENT PALETTE NUMBER
C     PALDEF        INT2 ARRAY CURRENT DEFINITION OF ALL 12 POSSIBLE PALETTES
C                              DISPLAYED ON THE SCREEN
C
C     OUTPUT ARGUMENTS: 
C     RTNCODE       C*1        '0' = MENU WAS EXITED WITH NO CHOICE
C                              '3' = MENU CHOICE 3 (SCREEN PRINT) SELECTED
C                              '4' = MENU CHOICE 4 (HI RESOLUTION) SELECTED
C------------------------------------------------------------------------------
$INCLUDE: 'HALOENV.INC'
      COMMON/DEVHNDL/IHNDLSCR,IHNDLVRI
      INTEGER       PALETTE, PALDEF(16,12), HELPLVL
      CHARACTER*2   INCHAR, USERTXT
      CHARACTER*1   HALOID, RTNCODE
      LOGICAL FIRSTCALL,PRTOPT
      DATA FIRSTCALL/.TRUE./
C **DEBUG
        WRITE(999,*)'BEG PRNTMAN PALETTE=',PALETTE,PALDEF(1,4)      
C
      IDPTR = ACTVPTR+1
      IDCLR = CLRMOD(IDPTR)+1
      IF (PRINTR(1,1)(14:17) .EQ. 'QQQQ') THEN
         CALL GRAFNOTE(0.3,0.8,517,202,' ',0,USERTXT)
         GO TO 200
      ENDIF
C
C---  PTRVAL(0) IS PIXEL WIDTH OF ACTIVE PRINTER. A -1 SIGNIFIES THAT THE
C---  USER FAILED TO RUN THE PRINTER OPTIONS PGM PRIOR TO 1ST EVER PRINT.
C
      PRTOPT = PTRVAL(0,IDPTR).EQ.-1
C **DEBUG      
      WRITE(999,*)'PRNTMAN PTRVAL(0),PRTOPT=',PTRVAL(0,IDPTR),PRTOPT
      IF (FIRSTCALL) THEN
         FIRSTCALL=.FALSE.
C **DEBUG         
         WRITE(999,*)'############PRNTMAN--CALL SETACTPR--FIRSTCALL'         
         CALL SETACTPR(PRINTR(IDCLR,IDPTR),PTRVAL(0,IDPTR),
     +                 PTRASP(IDPTR),IER)
         IF (IER.NE.0) THEN
            IF (IER.GE.29 .AND. IER.LE.33) THEN
               PRTOPT = .TRUE.
C **DEBUG      
               WRITE(999,*)'PRNTMAN IER,PRTOPT=',IER,PRTOPT
            ELSE   
C **DEBUG      
               WRITE(999,*)'PRNTMAN IER,PRTOPT=',IER,PRTOPT
               GO TO 200
            ENDIF
         ENDIF      
      ENDIF                 
C   
C---  DISPLAY GRAPHICS PRINTER MENU. ACTVPTR IS THE PRINTER DESIGNATION,
C---  FROM HALOENV.INC: 0 = PRIMARY AND 1 = ALTERNATE. 
C
      XL=0.1
      YL=0.8
      HELPLVL = 8
C **DEBUG
        WRITE(999,*)'PRNTMAN BEF GRAFMNU PALETTE=',PALETTE,PALDEF(1,4)      
  100 CALL GRAFMNU(1,8,XL,YL,HELPLVL,INCHAR)
C
C-----  CHANGE PRINTER DESIGNATION FROM PRIMARY TO ALTERNATE AND VICE VERSA
C
      NMSG = 0
      IF (INCHAR .EQ. '1 ') THEN
         IF (ACTVPTR .EQ. 0) THEN
            IF (PRINTR(1,2)(14:17) .EQ. 'QQQQ') THEN
               NMSG = 518
            ELSE
               ACTVPTR = 1
               NMSG = 457
            ENDIF
         ELSE
            ACTVPTR = 0
            NMSG = 456
         ENDIF
         IDPTR = ACTVPTR+1
         IDCLR = CLRMOD(IDPTR)+1
C **DEBUG
         WRITE(999,*)'PRMALT  IDPTR,IDCLR=',IDPTR,IDCLR
         WRITE(999,*)'PRMALT PRNTR=',PRINTR(IDCLR,IDPTR)    
         FIRSTCALL=.FALSE.
C **DEBUG         
         WRITE(999,*)'############PRNTMAN--CALL SETACTPR--CHG PTR'         
         CALL SETACTPR(PRINTR(IDCLR,IDPTR),PTRVAL(0,IDPTR),
     +                 PTRASP(IDPTR),IER)
         IF (IER.NE.0) THEN
            IF (IER.GE.29 .AND. IER.LE.33) THEN
               PRTOPT = .TRUE.
C **DEBUG      
               WRITE(999,*)'PRNTMAN IER,PRTOPT=',IER,PRTOPT
            ELSE   
C **DEBUG      
               WRITE(999,*)'PRNTMAN IER,PRTOPT=',IER,PRTOPT
               GO TO 200
            ENDIF
         ENDIF      
C
C-----  UPDATE HALO PRINTER OPTIONS.
C
      ELSE IF (INCHAR .EQ. '2 ') THEN
C **DEBUG
        WRITE(999,*)'PRNTMAN BEF PRNTOP PALETTE=',PALETTE,PALDEF(1,4)      
           CALL CLOSEG
           CALL PRNTOPHP 
           PRTOPT = PTRVAL(0,IDPTR).EQ.-1
C **DEBUG
        WRITE(999,*)'PRNTMAN BEF BGNHALO PALETTE=',PALETTE,PALDEF(1,4)      
           CALL BGNHALO(1,PALETTE,PALDEF)
C
C-----  QUICK SCREEN PRINT 
C-----  NETWORK=1 MEANS IBM PC LAN, SEND END-OF-SPOOL CHAR TO PRINT NOW
C
      ELSE IF (INCHAR .EQ. '3 ') THEN
         IF (.NOT.PRTOPT) THEN
              RTNCODE = INCHAR(1:1)
              GO TO 200
         ELSE
              NMSG = 516
         ENDIF
C
C-----  BETTER RESOLUTION PRINT ( THRU THE VIRTUAL RASTER INTERFACE)
C-----  NETWORK=1 MEANS IBM PC LAN, SEND END-OF-SPOOL CHAR TO PRINT NOW
C
      ELSE IF (INCHAR .EQ. '4 ') THEN
           IF (.NOT.PRTOPT) THEN
              RTNCODE = INCHAR(1:1)
              GO TO 200
           ELSE
              NMSG = 516
           ENDIF
      ELSE IF (INCHAR .EQ. 'ES' .OR. INCHAR .EQ. '4F') THEN
           RTNCODE = '0'
           GO TO 200
      ELSE
           CALL BEEP
      ENDIF
      IF (NMSG.GT.0) CALL GRAFNOTE(0.3,0.8,NMSG,202,' ',0,USERTXT)
      GO TO 100
C
  200 CONTINUE
C **DEBUG
        WRITE(999,*)'END PRNTMAN -- RTNCODE=',RTNCODE  
      RETURN      
      END
