$STORAGE:2

      SUBROUTINE BUFSIZ(XN1,YN1,XN2,YN2,NBYTES)
C
C   ROUTINE COMPUTES THE NUMBER OF BYTES REQUIRED TO SAVE THE WINDOW 
C   DESCRIBED BY THE CORNERS XN1,YN1   XN2,YN2 GIVEN IN NORMALIZED
C   DEVICE COORDS.
C
C    INPUT:
C       XN1,YN1...LOWER VALUE CORNER IN NORMALIZED DEVICE COORDS(NCD)
C       XN2,YN2...HIGHER VALUE CORNER IN NCD
C    OUTPUT:
C       NBYTES....NUMBER OF BYTES REQUIRED (INTEGER*4)
C
      INTEGER*4 NXBYTE,NYPIX,NBYTES,HEADER
      DATA HEADER /6/
C
      CALL MAPNTD(XN1,YN1,I1,J1)
      CALL MAPNTD(XN2,YN2,I2,J2)
      
      JPIX = I2 - I1 + 2
      CALL INQPFL(JBYTE,JPIX)
      NXBYTE = INT4(JBYTE)

      NYPIX = INT4(J2 - J1 + 2)
      NBYTES = NYPIX * NXBYTE
      NBYTES = NBYTES + HEADER
      RETURN
      END
      