$STORAGE:2

      SUBROUTINE DELGRAF (GRAFNAME)
C
C   ROUTINE TO DELETE A GRAPH DEFINITION FILE AND REMOVE ITS ENTRY 
C   FROM THE GRAFDEF INDEX FILE.
C
      CHARACTER*43 INREC
      CHARACTER*64 GRAFFILE
      CHARACTER*8 GRAFNAME
C      
C  BUILD GDF FILE NAME,  OPEN IT, AND DELETE IT
C
      GRAFFILE = 'O:\DATA\'//GRAFNAME
      DO 50 I1 = 20,1,-1
         IF (GRAFFILE(I1:I1).NE.' ') THEN
            GO TO 60
         END IF
50    CONTINUE
60    CONTINUE
      I1 = I1 + 1
      GRAFFILE(I1:I1+3) = '.GDF'         
      OPEN (11,FILE=GRAFFILE,STATUS='OLD',FORM='FORMATTED'
     +     ,MODE='WRITE',IOSTAT=ICHK)
      IF (ICHK.NE.6416.AND.ICHK.NE.0) THEN
         CALL OPENMSG(GRAFFILE,'DELGRAF     ',ICHK)
      END IF
      CLOSE(11,STATUS='DELETE')
C
C   FIND AND REMOVE THE ENTRY FROM THE GRAF-DEF INDEX FILE
C      
      OPEN (51,FILE='O:\DATA\GRAFDEF.IDX',STATUS='OLD',FORM='BINARY'
     +     ,ACCESS='DIRECT',RECL=43)
      DO 100 I = 1,9999
         READ(51,REC=I,ERR=110) INREC
         IF (INREC(1:8).EQ.GRAFNAME) THEN
            INREC(1:8) = '********'              
            INREC(10:41) = 'THIS RECORD DELETED'
            WRITE(51,REC=I) INREC
            GO TO 110
         END IF
100   CONTINUE
110   CONTINUE
      CLOSE(51)
      RETURN
      END
      