$STORAGE:2
      SUBROUTINE GETGRAF (GRAFNAME,ITYPE,NELEM,RTNCODE)
C------------------------------------------------------------------------------
C   ROUTINE TO DISPLAY A LIST OF EXISTING GRAPH DEFINITIONS TO THE USER SO
C   THEY CAN SELECT ONE.  ONCE GRAPH HAS BEEN SELECTED, IT CALLS RDGRAF TO 
C   READ THE GDF FILE INTO THE GRAFVAR COMMON BLOCK.
C   ---> THIS ROUTINE IS ASSOCIATED WITH GRAFINIT <---
C
C     INPUT ARGUMENTS: NONE
C
C     OUTPUT ARGUMENTS:
C
C     GRAFNAME   CHAR  NAME OF THE GRAPH SELECTED (CHAR*8)
C     ITYPE      INT2  CLICOM INTEGER OBS-TYPE FOR THE GRAPH SELECTED
C     NELEM      INT2  THE NUMBER OF ELEMENTS DEFINED FOR THE GRAPH
C     RTNCODE    CHAR  RETURN STATUS:  0 = SELECTION MADE, 1 = NO SELECTION, 
C                      2 = FILE ERROR WITH SELECTION (FROM RDGRAF)
C
C------------------------------------------------------------------------------
      CHARACTER*42 DESCREC
      CHARACTER*8  GRAFNAME
      CHARACTER*1  RTNCODE
      INTEGER*2    ITYPE,NELEM,KROW,KCOL,KER
C
C     ALLOW USER TO SELECT GRAPH FROM GRAPH DEFINITION INDEX FILE
C     AND TAKE APPROPRIATE ACTION.
C
  10  OPEN (51,FILE='O:\DATA\GRAFDEF.IDX',STATUS='OLD',FORM='BINARY'
     +     ,ACCESS='DIRECT',RECL=43)
      RTNCODE = '0'
      DESCREC = ' '
      CALL POSLIN(KROW,KCOL)
      CALL VALWIN(51,DESCREC,41,3,ICNTRL)
      CALL LOCATE(KROW,KCOL,KER)
      CLOSE(51)
      GRAFNAME = DESCREC(1:8)
      IF (GRAFNAME .EQ. '  ') THEN
         RTNCODE = '1'
      ELSE
         IF (ICNTRL.EQ.1) THEN
            CALL DELGRAF(GRAFNAME)
            GO TO 10
         ELSE
            CALL RDGRAF (GRAFNAME,ITYPE,NELEM,RTNCODE)
         ENDIF
      ENDIF
      RETURN
      END
