$STORAGE:2
      SUBROUTINE GETHAL(HALOID)
C------------------------------------------------------------------------------
C     READ THE DOS ENVIRONMENT AREA AND SEARCH FOR THE HALO GRAPHICS ID.  THE 
C     HALO ID IS INDICATED BY HALOID=x, WHERE x IS A-Z, 0-9.
C
C     OUTPUT ARGUMENT:
C
C     HALOID  CHAR  HALO GRAPHICS ID.  IF NO HALOID IS FOUND, DEFAULT IS ' '
C------------------------------------------------------------------------------
      CHARACTER*100 STRBUF(5),ENVSTR
      CHARACTER*1   HALOID, NULL
      EQUIVALENCE (STRBUF,ENVSTR)
C
C   SET DEFAULT VALUES
C
      NULL   = CHAR(0)
      HALOID =' '
C
C   GET THE ENVIRONMENT AREA - RETURNED AS A SINGLE STRING
C
      CALL GETENV(ENVSTR)
      I = 0
C
C   SEARCH THE ENVIRONMENT STRING FOR THE HALO ID
C
   40 CONTINUE
      I = I + 1
C
C   CHECK FOR END OF ENVIRONMENT STRING
C
      IF (ENVSTR(I:I) .EQ. NULL) THEN
         RETURN
      ENDIF
C
C   CHECK TO SEE IF THIS IS THE STRING WANTED
C
      IF (ENVSTR(I:I+5) .EQ. 'HALOID') THEN
         HALOID=ENVSTR(I+7:I+7)
         RETURN
      ENDIF
C
C   FIND THE END OF THIS STRING (HENCE THE BEGINING OF THE NEXT)
C
      DO 80 J = I,999
         IF (ENVSTR(J:J) .EQ. NULL) THEN
            I = J
            GO TO 40
         ENDIF
   80 CONTINUE
      RETURN
      END
