$STORAGE:2
      SUBROUTINE GTRECL(IGRAPH,NUMCOL,NRECL,NCOLCHR)
C
C     INPUT:
C        IGRAPH
C        NUMCOL
C     OUTPUT:
C        NRECL
C        NCOLCHR
C
$INCLUDE:  'GRFPARM.INC'
C
C       ** CALCULATE NUMBER OF CHARACTERS PER COLUMN
      IF (IGRAPH.EQ.4) THEN
C          .. WINDROSE -- USE DATA FORMAT (F9.2)
         NCOLCHR = 9      
      ELSE
C          .. TIMESERIES, MAP, SKEWT -- USE MAXIMUM CHARACTERS IN COLUMN HEADER
         NCOLCHR = LENTXTD
      ENDIF
      NRECL=18+NUMCOL*(NCOLCHR+1)
C      
      RETURN
      END      