$STORAGE:2
      SUBROUTINE GTSTNLST(STNSTAT,R4WORK,MXSTAT,MAXWRK,MAXLST,LSTNAM,
     +                    RTNCODE) 
C
C       ** INPUT:
C             STNSTAT
C             R4WORK
C             MXSTAT......DIMENSION OF STNSTAT
C             MAXWRK......DIMENSION OF R4WORK
C             MAXLST......MAXIMUM NUMBER OF STATIONS THAT CAN BE SELECTED FOR
C                         LIST FILE FOR THE CURRENT MAP DEFINITION 
C             LSTNAM......CURRENT NAME OF THE STATION SELECTION LIST FILE.
C                         DEFAULT VALUE ON FIRST ENTRY INTO ROUTINE IS
C                         STNGEOG AND IS SET BY CALLING ROUTINE.  IF RE-ENTRY
C                         INTO THIS ROUTINE, VALUE IS LAST NAME CHOSEN.
C       ** OUTPUT:
C             LSTNAM......NAME OF THE STATION SELECTION FILE CHOSEN BY THE
C                         USER.  DEFAULT VALUE IS STNGEOG
C             RTNCODE.....ERROR FLAG  0=NORMAL EXIT  1=EXIT WITH F4/ESC
C
      INTEGER*2 MXSTAT,MAXWRK
      INTEGER*4 STNSTAT(MXSTAT)
      REAL*4    R4WORK(MAXWRK)
      CHARACTER*8 LSTNAM
      CHARACTER*1 RTNCODE
C
      CHARACTER*78 MSGTXT
      CHARACTER*64 HELPFILE
      CHARACTER*42  LSTENTRY
      CHARACTER*2  RTNFLAG
C      
      DATA HELPFILE/'P:\HELP\GTSTNLST.HLP'/
C
      RTNCODE='0'
      CALL GETMSG(580,MSGTXT)
      CALL GETMSG(999,MSGTXT)
      RTNFLAG = '  '
      CALL POSLIN(IROW,ICOL)
C
   20 CONTINUE
      CALL WRTFNC(11)
      CALL LOCATE(IROW,ICOL,IERR)
      NCHAR= LNG(MSGTXT)
      CALL WRTSTR(MSGTXT,NCHAR,14,0)
      CALL GETSTR(0,LSTNAM,8,15,1,RTNFLAG)      
      CALL CLRMSG(3)
      IF (RTNFLAG.EQ.'4F') THEN
         CALL CLRMSG(25-IROW)
         LSTNAM = ' '
         RTNCODE='1'
         GO TO 100
      ELSE IF (RTNFLAG.EQ.'1F') THEN
         CALL DSPWIN(HELPFILE)
      ELSE IF (RTNFLAG.EQ.'1S') THEN
   30    CONTINUE
         CALL LOCATE(IROW,ICOL,IERR)
         LSTENTRY = ' '
         ICNTRL=0
         OPEN (51,FILE='O:\DATA\MPSTNLST.IDX',STATUS='OLD',FORM='BINARY'
     +           ,ACCESS='DIRECT',RECL=43)
         CALL VALWIN(51,LSTENTRY,43,6,ICNTRL)
         CLOSE(51)
         IF (LSTENTRY.NE.' ') THEN
            LSTNAM = LSTENTRY(1:8)
            IF (ICNTRL.EQ.1) THEN
               CALL LOCATE(IROW+2,5,IERR)
               CALL OPSTNLST(STNSTAT,R4WORK,MXSTAT,MAXWRK,MAXLST,
     +                       LSTNAM)
               LSTNAM=' '
               GO TO 30
            ENDIF   
         ENDIF
      ELSE IF (RTNFLAG.EQ.'2F') THEN
         IF (LSTNAM.EQ.' ') THEN
             CALL WRTMSG(3,597,12,1,0,' ',0)
         ELSE
C
C             .. ACCEPT FILE NAME FOR STATION LIST               
            GO TO 100
         ENDIF   
      ENDIF       
      GO TO 20
C
  100 CONTINUE
      IF (LSTNAM.EQ.' ') LSTNAM='STNGEOG'      
C
      RETURN
      END
      