$STORAGE:2
      SUBROUTINE MPLIN(XWIN,YWIN,MPCODE)
C      
      INTEGER*2 MPCODE(5)
      REAL *4   XWIN(*),YWIN(*)
C      
      PARAMETER (MAXCHAR=22,MAXCHOICE=9,MAXITEM=MAXCHOICE+1)
      INTEGER*2 WINSTAT,HELPLVL,MPCSAV(5)
      CHARACTER*2 INCHAR
      CHARACTER *(MAXCHAR) CHOICE(MAXITEM)
      CHARACTER *3 MPMRK
C
      DATA MPMRK/'^X^'/
C
C       ** INITIAL WINDOW CONTROL VARIABLES;  WINSTAT IS SET TO DRAW MENU,
C          AND GET CHOICE; SCREEN IS NOT SAVED; SAVE FLAGS FOR MAP LINES
C
      WINSTAT = 2
      HELPLVL=1
      DO 10 I=1,5
         MPCSAV(I)=MPCODE(I)
   10 CONTINUE      
C
C       ** DISPLAY MENU; GET INITIAL INPUT FROM USER
C          NOTE:  INITIAL INPUT POSITIONS CURSOR AND DISPLAYS INITIAL
C                 ON/OFF SETTINGS FOR MAP LINE FLAGS; A SECOND INPUT IS
C                 REQUIRED TO TOGGLE FLAGS ON/OFF
C       .. DISPLAY MENU WITH MAP LINE LABELS
      MENUNUM = 1
      CALL RDMENU(MENUNUM,MAXITEM,CHOICE,NUMCHOICE,RTNCODE)      
      NUMCHOICE = NUMCHOICE-1
      CALL ARGMENU(WINSTAT,CHOICE,NUMCHOICE,XWIN(1),YWIN(1),HELPLVL,
     +             INCHAR)
C
C       .. DRAW WINDOW FOR ON/OFF SETTINGS
      CALL XYWNDO(XWINLF,YWINTP,XWINRT,YWINBT)
      XBXLF = XWINRT + .01
      YBXBT = YWINBT
      XBXRT = XBXLF + .05
      YBXTP = YWINTP
      ICNTRL = 1
      CALL WNDOBOX(ICNTRL,XBXLF,YBXTP,XBXRT,YBXBT)      
C
C       .. SET DOT TEXT SIZE 
      CALL INQDRA(MAXX,MAXY)
      IF (MAXY.GT.350) THEN
         CALL SETTEX(2,1,0,0)
      ELSE
         CALL SETTEX(1,1,0,0)
      END IF
C
C       .. DISPLAY MAP FLAG SETTINGS IN WINDOW      
      CALL SETTCL(0,3)
      CALL INQTSI(MPMRK,HEIGHT,CWIDTH)
      CALL INQWOR(XLOW,YLOW,XHIGH,YHIGH)
      DXWIN = XHIGH-XLOW
      XPOS = XLOW + MAX0(.5*(DXWIN-CWIDTH),0)
      DO 20 I=1,5
         IF (MPCODE(I).EQ.-1) GO TO 20
            YPOS = YHIGH - (I+1)*HEIGHT
            CALL MOVTCA(XPOS,YPOS)
            CALL DELTCU( )
            CALL TEXT(MPMRK)
   20 CONTINUE
C   
      IF (INCHAR.EQ.'ES') GO TO 100
      READ(INCHAR,'(I1)') NMPC
      IF (MPCODE(NMPC).GT.-1) THEN
         MPCODE(NMPC)=-1
      ELSE
         MPCODE(NMPC)=1
      ENDIF
C      
      ICNTRL = -1
      CALL WNDOBOX(ICNTRL,XBXLF,YBXTP,XBXRT,YBXBT)      
      WINSTAT=3
C      
   30 CONTINUE
      IF (INCHAR.EQ.'ES') GO TO 100
         READ(INCHAR,'(I1)') NMPC
         IF (MPCODE(NMPC).GT.-1) THEN
            MPCODE(NMPC)=-1
            CALL SETTCL(3,3)
         ELSE
            MPCODE(NMPC)=MAX0(MPCSAV(NMPC),0)
            CALL SETTCL(0,3)
         ENDIF
         ICNTRL = 2
         CALL WNDOBOX(ICNTRL,XBXLF,YBXTP,XBXRT,YBXBT)      
         YPOS = YHIGH - (NMPC+1)*HEIGHT
         CALL MOVTCA(XPOS,YPOS)
         CALL DELTCU( )
         CALL TEXT(MPMRK)
         ICNTRL = -1
         CALL WNDOBOX(ICNTRL,XBXLF,YBXTP,XBXRT,YBXBT)      
         CALL ARGMENU(WINSTAT,CHOICE,NUMCHOICE,XWIN(1),YWIN(1),
     +                HELPLVL,INCHAR)
      GO TO 30
C      
  100 CONTINUE
      ICNTRL = -2
      CALL WNDOBOX(ICNTRL,XBXLF,YBXTP,XBXRT,YBXBT)      
      WINSTAT=0
      CALL ARGMENU(WINSTAT,CHOICE,NUMCHOICE,XWIN(1),YWIN(1),HELPLVL,
     +             INCHAR)
C
      RETURN
      END      
      