$STORAGE:2
      SUBROUTINE NW2W(XNW,YNW,XW,YW)
C
C       ** OBJECTIVE:  CONVERT X,Y DISTANCE FROM NORMALIZED WORLD COORDINATE
C                      UNITS TO WORLD COORDINATE UNITS 
C
C       ** INPUT:
C             XNW....X-DISTANCE IN NORMALIZED WORLD COORDINATE UNITS      
C             YNW....Y-DISTANCE IN NORMALIZED WORLD COORDINATE UNITS      
C       ** OUTPUT:       
C             XW....X-DISTANCE IN WORLD COORDINATE UNITS
C             YW....Y-DISTANCE IN WORLD COORDINATE UNITS
C
      CALL INQWOR(XW1,YW1,XW2,YW2)              
C                    
      XW  = XNW*(XW2-XW1) + XW1             
      YW  = YNW*(YW2-YW1) + YW1
C
      RETURN
      END              
      SUBROUTINE W2NW(XW,YW,XNW,YNW)
C
C       ** OBJECTIVE:  CONVERT X,Y POSITION FROM WORLD COORDINATES 
C                      TO NORMALIZED WORLD COORDINATES
C
C       ** INPUT:
C             XW....X-DISTANCE IN WORLD COORDINATES
C             YW....Y-DISTANCE IN WORLD COORDINATES  
C       ** OUTPUT:       
C             XNW....X-DISTANCE IN NORMALIZED WORLD COORDINATES
C             YNW....Y-DISTANCE IN NORMALIZED WORLD COORDINATES
C              
      CALL INQWOR(XW1,YW1,XW2,YW2)              
C                    
      XNW = (XW-XW1)/(XW2-XW1)
      YNW = (YW-YW1)/(YW2-YW1)
C
      RETURN
      END              
      SUBROUTINE XSZNW2W(XSZNW,XSZW,YSZW)
C
C       ** OBJECTIVE: GIVEN A HORIZONTAL SIZE (DISTANCE) IN NORMALIZED WORLD 
C                     COORDINATES CALCULATE THE X/Y SIZES IN WORLD COORDINATES.
C       ** INPUT:
C              XSZNW...HORIZONTAL SIZE IN NORMALIZED WORLD COORDINATES
C       ** OUTPUT:
C              XSZW....SIZE IN X-DIRECTION IN WORLD COORDINATES -- HORIZONTAL
C              YSZW....SIZE IN Y-DIRECTION IN WORLD COORDINATES -- VERTICAL
C
C       ** GET WORLD COORDINATE UNITS AND WORLD ASPECT RATIO
C
      CALL INQWOR(XW1,YW1,XW2,YW2)
      CALL GETWASP(WASP)
C
C       ** CALCULATE SIZES IN WORLD COORDINATE UNITS
C     
C          .. SIZE IN Y-DIRECTION              
      XSZW = XSZNW*ABS(XW2-XW1)
C          .. SIZE IN X-DIRECTION           
      YSZW = XSZW*WASP
C
      RETURN
      END      
      SUBROUTINE YSZNW2W(YSZNW,XSZW,YSZW)
C
C       ** OBJECTIVE: GIVEN A VERTICAL SIZE (DISTANCE) IN NORMALIZED WORLD 
C                     COORDINATES CALCULATE THE X/Y SIZES IN WORLD COORDINATES.
C       ** INPUT:
C              YSZNW...VERTICAL SIZE IN NORMALIZED WORLD COORDINATES
C       ** OUTPUT:
C              XSZW....SIZE IN X-DIRECTION IN WORLD COORDINATES -- HORIZONTAL
C              YSZW....SIZE IN Y-DIRECTION IN WORLD COORDINATES -- VERTICAL
C
C       ** GET WORLD COORDINATE UNITS AND WORLD ASPECT RATIO
C
      CALL INQWOR(XW1,YW1,XW2,YW2)
      CALL GETWASP(WASP)
C
C       ** CALCULATE SIZES IN WORLD COORDINATE UNITS
C     
C          .. SIZE IN Y-DIRECTION              
      YSZW = YSZNW*ABS(YW2-YW1)
C          .. SIZE IN X-DIRECTION           
      XSZW = YSZW/WASP
C
      RETURN
      END      
