$STORAGE:2
      SUBROUTINE SETGPAL(PALETTE,PALDEF)
C
C   ROUTINE TO SET THE CLICOM GRAPHICS PALETTE TO THE PALETTE NUMBER
C   PASSED.  IF PALETTE IS < 1 OR > 12 THEN THIS ROUTINE WRAPS. (0->12,
C   13->1)
C
C   INPUT:
C     PALETTE...PALETTE NUMBER WANTED
C     PALDEF....DEFINITION OF ALL 12 POSSIBLE PALETTES.
C   OUTPUT:
C     PALETTE...PALETTE NUMBER ALLOWED (ADJUSTED FOR VALUES < 0 OR > 12)
C
      INTEGER*2 PALETTE, PALDEF(16,12)
C
      IF (PALDEF(1,12).GE.0) THEN
         MAXPAL = 12
      ELSE
         MAXPAL = 11
      END IF
      
      IF (PALETTE.LT.1) THEN
         PALETTE = MAXPAL
      ELSE IF (PALETTE.GT.MAXPAL) THEN
         PALETTE = 1
      END IF
      
      CALL REPPAL(PALDEF(1,PALETTE))
      RETURN
      END
      