$STORAGE:2
      PROGRAM       ENVRSIZE
C------------------------------------------------------------------------------
C     DETERMINE IF THERE IS ENOUGH FREE SPACE IN THE DOS ENVIRONMENT AREA FOR
C     CLICOM PROCESSING.  PRINT A WARNING MESSAGE TO CHANGE THE SIZE OF THE
C     ENVIRONMENT RATHER THAN GENERATE A DOS WARNING 'OUT OF ENVIRONMENT SPACE'
C------------------------------------------------------------------------------
      LOGICAL       OLDDOS
      CHARACTER*100 STRBUF(5), ENVSTR
      CHARACTER*1   NULL
      EQUIVALENCE   (STRBUF,ENVSTR)
C
C   SET DEFAULT VALUES
C
      NULL   = CHAR(0)
      OLDDOS = .FALSE.
      LENVR  = 150
      MAXENV = 512
C
C     GET VERSION OF DOS (NEEDED TO DETERMINE WHETHER WORDS OR PARAGRAPHS ARE
C     USED FOR SETTING THE ENVIRONMENT SPACE)
C
      CALL DOSVER(MAJVER,MINVER)
      IF (MINVER.GT.10) THEN
          MINVER = NINT(FLOAT(MINVER) / 10.)
      END IF
      IF (MAJVER.EQ.3.AND.MINVER.LT.2) THEN
          OLDDOS = .TRUE.
      END IF
C
C     GET THE ENVIRONMENT AREA - RETURNED AS A SINGLE STRING
C
      CALL GETENV(ENVSTR)
C
C     CHECK FOR END OF ENVIRONMENT STRING - 2 NULL BYTES 
C
      DO 30 I = I,499
         IF (ENVSTR(I:I) .EQ. NULL) THEN
            IF (ENVSTR(I+1:I+1) .EQ. NULL) THEN
               J = I + 1
               L = J
               GO TO 60
            ENDIF
         ENDIF
   30 CONTINUE
C
C     CHECK TO SEE IF AMPLE SPACE IN ENVIRONMENT FOR CLICOM VARIABLES
C
   60 IF (OLDDOS) THEN
         J      =  J / 16 + 1
         LENVR  = LENVR / 16
         MAXENV = MAXENV / 16
      ENDIF
      IF (J+LENVR .GT. MAXENV) THEN
         STOP 1
      ENDIF
      STOP ' '
      END
