      PROGRAM SETDOSLV
C
C     SET A DOS RETURN CODE OF 20.  USED TO PREVENT 'PROGRAM TOO BIG TO FIT
C     IN MEMORY' INFINITE BATCH FILE LOOP.
C
      IERR = 0
      CALL LOCATE(23,0,IERR)
      STOP 20
      END
      