$storage:2

C     PROGRAM WRTHLP
C
C  THIS ROUTINE PRINTS A TEXT FILE TO THE SCREEN WITH A PAUSE AT THE
C     END OF EACH PAGE.  IT STOPS IF AN F4 KEY IS HIT, SCOLLS UP IF A
C     PgUp IS HIT AND GOES TO THE NEXT PAGE IF A PgDn IS HIT..
C
C     NOTE: THE TEXT FILE NAME TO BE PRINTED MUST BE INCLUDED IN THE 
C           COMMAND LINE USED TO START THE PROGRAM
C           EXAMPLE: "WRTHLP \HELP\GENINFO.HLP"
C
      INTERFACE TO SUBROUTINE CMDLIN(ADDRES,LENGTH,RESULT)
      INTEGER*4 ADDRES[VALUE],LENGTH[VALUE]
      CHARACTER*1 RESULT
      END
C
      PROGRAM WRTHLP

      CHARACTER*1 CHAR
      CHARACTER*2 INCHAR
      CHARACTER*64 RESULT,FILNAM
      CHARACTER*80 TXTFIL(400)
C
      INTEGER*2 ILEN
      INTEGER*4 PSP,PSPNCHR,OFFSET
C
C  FOLLOWING STATEMENT REQUIRED FOR FORTRAN 3.3 - NOT ALLOWED IN FTN 4
c      EXTERNAL WRTHLP
C
C   LOCATE SEGMENTED ADDRESS OF THE BEGINNING OF THIS PROGRAM
C
      OFFSET = #00100000
      PSP = LOCFAR(WRTHLP)
C
C   COMPUTE THE BEGINNING OF THE PROGRAM SEGMENT PREFIX (PSP)
C
      PSP = (PSP - MOD(PSP,#10000)) - OFFSET 
C
C   LOCATE POSITION OF COMMAND PARAMTERS WITHIN THE PSP
C
      PSPNCHR = PSP + #80
      PSP = PSP + #81
C
C   PASS THE ADDRESS OF THE COMMAND PARAMTERS TO CMDLIN WHICH DECODES
C      THE COMMAND AND RETURNS IT AS RESULT.
C
      CALL CMDLIN(PSP,PSPNCHR,RESULT)
C
C   OPEN THE FILE
C
      ILEN = INT2(PSPNCHR)
      DO 20 I = 1,ILEN
         CHAR = RESULT(I:I)
         IF (CHAR.NE.' '.AND.CHAR.NE.',') THEN
            GO TO 30
         END IF
         ISTRT = I
   20 CONTINUE
   30 CONTINUE
      FILNAM = '  '
      FILNAM(1:ILEN) = RESULT(ISTRT+1:ILEN)
   40 CONTINUE
      OPEN (59,FILE=FILNAM,STATUS='OLD',FORM='FORMATTED'
     +      ,SHARE='DENYWR',MODE='READ',IOSTAT=IOCHK)
      IF (IOCHK.NE.0) THEN
         CALL OPENMSG(FILNAM,'WRTHLP      ',IOCHK)
         GO TO 40
      END IF
C
C   LOAD THE FILE TO BE PRINTED INTO TXTFIL (MAX 400 LINES)
C
      DO 50 I = 1,400
         READ(59,'(A80)',END=60) TXTFIL(I)
         NUMLINE = I
   50 CONTINUE
   60 CONTINUE
      CLOSE(59)
C
C   INITIALIZE THE SCREEN BORDER
C  
      IFG = 7
      CALL CLTEXT(1,1,IERR)

C   PRINT THE TEXT FILE
C
      IPAGE = 1
      CALL PAGWRT(IPAGE,NUMLINE,TXTFIL,IFG)
  100 CONTINUE
      CALL GETCHAR(0,INCHAR)
      IF (INCHAR.EQ.'DP') THEN
         CALL PAGWRT(IPAGE,NUMLINE,TXTFIL,IFG)
      ELSE IF (INCHAR.EQ.'UP') THEN
         IF (IPAGE.GT.2) THEN
            IPAGE = IPAGE - 2
            CALL PAGWRT(IPAGE,NUMLINE,TXTFIL,IFG)
         END IF
      ELSE IF (INCHAR.EQ.'HO') THEN
         IPAGE = 1
         CALL PAGWRT(IPAGE,NUMLINE,TXTFIL,IFG)
      ELSE IF (INCHAR.EQ.'4F') THEN
         CALL CLTEXT(0,0,IERR)
         STOP ' '
      END IF
      GO TO 100  
      END
