$STORAGE:2
C
C     PROGRAM WRTSCRN
C
C   ROUTINE TO DISPLAY A SCREEN OF TEXT 
C   NOTE: THE NAME OF THE FILE CONTAINING THE SCREEN DEFINITION MUST
C         BE INCLUDED IN THE DOS COMMAND LINE (MAX 32 CHARACTERS)
C         AND THE BORDER COLOR WANTED CAN BE PASSED AS THE SECOND
C         PARAMETER IN THE COMMAND LINE.
C         EXAMPLE: "WRTSCRN \FORM\INTROMNU.SCR 0"
C
      INTERFACE TO INTEGER*2 FUNCTION SYSTEM [C]
     +      (STRING [REFERENCE])
      CHARACTER*1 STRING
      END
C
      INTERFACE TO SUBROUTINE CMDLIN(ADDRES,LENGTH,RESULT)
      INTEGER*4 ADDRES[VALUE],LENGTH[VALUE]
      CHARACTER*1 RESULT
      END
C
      PROGRAM WRTSCRN
C
      CHARACTER*64 RESULT
      CHARACTER*64 SCRNFILE
      CHARACTER*1 OPTION,RE
      INTEGER*4 PSP,PSPNCHR,OFFSET
C
C  FOLLOWING STATEMENT REQUIRED FOR FORTRAN 3.3 - NOT ALLOWED IN FTN 4      
c      EXTERNAL WRTSCRN
C 
      DATA SCRNFILE /' :        .   '/
      RE = CHAR(13)
C
C   LOCATE SEGMENTED ADDRESS OF THE BEGINNING OF THIS PROGRAM
C
      OFFSET = #00100000
      PSP = LOCFAR(WRTSCRN)
C
C   COMPUTE THE BEGINNING OF THE PROGRAM SEGMENT PREFIX (PSP)
C
      PSP = (PSP - MOD(PSP,#10000)) - OFFSET 
C
C   LOCATE POSITION OF COMMAND PARAMTERS WITHIN THE PSP
C
      PSPNCHR = PSP + #80
      PSP = PSP + #81
C
C   PASS THE ADDRESS OF THE COMMAND PARAMTERS TO CMDLIN WHICH DECODES
C      THE COMMAND AND PASSES IT BACK AS RESULT. 
C
      CALL CMDLIN(PSP,PSPNCHR,RESULT)
C
C   FIND THE END OF THE FIRST COMMAND PARAMETER
C      
      DO 30 I = 1,32
         IF (RESULT(I:I).EQ.' ') THEN
            GO TO 35
         END IF
         NAMLEN = I
   30 CONTINUE
   35 CONTINUE
      SCRNFILE = RESULT(1:NAMLEN) 
C
C   CHECK FOR THE SECOND COMMAND OPTION - BORDER COLOR
C
      IBORD = -1
      DO 150 I = NAMLEN+1,64
         OPTION = RESULT(I:I)
         IF (OPTION.NE.' '.AND.OPTION.NE.','.AND.OPTION.NE.RE) THEN
            READ(OPTION,'(I1)',ERR=180) IBORD
            GO TO 200
         END IF
  150 CONTINUE
      GO TO 200
  180 CONTINUE
      CALL WRTMSG(4,137,12,1,1,OPTION,1)
  200 CONTINUE
C  
      CALL SAVRES(1,3,0,SCRNFILE,IBORD,IERR)
C
      CALL LOCATE(22,0,IERR)
      END
