$STORAGE:2
C
C     PROGRAM WTBTDSD2
C
C     ** OBJECTIVE:  PROGRAM CONSTRUCTS THE CALL FROM DSDFMT1.BAT TO 
C                    DSDFMT2.BAT BASED ON THE DATA FILE NAME ASSOCIATED
C                    WITH THE DATASET DIRECTORY FORM AND
C                    WRITES THE CALL IN THE FILE CALLDSD2.BAT
C                    
C     ** NOTE:  THE VERIFY RECORD CODE (0 OR 1) MUST BE INCLUDED ON THE 
C               COMMAND LINE CALLING THIS ROUTINE 
C               EXAMPLE: "WTBTDSD2 0"
C
      INTERFACE TO SUBROUTINE CMDLIN(ADDRES,LENGTH,RESULT)
      INTEGER*4 ADDRES[VALUE],LENGTH[VALUE]
      CHARACTER*1 RESULT
      END
C
C----------------------------------------------------------------------
C
      PROGRAM WTBTDSD2
C
      INTEGER*4   NUMREC
      CHARACTER*1 VERFCODE
      CHARACTER*6 OUTFRMT
      CHARACTER*8 DEASFIL
      CHARACTER*21 OUTFIL
      CHARACTER*22 FILNAME
      CHARACTER*24 FORMNAME
      CHARACTER*20 LINE
C
      CHARACTER*64 RESULT
      INTEGER*4    PSP,PSPNCHR,OFFSET
C
      DATA FORMNAME/'DATASET DIRECTORY'/
C
C       ** LOCATE SEGMENTED ADDRESS OF THE BEGINNING OF THIS PROGRAM
C
      OFFSET = #00100000
      PSP = LOCFAR(WTBTDSD2)
C
C       ** COMPUTE THE BEGINNING OF THE PROGRAM SEGMENT PREFIX (PSP)
C
      PSP = (PSP - MOD(PSP,#10000)) - OFFSET 
C
C       ** LOCATE POSITION OF COMMAND PARAMTERS WITHIN THE PSP
C
      PSPNCHR = PSP + #80
      PSP = PSP + #81
C
C       ** PASS THE ADDRESS OF THE COMMAND PARAMETERS TO CMDLIN WHICH DECODES
C          THE COMMAND AND RETURNS IT AS RESULT.
C
      CALL CMDLIN(PSP,PSPNCHR,RESULT)
C
C       ** PULL THE COMMAND (REC-TYPE) OUT OF THE RESULT
C
      VERFCODE = RESULT(1:1)
C
C       ** GET ACTUAL FILE NAME ASSOCIATED WITH THE DATAEASE FORM NAME
C
      CALL FNDFIL(FORMNAME,FILNAME,NUMREC)
      DEASFIL = FILNAME(3:10)
C
C       ** OPEN BATCH FILE THAT WILL CONTAIN THE CALL TO DSDFMT2.BAT
C
      OUTFIL = 'P:\BATCH\CALLDSD2.BAT'
      OPEN (63,FILE=OUTFIL,STATUS='UNKNOWN',FORM='FORMATTED')
C 
C       ** WRITE THE CALL TO DSDFMT2.BAT WITH THE ACTUAL DATAEASE FILE NAME
C                DSDFMT2 0 DATAAAAx  
C                DSDFMT2 1 DATAAAAx 
C
      WRITE(LINE,500) VERFCODE,DEASFIL
  500 FORMAT('DSDFMT2 ',A1,1X,A8)
      CALL GETFRMT(LINE,OUTFRMT)
      WRITE(63,OUTFRMT) LINE
      CLOSE(63)
C
      STOP ' '
      END