ECHO OFF
FL /FPi /Od /4Nb /c GRAFMAN.FOR 
IF EXIST HALODVXX.OBJ GOTO OKHALO
COPY \CLICOM\HALO\HALODVXX.OBJ
IF EXIST HALODVXX.OBJ GOTO OKHALO
ECHO The link for GRFMN requires HALODVXX.OBJ and HALOF.LIB.  Please 
ECHO copy HALODVXX.OBJ to this directory and make sure HALOF.LIB is included
ECHO in the %LIB% directory.
GOTO EXIT
:OKHALO
IF EXIST PCTRL2.OBJ GOTO OKPC2
COPY \CLICOM\SRC\OBJ\PCTRL2.OBJ
IF EXIST PCTRL2.OBJ GOTO OKPC2
ECHO The link for GRFMN2 requires PCTRL2.OBJ
GOTO EXIT
:OKPC2
IF EXIST PCTRL134.OBJ GOTO OKPC134
COPY \CLICOM\SRC\OBJ\PCTRL134.OBJ
IF EXIST PCTRL134.OBJ GOTO OKPC134
ECHO The link for GRFMN134 requires PCTRL134.OBJ
GOTO EXIT
:OKPC134
ECHO The overlay link for GRFMN requires the object code for all
ECHO overlayed subroutines outside of their libraries.  This batch file 
ECHO will retrieve the necessary object code if you ask it to.
QUERY Do you want to retrieve the object code from PLTUTIL.LIB (Y/N)? @YN
IF ERRORLEVEL 2 GOTO ENDLIB1
LIB %LIB%\PLTUTIL *TIMESER *DRWGRD *DRWAX *PLTBOX;
LIB %LIB%\PLTUTIL *WINDROSE;
LIB %LIB%\PLTUTIL *SKEWT *SKEWFUNC *PLTWIND *PLTSND *SETZOOM;
LIB %LIB%\PLTUTIL *CLRMAN;
LIB %LIB%\PLTUTIL *LBLMAN *CHNGLBL *CHNGLGND *CHNGRING *CHNGTXAX *FLUSH;
LIB %LIB%\PLTUTIL *OUTMAN *GRFPRNT *PRNTOP *PRNTMAN *WRTGSCRN;
LIB %LIB%\PLTUTIL *CONMAP;
LIB %LIB%\PLTUTIL *CUSTCOL;
LIB %LIB%\PLTUTIL *PICKFONT *TXTCOLR *TXTFONT *TXTLOC *TXTSIZ;
:ENDLIB1
QUERY Do you want to retrieve the object code from UTILITY.LIB (Y/N)? @YN
IF ERRORLEVEL 2 GOTO ENDLIB2
LIB %LIB%\UTILITY *GETFRM *WRTFNC *VALWIN *DSPWIN *DSPFRM;
:ENDLIB2
QUERY Do you want to retrieve the object code from KWLIB.LIB (Y/N)? @YN
IF ERRORLEVEL 2 GOTO ENDLIB3
LIB %LIB%\KWLIB *KWBORD *KWINQL  *KWINTC *KWLAND;
LIB %LIB%\KWLIB *CONTOUR *KWGRID *KSETUP *KWAREA *KWTRAN *KWNSTR *KWLAB;
LIB %LIB%\KWLIB *KWPLOT *KWSCAL *SCLSETUP *GCTPSP *GTRNZ1 *MILLER *EQRECT *CNTR2 *KWWEVR;
:ENDLIB3
ECHO START LINK FOR GRFMN2
LINK @LGMN2.LNK
ECHO COMPLETE LINK FOR GRFMN2
IF ERRORLEVEL 2 GOTO EXIT
ECHO START LINK FOR GRFMN134
LINK @LGMN134.LNK
ECHO COMPLETE LINK FOR GRFMN134
:EXIT
