ECHO OFF
FL /FPi /Od /4Nb /c dataqc.FOR 
IF EXIST HALODVXX.OBJ GOTO OKHALO
copy \clicom\halo\halodvxx.obj
IF EXIST HALODVXX.OBJ GOTO OKHALO
ECHO The link for DATAQC requires HALODVXX.OBJ and HALOF.LIB.  Please 
ECHO copy HALODVXX.OBJ to this directory and make sure HALOF.LIB is included
ECHO in the %LIB% directory.
GOTO EXIT
:OKHALO
ECHO The overlay link for DATAQC requires the object code for all
ECHO overlayed subroutines outside of their libraries.  This batch file 
ECHO will retrieve the necessary object code if you ask it to.
QUERY Do you want to retrieve the object code from the libraries (Y/N)? @YN
IF ERRORLEVEL 2 GOTO LABEL1
LIB %LIB%\UTILITY *GETMNU *DSPWIN *VALWIN *GETFRM *WRTFNC;
LIB %LIB%\CORELIB *UAPLOT *AQC12 *EDIT *RAOBQC *LINEQC *GENVARS *BANNER *DISLIMS *CHKKEY;
LIB %LIB%\PLTUTIL *SKEWT *SKEWFUNC *PLTWIND *PLTSND *SETZOOM *GRFTXT;
LIB %LIB%\KWLIB *KWBORD *KWINQL *KWLAND *KSETUP *KWAREA *KWTRAN *KWNSTR *KWLAB;
LIB %LIB%\KWLIB *KWPLOT *KWSCAL *SETUP *GCTPSP *GTRNZ1 *MILLER *EQRECT;
:LABEL1
REM ----- SPECIAL COMPILATION OF DRWLGND AND SETZOOM
IF EXIST DRWLGND.OBJ COPY DRWLGND.OBJ *.OSV
IF EXIST SETZOOM.OBJ COPY SETZOOM.OBJ *.OSV
COPY \CLICOM\SRC\INCLUDES\QCSAVBUF.INC SAVBUF.INC
FL /FPi /Od /4Nb /I\CLICOM\SRC\CORE\GRAFMAIN /c \CLICOM\SRC\CORE\GRAFSUB\DRWLGND.FOR 
FL /FPi /Od /4Nb /I\CLICOM\SRC\CORE\GRAFMAIN /c \CLICOM\SRC\CORE\GRAFSUB\SETZOOM.FOR 
DEL SAVBUF.INC
REM -----
LINK @LDATAQC.LNK
DEL DRWLGND.OBJ
DEL SETZOOM.OBJ
IF EXIST DRWLGND.OSV REN DRWLGND.OSV *.OBJ
IF EXIST SETZOOM.OSV REN SETZOOM.OSV *.OBJ
:EXIT
