$storage:2
C
C   PROGRAM RNDATA
C
C   ROUTINE TO READ THE CONTROL FILE USED BY LDDATA AND
C     RENAME THE OUTPUT FILE THAT LDDATA WROTE.
C
C     NOTE:  THE DATA-TYPE CODE (MLY,DLY...) MUST BE INCLUDED ON THE
C            COMMAND LINE CALLING THIS ROUTINE
C            EXAMPLE: "RNDATA DLY"
C
      INTERFACE TO SUBROUTINE CMDLIN(ADDRES,LENGTH,RESULT)
      INTEGER*4 ADDRES[VALUE],LENGTH[VALUE]
      CHARACTER*1 RESULT
      END

C----------------------------------------------------------------------
      PROGRAM RNDATA

      CHARACTER*1 NULL
      CHARACTER*3 DDSID,RECTYPE
      CHARACTER*16 DATFILE
      CHARACTER*22 ERRFIL,NEWFIL
      CHARACTER*30 INDATA
C
      CHARACTER*64 RESULT
      INTEGER*4 PSP,PSPNCHR,OFFSET
C
C  FOLLOWING STATEMENT REQUIRED FOR FORTRAN 3.3 - NOT ALLOWED IN FTN 4      
c      EXTERNAL RNDATA
      NULL = CHAR(0)
C
C   LOCATE SEGMENTED ADDRESS OF THE BEGINNING OF THIS PROGRAM
C
      OFFSET = #00100000
      PSP = LOCFAR(RNDATA)
C
C   COMPUTE THE BEGINNING OF THE PROGRAM SEGMENT PREFIX (PSP)
C
      PSP = (PSP - MOD(PSP,#10000)) - OFFSET 
C
C   LOCATE POSITION OF COMMAND PARAMTERS WITHIN THE PSP
C
      PSPNCHR = PSP + #80
      PSP = PSP + #81
C
C   PASS THE ADDRESS OF THE COMMAND PARAMTERS TO CMDLIN WHICH DECODES
C      THE COMMAND AND RETURNS IT AS RESULT.
C
      CALL CMDLIN(PSP,PSPNCHR,RESULT)
C
C   PULL THE COMMAND (REC-TYPE) OUT OF THE RESULT
C
      RECTYPE = RESULT(1:3)
C
C   TO FIND OUT THE DATASET-ID READ THE DATA FILE WRITTEN BY LDDATA
C
      DATFILE = 'Q:CLIMDATA.DAT'
  100 CONTINUE
      OPEN(21,FILE=DATFILE,STATUS='OLD',FORM='BINARY',IOSTAT=IOCHK)
      IF (IOCHK.NE.0) THEN
         IF (IOCHK.EQ.6416) THEN
            STOP ' '
         ELSE
            ERRFIL = DATFILE
            CALL OPENMSG(ERRFIL,'RNDATA      ',IOCHK)
            GO TO 100 
         END IF
      END IF
      READ(21,END=200) INDATA 
      CLOSE(21)
      IF (RECTYPE.EQ.'MLY'.OR.RECTYPE.EQ.'mly') THEN
         DDSID = INDATA(7:9)
      ELSE IF (RECTYPE.EQ.'10D'.OR.RECTYPE.EQ.'10d') THEN
         DDSID = INDATA(13:15)
      ELSE IF (RECTYPE.EQ.'DLY'.OR.RECTYPE.EQ.'dly') THEN
         DDSID = INDATA(12:14)
      ELSE IF (RECTYPE.EQ.'SYN'.OR.RECTYPE.EQ.'syn') THEN
         DDSID = INDATA(6:8)
      ELSE IF (RECTYPE.EQ.'HLY'.OR.RECTYPE.EQ.'hly') THEN
         DDSID = INDATA(10:12)
      ELSE IF (RECTYPE.EQ.'15M'.OR.RECTYPE.EQ.'15m') THEN
         DDSID = INDATA(28:30)
      ELSE IF (RECTYPE.EQ.'U-A'.OR.RECTYPE.EQ.'u-a') THEN
         DDSID = INDATA(6:8)
      END IF
C
C   DELETE THE OLD DATA FILE 
C
      NEWFIL = 'Q:AAAAAA.DAT'
      NEWFIL(3:5) = RECTYPE
      NEWFIL(6:8) = DDSID
      OPEN(61,FILE=NEWFIL,STATUS='OLD',FORM='BINARY',IOSTAT=IOCHK)
      IF (IOCHK.EQ.0) THEN
         CLOSE(61,STATUS='DELETE')
      ELSE
         CLOSE(61)
      END IF      
C
C   RENAME THE DATA FILE 
C
      NEWFIL(13:13) = NULL
      DATFILE(15:15) = NULL
      CALL RNAME2(DATFILE,NEWFIL,IERR)
      IF (IERR.NE.1) THEN
         RESULT = ' '
         RESULT(1:14) = DATFILE
         RESULT(15:15) = ','
         RESULT(16:27) = NEWFIL
         CALL WRTMSG(4,158,12,1,1,RESULT,27)
      END IF
  200 CONTINUE
      STOP ' '
      END
