$STORAGE:2

      SUBROUTINE CHKSTN(STNID,STNLIST,ISTN,MAXROW,RTNCODE)
C
C   ROUTINE TO CHECK THE CURRENT STNID AGAINST A LIST OF STATIONS 
C   ASSOCIATED WITH A PRE-DEFINED MAP.
C
C   INPUT:
C      STNID....ID OF THE STN TO BE CHECKED
C      STNLIST..LIST OF THE STATIONS WHOSE LOCATIONS PLACE THEM WITHIN
C               THE BOUNDARIES OF THE PRESENT MAP. (CREATED BY SELAREA)
C      MAXROW...DIMENSION OF STNLIST
C   OUTPUT:
C      ISTN.....IF STNID IS FOUND IN STNLIST THEN ISTN GIVES THE LINE
C               AT WHICH IT IS FOUND.  IT IS USED AN AN INDEX INTO 
C               STNLIST TO RETRIEVE THE STN LOCATION.
C      RTNCODE..RESULTS OF THE CHECK.
C         RTNCODE = '0' THEN THE STNID IS IN STNLIST
C         RTNCODE = '1' THEN STNID WAS NOT FOUND IN STNLIST.   
C  
      CHARACTER*8 STNID,STNLIST(MAXROW)
      CHARACTER*1 RTNCODE
      RTNCODE = '1'
      ISTN = 0
C
      DO 100 I = 1,MAXROW
         IF (STNID.EQ.STNLIST(I)) THEN
            ISTN = I
            RTNCODE = '0'
            RETURN
         END IF
100   CONTINUE
      RETURN
      END
