$STORAGE:2
C
      SUBROUTINE GETDATA(IDKEY,RTNCODE)
C
C  THIS ROUTINE LOADS ANY DATA ALREADY ENTERED FOR THE EDIT FRAME 
C  SPECIFIED BY IDKEY.
C
$INCLUDE: 'VAL1.INC'
$INCLUDE: 'INDEX.INC'
C
      CHARACTER*1 RTNCODE
      CHARACTER*21 IDKEY
C
C     RETURN CODE (RTNCODE)
C       '0' = KEY FOUND
C       '1' = END PROGRAM REQUESTED
C       '2' = KEY NOT FOUND
C
C   OPEN THE DATA AND INDEX FILES
C
      CALL OPENFILES(1)
C
C   FIND THE LOCATION OF THE RECORD WANTED AND READ THE DATA
C
      CALL BINDATA(IDKEY,RTNCODE)
C
      IF (RTNCODE.EQ.'0')THEN
         READ (20,REC=RECNUM)IDKEY,((VALARRAY(I,J),I=1,NUMELEM),
     +         J=1,NUMLINE),(((FLAGARRAY(K,L,M),M=1,2),K=1,NUMELEM),
     +         L=1,NUMLINE)
      END IF
C
      CLOSE (19)
      CLOSE (20)
C
      RETURN
      END
