$STORAGE:2

      SUBROUTINE LDBANR(ITYPE,RECTYPE,FIELD,RTNCODE)
C
C     SUBROUTINE TO DISPLAY THE BANNER AND SOLICIT; STATION ID, DATA
C     SET ID, AND TIME FRAME DATA AND LOAD; STATION HISTORY DATA,
C     VALIDATION PARAMETERS AND EXISTING OBSERVATIONS.
C
C     IT ALSO OPENS THE INDEX AND DATA FILES (19,20 RESPECTIVELY)
C
$INCLUDE: 'INDEX.INC'
$INCLUDE: 'VAL1.INC'
C
      CHARACTER*1 RTNCODE
      CHARACTER*2 HOURLBL(24)
      CHARACTER*3 RECTYPE
      CHARACTER*8 FIELD(6)
C
      INTEGER*2 DSETID,OLDDDS
      DATA OLDDDS/-99/
C
      RTNCODE = '0'
C
C     SET UP THE SCREEN
C
      CALL CLS
      CALL SETMOD(3,IERR)
C
C   RETRIEVE THE FIELDS FROM THE USER
C      
   20 CONTINUE
      CALL GTLDBN(RECTYPE,DSETID,FIELD,RTNCODE)

      IF (RTNCODE.EQ.'1')THEN
         RETURN
      END IF
C
C   IF THIS IS A NEW DATASET THEN OPEN THE SETUP FILE AND LOAD THE
C   ELEMENT CODES AND COLUMN HEADERS AND NAME THE INDEX AND DATA FILES
C
      IF (DSETID.NE.OLDDDS) THEN
         OLDDDS = DSETID
         CALL GETSET(DSETID,ITYPE,RECTYPE,HOURLBL,RTNCODE)
         IF (RTNCODE.NE.'0') THEN
            GO TO 20
         END IF
      END IF
C
      RETURN
      END
C
$PAGE
C
      SUBROUTINE GTLDBN(RECTYPE,DSETID,FIELD,RTNCODE)
C
C     SUBROUTINE TO DISPLAY THE BANNER LINE AND RETRIEVE ACCEPTABLE
C     RESPONSES
C
      CHARACTER*1 RTNCODE
      CHARACTER*2 RTNFLAG
      CHARACTER*3 RECTYPE
C
      INTEGER*2 DSETID
      CHARACTER*8 FIELD(6)
      CHARACTER*8 FORMNAME(2)
      CHARACTER*64 HELPFILE
C
      DATA FORMNAME /'LD3FLDS','LD5FLDS'/
      DATA HELPFILE/'P:\HELP\LDFLDS.HLP'/
C
      RTNCODE = '0'
C
20    CONTINUE
      CALL LOCATE (0,0,IERR)
      IF (RECTYPE.EQ.'MLY'.OR.RECTYPE.EQ.'10D') THEN
         IFORM = 1
      ELSE
         IFORM = 2
      END IF
30    CONTINUE      
      RTNFLAG = 'SS'
      CALL GETFRM(FORMNAME(IFORM),HELPFILE,FIELD,8,RTNFLAG)
      IF (RTNFLAG.EQ.'4F')THEN
         RTNCODE = '1'
         RETURN
      END IF
C
C     DECODE AND VALIDATE THE REPLIES
C
      IF (FIELD(1).EQ.'   ') THEN
         CALL WRTMSG(3,101,12,1,1,' ',0)
         GO TO 20
      END IF
      CALL CLRMSG(3)
      CALL CLRMSG(2)
      READ (FIELD(1),'(I3)')DSETID
C
      RETURN
      END
