$STORAGE:2
      SUBROUTINE RDHRLBL(ITYPE,HOURLBL,RTNCODE)
C
C       ** OBJECTIVE:  READ THE HOUR LABELS FOR HOURLY OR SYNOPTIC DATA
C                      FROM P:DATA\DATAQC.PRM    
C       ** INPUT:
C             ITYPE......DATA TYPE INDEX --  4=SYNOPTIC  5=HOURLY
C       ** OUTPUT:
C             HOURLBL....LIST OF HOUR LABELS 
C             RTNCODE....ERROR FLAG -- '0'=OK   '1'=ERROR IN READING DATAQC.PRM
C
      INTEGER*2    ITYPE
      CHARACTER*1  RTNCODE
      CHARACTER*2  HOURLBL(*),CNLIN
      CHARACTER*80 SCRATCH
C
      RTNCODE = '0'
C
      IF (ITYPE.EQ.4) THEN
C          .. SYNOPTIC DATA
         NSKIP = 46      
         NLBL = 8
      ELSE 
C          .. HOURLY DATA      
         NSKIP = 40
         NLBL = 24
      ENDIF
C        
C       ** OPEN THE DATAQC PARAMETER FILE
C
   20 CONTINUE
      OPEN(9,FILE='P:\DATA\DATAQC.PRM',STATUS='OLD',IOSTAT=IOCHK)
      IF(IOCHK.NE.0) THEN
         CALL OPENMSG('P:\DATA\DATAQC.PRM   ','RDHRLBL      ',IOCHK)
         GO TO 20
      END IF   
C    
      DO 40 I = 1,NSKIP
         READ(9,'(1X)',END=910)
  40  CONTINUE
      READ(9,'(A80)',END=910) SCRATCH
      CALL PARSE1(SCRATCH,80,NLBL,2,HOURLBL,RTNCODE)
      IF (RTNCODE.GT.'0') THEN
          GO TO 910
      END IF               
      CLOSE(9)
      RETURN
C
C       ** REACH THIS POINT IF DATAQC.PRM FILE IS TOO SHORT SO AN EOF WAS 
C          READ, OR A RECORD CONTAINED A FORMAT ERROR.
C
  910 CONTINUE
      CLOSE(9)
      WRITE(CNLIN,'(I2)') NSKIP+1
      CALL WRTMSG(3,174,12,1,1,CNLIN,2)
      RTNCODE = '1'
      RETURN
      END